# frozen_string_literal: true

require 'fileutils'
require 'json'
require_relative '../../core/logger'
require_relative '../../core/generated_marker'
require_relative '../../core/converter_generator_core'
require_relative 'swift_component_generator'
require_relative 'adapter_generator'

module SjuiTools
  module SwiftUI
    module Generators
      # iOS profile over the shared converter-scaffolder body
      # (lib/core/converter_generator_core.rb — byte-identical mirror of
      # shared/core/converter_generator_core.rb, pinned by
      # spec/core/shared_core_mirror_spec.rb). The overwrite flow, registry
      # patching, attribute-definition JSON and type mapping live in the
      # shared core; this class owns the SwiftUI scaffold template, the
      # Swift/adapter sub-generators and the Xcode membership exceptions.
      class ConverterGenerator < ::JsonUIShared::ConverterGeneratorCore
        def initialize(name, options = {})
          @name = name
          # Keep original PascalCase name for component, add Converter suffix for class
          @component_pascal_case = name  # e.g., MyTestCard
          @class_name = name + "Converter"  # e.g., MyTestCardConverter
          @options = options
          @logger = Core::Logger
          @command = build_command_string('sjui g converter')
        end

        def generate
          @logger.info "Generating custom converter: #{@class_name}"
          track_scaffold_files
          keep_children_declaration

          # Create converter file
          create_converter_file

          # Update mappings file
          update_mappings_file

          # Create Swift file using separate generator (pass command for comment)
          swift_options = @options.merge(command: @command)
          swift_generator = SwiftComponentGenerator.new(@name, swift_options)
          swift_generator.generate

          # Generate adapter file if adapter_directory is configured (pass command for comment)
          adapter_generator = AdapterGenerator.new(@name, swift_options)
          adapter_generator.generate

          # After the scaffold: it says "kept" when the run wrote none.
          warn_outside_attribute_types

          # The attribute definition, after the scaffold (as on kjui and
          # rjui): a run that takes children but kept a leaf-form adapter or
          # converter writes a leaf, and names them. Until 1.8.121 it was
          # written between the mappings and the Swift file, before anything
          # the run kept was known (ticket
          # leaf-turned-container-keeps-its-leaf-scaffold-silently).
          generate_attribute_definition_file

          @logger.success "Successfully generated converter: #{@class_name}"
          @logger.info "Converter file created at: views/extensions/#{@name}_converter.rb"
          @logger.info "Mappings file updated with '#{@component_pascal_case}' => '#{@class_name}'"

          # Update membership exceptions to exclude the extensions directory
          update_membership_exceptions_if_needed
        end

        private

        def extensions_dir
          # Check if we're in a test app or main SwiftJsonUI
          if File.exist?(File.join(Dir.pwd, 'sjui_tools'))
            # Test app structure
            File.join(Dir.pwd, 'sjui_tools', 'lib', 'swiftui', 'views', 'extensions')
          else
            # Main SwiftJsonUI structure
            File.join(Dir.pwd, 'tools', 'sjui_tools', 'lib', 'swiftui', 'views', 'extensions')
          end
        end

        def converter_file_name
          "#{to_snake_case(@name)}_converter.rb"
        end

        def registry_spec
          {
            file: File.join(extensions_dir, 'converter_mappings.rb'),
            const: 'CONVERTER_MAPPINGS',
            mapping_line: "          '#{@component_pascal_case}' => '#{@class_name}',",
            initial_content: <<~RUBY
              # frozen_string_literal: true

              # This file maps custom component types to their converter classes
              # Auto-generated by sjui g converter command

              module SjuiTools
                module SwiftUI
                  module Views
                    module Extensions
                      CONVERTER_MAPPINGS = {
                        '#{@component_pascal_case}' => '#{@class_name}',
                      }.freeze
                    end
                  end
                end
              end
            RUBY
          }
        end

        def attr_defs_dir
          File.join(extensions_dir, 'attribute_definitions')
        end

        def command_string
          @command
        end

        def json_marker(source:, generator:)
          Core::GeneratedMarker.json_marker(source: source, generator: generator)
        end

        def converter_template
          marker_header = Core::GeneratedMarker.scaffold_header(
            source: @component_pascal_case,
            generator: @command,
            prefix: "#"
          )
          <<~RUBY
            # frozen_string_literal: true

            #{marker_header}

            require_relative '../base_view_converter'
            require_relative '../responsive_helper'
            require_relative '../../../core/attribute_types'

            module SjuiTools
              module SwiftUI
                module Views
                  module Extensions
                    class #{@class_name} < BaseViewConverter
                      def initialize(component, indent_level = 0, action_manager = nil, converter_factory = nil, view_registry = nil, binding_registry = nil)
                        super(component, indent_level, action_manager, binding_registry)
                        @factory = converter_factory
                        @registry = view_registry
                        # The names BaseViewConverter reads when it renders a
                        # child (render_child_honoring_visibility). Without
                        # them every child of a container comes out empty.
                        @converter_factory = converter_factory
                        @view_registry = view_registry
                      end

                      def convert
                        # Responsive override (regression: sjui-markdown-text-converter-ignores-responsive)
                        # When this component has a `responsive` block, route through
                        # ResponsiveHelper.generate_leaf_function so the size-class
                        # branches (maxWidth / centerHorizontal / padding / margin /
                        # background / cornerRadius / ...) take effect. Without this
                        # the override silently drops, since BaseViewConverter#convert
                        # does not check responsive — that's ViewConverter's role for
                        # built-in `View` containers, and each extension converter has
                        # to opt in on its own surface.
                        if JsonUIShared::ResponsiveResolver.responsive?(@component) && @factory
                          func_name = @factory.next_responsive_name
                          func_code = SjuiTools::SwiftUI::Views::ResponsiveHelper.generate_leaf_function(
                            func_name, @component, @factory, @indent_level,
                            @action_manager, @registry, @binding_registry
                          )
                          @factory.register_responsive_function(func_code)
                          add_line "\#{func_name}()"
                          return generated_code
                        end

            #{generate_container_check}

                        # Collect parameters
                        params = []
            #{generate_parameter_collection}

                        if is_container
                          # Container component with children
                          if params.empty?
                            add_line "#{@component_pascal_case} {"
                          else
                            add_line "#{@component_pascal_case}("
                            indent do
                              params.each_with_index do |param, index|
                                if index == params.length - 1
                                  add_line param
                                else
                                  add_line "\#{param},"
                                end
                              end
                            end
                            add_line ") {"
                          end

                          # The children in one VStack, as the Dynamic adapter
                          # passes them. Handed over bare, several children
                          # reached a content slot drawn in a Group and every
                          # modifier on the component — its accessibility
                          # container and identifier included — was applied
                          # to each child: measured (the codegen host, iOS
                          # 26.5, 2026-09-25) the container's id found twice
                          # with two children. Ticket
                          # sjui-custom-container-takes-its-childrens-identifiers.
                          indent do
                            add_line "VStack(alignment: .leading, spacing: 0) {"
                            indent do
                              process_children
                            end
                            add_line "}"
                          end

                          add_line "}"
                        else
                          # Non-container component
                          if params.empty?
                            add_line "#{@component_pascal_case}()"
                          else
                            add_line "#{@component_pascal_case}("
                            indent do
                              params.each_with_index do |param, index|
                                if index == params.length - 1
                                  add_line param
                                else
                                  add_line "\#{param},"
                                end
                              end
                            end
                            add_line ")"
                          end
                        end

            #{generate_modifiers_code}

                        generated_code
                      end

                      private

                      def component_name
                        "#{@component_pascal_case}"
                      end

                      # Process children components (handles both 'children' and 'child' keys)
                      def process_children
                        # Handle both 'children' and 'child' keys (both are arrays)
                        child_array = @component['children'] || @component['child']

                        if child_array && child_array.is_a?(Array)
                          child_array.each do |child|
                            # Honors the child's `visibility` (VisibilityWrapper),
                            # as every built-in container does.
                            render_child_honoring_visibility(child)
                          end
                        end
                      end

                      # A literal the layout gives a prop, written as the Swift the
                      # component's declared type takes — by the shared attribute
                      # type vocabulary (lib/core/attribute_types.rb), the table
                      # the component itself was scaffolded from. nil when it
                      # cannot be written; the caller then passes nothing and says so.
                      # @param is_binding_attr [Boolean] if true, use $data. (Binding), otherwise data. (read-only)
                      def format_value(value, type, is_binding_attr: false)
                        # Check if it's a binding expression @{propertyName}
                        if value.is_a?(String) && value.start_with?('@{') && value.end_with?('}')
                          # Extract property name and return as binding or read-only
                          property_name = value[2..-2]  # Remove @{ and }
                          prefix = is_binding_attr ? "$data" : "data"
                          return "\#{prefix}.\#{property_name}"
                        end
                        # Outside the vocabulary, kept from before it existed.
                        return format_edge_insets_value(value) if type.to_s.downcase.delete('?') == 'edgeinsets'

                        JsonUIShared::AttributeTypes.swift_literal(type, value) do |canonical, literal|
                          format_color_value(literal) if canonical == 'color' && literal.is_a?(String)
                        end
                      end

                      def unwritten(key, value, type)
                        warn "[sjui] \#{component_name}.\#{key}: the layout's \#{value.inspect} is not a \#{type} " \\
                             "literal this converter can write — the prop keeps its default. Give a \#{type} value, " \\
                             "or bind it (@{…})."
                      end

                      def format_color_value(value)
                        return nil unless value
                        if value.is_a?(String) && value.start_with?('#')
                          # Parse hex color
                          hex = value.delete('#')
                          r = hex[0..1].to_i(16) / 255.0
                          g = hex[2..3].to_i(16) / 255.0
                          b = hex[4..5].to_i(16) / 255.0
                          "Color(red: \#{r}, green: \#{g}, blue: \#{b})"
                        elsif value.is_a?(Hash)
                          r = value['red'] || value['r'] || 0
                          g = value['green'] || value['g'] || 0
                          b = value['blue'] || value['b'] || 0
                          "Color(red: \#{r}, green: \#{g}, blue: \#{b})"
                        else
                          "SwiftJsonUIConfiguration.shared.getColor(for: \\"\#{value}\\") ?? Color.clear"
                        end
                      end

                      def format_edge_insets_value(value)
                        return nil unless value
                        if value.is_a?(Hash)
                          top = value['top'] || 0
                          leading = value['leading'] || value['left'] || 0
                          bottom = value['bottom'] || 0
                          trailing = value['trailing'] || value['right'] || 0
                          "EdgeInsets(top: \#{top}, leading: \#{leading}, bottom: \#{bottom}, trailing: \#{trailing})"
                        elsif value.is_a?(Numeric)
                          "EdgeInsets(top: \#{value}, leading: \#{value}, bottom: \#{value}, trailing: \#{value})"
                        else
                          nil
                        end
                      end
                    end
                  end
                end
              end
            end
          RUBY
        end

        def generate_container_check
          case @options[:is_container]
          when true
            "            # Force container mode\n            is_container = true\n"
          when false
            "            # Force non-container mode\n            is_container = false\n"
          else
            "            # Auto-detect container based on children or child\n            is_container = (@component['children'] && !@component['children'].empty?) || (@component['child'] && !@component['child'].empty?)\n"
          end
        end

        def generate_parameter_collection
          return "" if !@options[:attributes] || @options[:attributes].empty?

          lines = []
          @options[:attributes].each do |key, type|
            # Check if this is a binding property (starts with @)
            # @-prefixed attributes generate @Binding var in Swift → use $data. (Binding)
            # Non-@ attributes generate let in Swift → use data. (read-only)
            is_binding = key.start_with?('@')
            actual_key = is_binding ? key[1..-1] : key
            data_prefix = is_binding ? "$data" : "data"
            # Check if we need to handle the key existing vs nil differently
            if is_binding
              # Binding property - always expect @{} format, use $data. (Binding)
              lines << "            if @component['#{actual_key}']"
              lines << "              value = @component['#{actual_key}']"
              lines << "              if value.is_a?(String) && value.start_with?('@{') && value.end_with?('}')"
              lines << "                property_name = value[2..-2]"
              lines << '                params << "' + "#{actual_key}: #{data_prefix}." + '#{property_name}"'
              lines << "              else"
              lines << "                # For binding properties, assume direct property binding if not @{} format"
              lines << '                params << "' + "#{actual_key}: #{data_prefix}." + '#{value}"'
              lines << "              end"
              lines << "            end"
            else
              # By key, not by value: a `false` the layout gives is a value too.
              lines << "            if @component.key?('#{actual_key}')"
              lines << "              value = @component['#{actual_key}']"
              lines << "              if value.is_a?(String) && value.start_with?('@{') && value.end_with?('}')"
              lines << "                # Handle binding - use #{data_prefix}. (#{is_binding ? 'Binding' : 'read-only'})"
              lines << "                property_name = value[2..-2]"
              lines << '                params << "' + "#{actual_key}: #{data_prefix}." + '#{property_name}"'
              lines << "              else"
              lines << "                # Handle static value"
              lines << "                formatted_value = format_value(value, '#{type}')"
              lines << "                if formatted_value"
              lines << '                  params << "' + "#{actual_key}: " + '#{formatted_value}"'
              lines << "                else"
              lines << "                  unwritten('#{actual_key}', value, '#{type}')"
              lines << "                end"
              lines << "              end"
              lines << "            end"
            end
          end
          lines.join("\n")
        end

        def generate_modifiers_code
          "            # Apply default modifiers\n            apply_modifiers"
        end

        def to_camel_case(str)
          str.split('_').map(&:capitalize).join
        end

        def update_membership_exceptions_if_needed
          # Try to find and update the Xcode project file
          require_relative '../../core/project_finder'
          require_relative '../../core/pbxproj_manager'

          if Core::ProjectFinder.setup_paths && Core::ProjectFinder.project_file_path
            begin
              manager = Core::PbxprojManager.new(Core::ProjectFinder.project_file_path)
              manager.setup_membership_exceptions
              @logger.info "Updated Xcode project to exclude extensions directory"
            rescue => e
              @logger.warn "Could not update Xcode project exclusions: #{e.message}"
            end
          end
        end
      end
    end
  end
end
