# frozen_string_literal: true

# `sjui setup` の HotLoader 注入は、生成した区間だけを所有する。
#
# WHY（2026-09-14、票 sjui-setup-silently-deletes-user-code-…）
#
# 旧実装は削除を 4 か所の正規表現で行い、うち 1 本が
#   `func application\w+\([^{]*\{\s*#if DEBUG[^}]*`
# で本文を飲んで**閉じ括弧を残さなかった**。HotLoader 以外の `#if DEBUG` を持つ
# ライフサイクルメソッド（検体 E）を持つ一般的なアプリでは、初回 setup で
# brace が -1 になりビルドが壊れる。文字列 assert では「marker 0」としか
# 見えないので、**この検体は compile 腕でしか捕まらない**。
#
# さらに 2 つ:
#  - 既存のライフサイクルメソッドを持つアプリには注入されず、HotLoader が黙って死ぬ（検体 B）
#  - エントリのガードが `content.include?("HotLoader.instance")` だったため、
#    **既に setup 済のプロジェクトには以後どんな変更も届かない**（検体 F）。
#    印字は "already exists" と成功の顔で出る。scene 移行が構造的に配れない形。
#
# 腕は境界の両側を同じ表に置く: 生成節の前(D2)/後(D) にユーザー行、
# マーカー在り(冪等)/無し(移行する)。
require 'spec_helper'
require 'tmpdir'
require "stringio"
require "English"
require 'uikit/xcode_project/setup/app_delegate_setup'

# ⚠️ describe ブロック直下の定数は Object に定義され、他の spec と衝突する
#   （実測: この spec の SHAPES が pair_scan_closure_spec.rb の SHAPES を上書きし、
#    向こうの 11 例が赤くなった。自分のスイートだけ緑にして渡すところだった）
module HotLoaderRegionFixtures
end

RSpec.describe SjuiTools::UIKit::XcodeProject::Setup::AppDelegateSetup do
  HotLoaderRegionFixtures::MARKER = 'sjui:hotloader:begin'
  HotLoaderRegionFixtures::OLD_VERSION_REGION = "// sjui:hotloader:begin v0 — generated by old setup"

  # `did_finish_body` は既定で素の 1 行。旧生成物の検体では、実際の setup が
  # 書き込んでいた UIViewCreator の 2 行と HotLoader 3 行組を持たせる
  # （この形を fixture に入れるまで、行剥がしを no-op にする変異が生き残った＝
  #  腕が弱いのではなく検体が届いていなかった）。
  def shell(inner, did_finish_body = "        return true\n")
    <<~SWIFT
      import UIKit
      @main
      class AppDelegate: UIResponder, UIApplicationDelegate {
          var window: UIWindow?

          func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
      #{did_finish_body}    }

      #{inner}}
    SWIFT
  end

  HotLoaderRegionFixtures::LEGACY_DID_FINISH_BODY = <<~SWIFT
          UIViewCreator.prepare()
          UIViewCreator.copyResourcesToDocuments()
          #if DEBUG
          HotLoader.instance.isHotLoadEnabled = true
          #endif
          return true
  SWIFT

  HotLoaderRegionFixtures::LEGACY_DID_BECOME_ACTIVE = <<~SWIFT
        func applicationDidBecomeActive(_ application: UIApplication) {
            #if DEBUG
            HotLoader.instance.isHotLoadEnabled = true
            #endif
    %s    }
  SWIFT

  HotLoaderRegionFixtures::SHAPES = {
    bare: '',
    existing_methods: <<~SWIFT,
          func applicationDidBecomeActive(_ application: UIApplication) {
              Analytics.resume()
          }

          func applicationDidEnterBackground(_ application: UIApplication) {
              Analytics.pause()
          }

          func applicationWillTerminate(_ application: UIApplication) {
              Analytics.flush()
          }
    SWIFT
    user_line_after_region: format(HotLoaderRegionFixtures::LEGACY_DID_BECOME_ACTIVE, "            Analytics.resume()\n"),
    user_line_before_region: <<~SWIFT,
          func applicationDidBecomeActive(_ application: UIApplication) {
              Analytics.resume()
              #if DEBUG
              HotLoader.instance.isHotLoadEnabled = true
              #endif
          }
    SWIFT
    other_if_debug: <<~SWIFT,
          func applicationDidBecomeActive(_ application: UIApplication) {
              #if DEBUG
              print("debug")
              #endif
              Analytics.resume()
          }
    SWIFT
    legacy_generated: format(HotLoaderRegionFixtures::LEGACY_DID_BECOME_ACTIVE, ''),
    # G: 今日までの setup が実際に書いていた完全な旧生成物（didFinishLaunching に
    #    UIViewCreator 2 行 + HotLoader 3 行組を持つ）。この検体が無いと、
    #    行剥がしの片側（単独行）を殺す変異が無症状で通る。
    legacy_full: format(HotLoaderRegionFixtures::LEGACY_DID_BECOME_ACTIVE, ''),
    # H: 前の版のマーカー区間を持つ生成物。版を上げた setup が既存プロジェクトに
    #    届くこと（区間は貼り替わり、区間の外のユーザー行は残ること）の検体。
    #    これが無いと「マーカー区間の剥がし」を no-op にする変異が無症状で通る。
    old_version_region: <<~SWIFT
          func applicationDidBecomeActive(_ application: UIApplication) {
              #{HotLoaderRegionFixtures::OLD_VERSION_REGION}
              #if DEBUG
              HotLoader.instance.isHotLoadEnabled = true
              #endif
              // sjui:hotloader:end
              Analytics.resume()
          }
    SWIFT
  }.freeze

  # 検体ごとの didFinishLaunching 本文
  HotLoaderRegionFixtures::DID_FINISH = Hash.new("        return true\n").merge(
    legacy_full: HotLoaderRegionFixtures::LEGACY_DID_FINISH_BODY
  ).freeze

  # 実エントリを撃つ。抽出した private メソッドではない
  # （抽出計器での測定は「その関数の主張」であって「コマンドの主張」ではない:
  #  初報はそれで、早期 return の手前で起きない欠陥を major として起票した）。
  HotLoaderRegionFixtures::SCENE_DELEGATE = <<~SWIFT
    import UIKit

    class SceneDelegate: UIResponder, UIWindowSceneDelegate {
        var window: UIWindow?

        func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        }
    }
  SWIFT

  # scene: :ok（SceneDelegate + Manifest あり）/ :no_file / :no_manifest
  def run_setup(dir, source, scene: :ok)
    app = File.join(dir, 'App')
    FileUtils.mkdir_p(app)
    FileUtils.mkdir_p(File.join(dir, 'App.xcodeproj'))
    scene_path = File.join(app, 'SceneDelegate.swift')
    File.write(scene_path, HotLoaderRegionFixtures::SCENE_DELEGATE) if scene != :no_file && !File.exist?(scene_path)
    plist = scene == :no_manifest ? "<plist><dict></dict></plist>\n" : "<plist><dict><key>UIApplicationSceneManifest</key><dict/></dict></plist>\n"
    File.write(File.join(app, 'Info.plist'), plist) unless File.exist?(File.join(app, 'Info.plist'))
    path = File.join(app, 'AppDelegate.swift')
    File.write(path, source) unless source.nil?
    out = StringIO.new
    begin
      $stdout = out
      described_class.new(File.join(dir, 'App.xcodeproj')).add_hotloader_functionality
    ensure
      $stdout = STDOUT
    end
    scene_text = File.exist?(scene_path) ? File.read(scene_path) : nil
    [File.read(path), out.string, scene_text]
  end

  def user_lines(text)
    text.scan('Analytics.').size + text.scan('print("debug")').size
  end

  HotLoaderRegionFixtures::SHAPES.each do |name, inner|
    context "検体 #{name}" do
      let(:source) { shell(inner, HotLoaderRegionFixtures::DID_FINISH[name]) }

      it '消費側が書いた行を 1 行も失わない' do
        Dir.mktmpdir do |dir|
          after, = run_setup(dir, source)
          expect(user_lines(after)).to eq(user_lines(source)),
            "user 行 #{user_lines(source)} → #{user_lines(after)}\n#{after}"
        end
      end

      it 'brace が均衡する（E はここが 5:6 になってビルドが壊れていた）' do
        Dir.mktmpdir do |dir|
          after, = run_setup(dir, source)
          expect(after.count('{')).to eq(after.count('}')), after
        end
      end

      it 'on/off は SceneDelegate の 3 メソッドに入る（v2: application* には入れない）' do
        Dir.mktmpdir do |dir|
          after, _msg, scene = run_setup(dir, source)
          %w[sceneDidBecomeActive sceneDidEnterBackground sceneDidDisconnect].each do |m|
            expect(scene).to match(/func\s+#{m}[^}]*HotLoader\.instance\.isHotLoadEnabled/m),
              "SceneDelegate の #{m} に注入されていない\n#{scene}"
          end
          # iOS 27 では application* は呼ばれない。ここに残すと黙って死ぬので入れない。
          %w[applicationDidBecomeActive applicationDidEnterBackground applicationWillTerminate].each do |m|
            expect(after).not_to match(/func\s+#{m}[^}]*HotLoader\.instance\.isHotLoadEnabled/m),
              "AppDelegate の #{m} に残っている\n#{after}"
          end
          # didFinishLaunching の prepare / copyResources は AppDelegate に残る
          expect(after).to include('UIViewCreator.prepare()')
        end
      end

      it '2 回目は何も変えない（冪等）' do
        Dir.mktmpdir do |dir|
          first, = run_setup(dir, source)
          second, msg = run_setup(dir, nil)
          expect(second).to eq(first)
          expect(msg).to include('already up to date')
        end
      end

      it '生成行が重複しない（UIViewCreator は 1 回ずつ）' do
        Dir.mktmpdir do |dir|
          after, = run_setup(dir, source)
          expect(after.scan('UIViewCreator.prepare()').size).to eq(1), after
          expect(after.scan('UIViewCreator.copyResourcesToDocuments()').size).to eq(1), after
          expect(after.scan('HotLoader.instance.isHotLoadEnabled').size).to eq(1), after
        end
      end

      it '取り残された `#if DEBUG` が無い（三行組の剥がしが片側だけ効くと空の条件が残る）' do
        Dir.mktmpdir do |dir|
          after, = run_setup(dir, source)
          # 中身の消えた `#if DEBUG` / `#endif` の対が残っていないこと。
          # ⚠️ 全体の `#if DEBUG` 数を HotLoader 行数と比べる形にすると、消費側が
          #   自分で書いた `#if DEBUG`（検体 other_if_debug）を欠陥として数える。
          #   欠陥の署名は「空の対」であって「総数」ではない。
          empty_pairs = after.lines.each_cons(2).count { |a, b| a.strip == '#if DEBUG' && b.strip == '#endif' }
          expect(empty_pairs).to eq(0), after
        end
      end

      it '生成した区間はマーカーで囲まれている（AppDelegate 1 / SceneDelegate 3）' do
        Dir.mktmpdir do |dir|
          after, _msg, scene = run_setup(dir, source)
          expect(after.scan(HotLoaderRegionFixtures::MARKER).size).to eq(1)
          expect(scene.scan(HotLoaderRegionFixtures::MARKER).size).to eq(3)
          expect(after.scan('sjui:hotloader:end').size).to eq(1)
          expect(scene.scan('sjui:hotloader:end').size).to eq(3)
        end
      end
    end
  end

  it '前の版の区間は貼り替わり、区間の外のユーザー行は残る（版を上げた setup が既存プロジェクトに届く）' do
    Dir.mktmpdir do |dir|
      after, msg, scene = run_setup(dir, shell(HotLoaderRegionFixtures::SHAPES[:old_version_region]))
      expect(msg).not_to include('already up to date'), '古い版の区間が素通りした ⇒ 版を上げても届かない'
      expect(after).not_to include(HotLoaderRegionFixtures::OLD_VERSION_REGION)
      expect(after.scan(HotLoaderRegionFixtures::MARKER).size).to eq(1)
      expect(scene.scan(HotLoaderRegionFixtures::MARKER).size).to eq(3)
      expect(after).to include('Analytics.resume()')
    end
  end

  it '区間の外に消費側が書いた HotLoader 行は残る（生成物と手書きの境界）' do
    Dir.mktmpdir do |dir|
      hand_written = shell(<<~SWIFT)
            func applicationDidBecomeActive(_ application: UIApplication) {
                HotLoader.instance.isHotLoadEnabled = true
            }
      SWIFT
      after, = run_setup(dir, hand_written)
      # ⚠️ 検体は**裸の** `= true` 行にする。`= shouldHotLoad` でも行末コメント付きでも
      #   剥がしの述語（`= (true|false)\s*$`）に当たらず、枝を戻す逆変異で赤くならない
      #   ＝ 判別力ゼロの腕になる（2 回踏んで実測で気づいた）。
      #   ⚠️ 裸の 1 行は「消費側の手書き」と「旧生成物の残骸」を綴りで区別できない。
      #   区別できない以上、消さない側に倒す（消したら復元できないが、残れば消せる）。
      # 生成区間を落としてから見る。区間の中の生成行と綴りが同じなので、
      # 総数で数えると枝を戻す逆変異でも通ってしまう（2 回踏んだ）。
      outside = []
      inside = false
      after.each_line do |line|
        inside = true if line.include?(HotLoaderRegionFixtures::MARKER)
        outside << line unless inside
        inside = false if line.include?('sjui:hotloader:end')
      end
      expect(outside.join).to include('HotLoader.instance.isHotLoadEnabled = true'),
        "区間の外の手書き行を消した\n#{after}"
    end
  end

  it 'v1 の生成メソッド（区間だけの本体）は v2 移行で AppDelegate から消える' do
    Dir.mktmpdir do |dir|
      # 区間しか持たない = 完全に生成物。剥がしたら空になるので、畳んで消す。
      # ⚠️ 消費側の行が 1 行でも在れば消さない（上の old_version_region 検体がその側）。
      pure_generated = shell(<<~SWIFT)
            func applicationDidBecomeActive(_ application: UIApplication) {
                #{HotLoaderRegionFixtures::OLD_VERSION_REGION}
                #if DEBUG
                HotLoader.instance.isHotLoadEnabled = true
                #endif
                // sjui:hotloader:end
            }
      SWIFT
      after, _msg, scene = run_setup(dir, pure_generated)
      expect(after).not_to include('func applicationDidBecomeActive'),
        "空になった生成メソッドが AppDelegate に残った\n#{after}"
      expect(scene).to match(/func\s+sceneDidBecomeActive[^}]*HotLoader/m)
      expect(after.count('{')).to eq(after.count('}'))
    end
  end

  # ── scene が無い / Manifest が無い ──────────────────────────────
  # 黙って AppDelegate 側へ戻すと、アプリが scene 化した後の再 setup で旧型に
  # 巻き戻り、消費側は壊れたことに気づけない。だから警告して**戻さない**。
  %i[no_file no_manifest].each do |missing|
    it "SceneDelegate が届かない（#{missing}）ときは警告し、AppDelegate へ戻さない" do
      Dir.mktmpdir do |dir|
        after, msg, = run_setup(dir, shell(''), scene: missing)
        expect(msg).to include('iOS 27'), msg
        expect(msg).to match(/UIScene|UIApplicationSceneManifest/), msg
        %w[applicationDidBecomeActive applicationDidEnterBackground applicationWillTerminate].each do |m|
          expect(after).not_to include("func #{m}"), "AppDelegate へ戻した\n#{after}"
        end
        # didFinishLaunching 側の準備は届く（ホットリロードの on/off だけが欠ける）
        expect(after).to include('UIViewCreator.prepare()')
      end
    end
  end

  it '警告は毎回出る（届かないままの状態を「最新」と黙らない）' do
    Dir.mktmpdir do |dir|
      _, first, = run_setup(dir, shell(''), scene: :no_file)
      _, second, = run_setup(dir, nil, scene: :no_file)
      expect(first).to include('iOS 27')
      expect(second).to include('iOS 27'), "2 回目が黙った ⇒ 届いていないのに up to date 扱い\n#{second}"
    end
  end

  # ガードの述語が「マーカー」を見ていること。境界の両側を同じ例に置く。
  # 変異「述語を include?("HotLoader.instance") に戻す」で旧生成物側だけが赤くなる。
  it '旧生成物（マーカー無し・HotLoader 在り）は移行され、マーカー在りだけが素通りする' do
    Dir.mktmpdir do |dir|
      legacy, msg = run_setup(dir, shell(HotLoaderRegionFixtures::SHAPES[:legacy_generated], HotLoaderRegionFixtures::DID_FINISH[:legacy_generated]))
      expect(msg).not_to include('already up to date'),
        '旧生成物が素通りした ⇒ 既 setup プロジェクトに移行が届かない'
      expect(legacy).to include(HotLoaderRegionFixtures::MARKER)

      _, msg2 = run_setup(dir, nil)
      expect(msg2).to include('already up to date')
    end
  end

  # 唯一 E を捕まえられる窓。文字列 assert では marker 0 としか見えない。
  # 母艦の swiftc は UIKit を持たない（macOS SDK）ので、iPhoneSimulator SDK を直に指す。
  # SDK が無い環境では skip（「走らなかった」を緑にしない）。
  describe 'compile 腕（iOS SDK で typecheck）' do
    HotLoaderRegionFixtures::TARGET = 'arm64-apple-ios17.0-simulator'
    HotLoaderRegionFixtures::STUBS = <<~SWIFT
      final class HotLoaderStub { var isHotLoadEnabled = false; static let instance = HotLoaderStub() }
      typealias HotLoader = HotLoaderStub
      enum UIViewCreator { static func prepare() {}; static func copyResourcesToDocuments() {} }
      enum Analytics { static func resume() {}; static func pause() {}; static func flush() {} }
    SWIFT

    def self.ios_sdk
      @ios_sdk ||= `xcrun --sdk iphonesimulator --show-sdk-path 2>/dev/null`.strip
    end

    def typecheck(swift)
      Dir.mktmpdir do |dir|
        file = File.join(dir, 'Probe.swift')
        File.write(file, swift)
        out = `xcrun -sdk iphonesimulator swiftc -typecheck -target #{HotLoaderRegionFixtures::TARGET} #{file} 2>&1`
        [$CHILD_STATUS.nil? ? $?.success? : $?.success?, out]
      end
    end

    # `import SwiftJsonUI` と `@main` は落とす: 前者はここにモジュールが無く（HotLoader /
    # UIViewCreator は上の HotLoaderRegionFixtures::STUBS が代わりを務める）、後者は fragment に entry point を
    # 2 つ作らないため。UIKit は本物を読ませる（stub で代用しない）。
    def compilable(app_delegate_source)
      HotLoaderRegionFixtures::STUBS + app_delegate_source.lines.reject { |l| l.start_with?('@main', 'import SwiftJsonUI') }.join
    end

    before do
      skip "iPhoneSimulator SDK が無い（#{self.class.ios_sdk.empty? ? 'xcrun 不在' : 'SDK 不明'}）" if self.class.ios_sdk.empty?
    end

    # 対照: この腕が構造の壊れを実際に見ていることを、同じ表の中で示す。
    # 検体は旧実装が検体 E に対して実際に出した形（閉じ括弧が 1 つ多い）。
    it '対照: 閉じ括弧が 1 つ多い生成物は落ちる（腕が構造を見ている証拠）' do
      broken = compilable(<<~SWIFT)
        import UIKit
        class AppDelegate: UIResponder, UIApplicationDelegate {
            func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                return true
            }

            }
            func applicationDidBecomeActive(_ application: UIApplication) {
                Analytics.resume()
            }
        }
      SWIFT
      ok, out = typecheck(broken)
      expect(ok).to be(false), "壊れた生成物が通った ⇒ この腕は構造を見ていない\n#{out}"
    end

    HotLoaderRegionFixtures::SHAPES.each_key do |name|
      it "検体 #{name} の生成物が typecheck を通る" do
        Dir.mktmpdir do |dir|
          after, _msg, scene = run_setup(dir, shell(HotLoaderRegionFixtures::SHAPES[name], HotLoaderRegionFixtures::DID_FINISH[name]))
          ok, out = typecheck(compilable(after))
          expect(ok).to be(true), "AppDelegate:\n#{out}\n---\n#{after}"
          # v2 では on/off の本体は SceneDelegate 側。同じ窓で見る。
          ok2, out2 = typecheck(compilable(scene))
          expect(ok2).to be(true), "SceneDelegate:\n#{out2}\n---\n#{scene}"
        end
      end
    end
  end
end
