"""``jui sync_tool`` — sync project-local platform tools with the home install.

Each subproject that runs ``rjui build`` / ``sjui build`` / ``kjui build`` needs
a project-local copy of the relevant platform tool under
``<platform_root>/<tool>_tools/``. Those copies are required because generated
custom-converter files use ``require_relative`` and therefore resolve paths
from their own location — the global ``~/.jsonui-cli/<tool>_tools/`` cannot
serve those requires alone.

The tradeoff: once copied, the project-local tree drifts away from the
upstream code in ``~/.jsonui-cli/``. ``jui sync_tool`` brings the project
copies back in line while preserving the ``extensions/`` directories, which
hold per-project custom converters generated by ``rjui g converter`` etc.

Resolution:

1. Walk up from CWD to find ``jui.config.json``.
2. For each platform in ``config.platforms``, map to a tool dir:
   ios → ``sjui_tools``, android → ``kjui_tools``, web → ``rjui_tools``.
3. Source root: ``$JSONUI_CLI_PATH`` env > ``~/.jsonui-cli/`` > error.
4. Target root: ``<project>/platforms.<name>.root/<tool>_tools/``.
5. Copy every file from source into target, skipping anything whose path
   contains a ``/extensions/`` segment. Files in the target that are under
   ``extensions/`` are left alone.
6. With ``--prune``, also delete files in target (outside ``extensions/``)
   that don't exist in source — keeps the target in strict parity.

Notes:
- ``.pyc`` / ``__pycache__`` / ``.DS_Store`` / ``.git`` are always skipped.
- ``--dry-run`` shows what would change without touching disk.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path

from datetime import datetime, timezone

from ..core.config_manager import ConfigManager
from ..version import source_sha, toolchain_version


PLATFORM_TO_TOOL = {
    "ios": "sjui_tools",
    "android": "kjui_tools",
    "web": "rjui_tools",
}

#: Consumer-side toolchain-coordinate stamp: <project>/.jsonui-cli/sync-meta.json.
#: Written on every successful sync so a bug report can name the exact
#: toolchain (version + source SHA) the project's tool copies came from.
SYNC_META_DIRNAME = ".jsonui-cli"
SYNC_META_FILENAME = "sync-meta.json"

# Files that live at the CLI-root ``shared/core/`` (a SIBLING of each tool
# dir) but are read at runtime by the tools via a ``<tool_dir>/shared/core/``
# path. ``jui sync_tool`` mirrors only the tool tree, so these would never
# reach a project-local install without explicit distribution. Each entry is
# a path relative to ``shared/core/`` in the source root; it is copied to the
# same relative path under ``<target_tool_dir>/shared/core/``.
#
# font_weight_mapping.json: the weight-name → platform-enum table shared by
# sjui/kjui/rjui font helpers. Missing it used to make sjui round every
# looked-up weight to ``.regular`` in consumers (see bug report).
SHARED_CORE_PAYLOADS = (
    "font_weight_mapping.json",
)

# Dirs never synced. Anything install/build-derived that each project
# regenerates via its own toolchain stays out of the copy.
SKIP_DIR_NAMES = {
    "__pycache__",
    ".git",
    "node_modules",   # hotloader and similar Node subprojects — run `npm install` per project
    ".bundle",        # Bundler per-project config
    "vendor",         # bundled gems / Ruby deps
    "tmp",
    "log",
    ".rspec_status",
    ".byebug_history",
    "coverage",
    ".pytest_cache",
}
SKIP_FILE_NAMES = {".DS_Store"}
SKIP_SUFFIXES = {".pyc", ".pyo", ".gem", ".log", ".tmp"}


def register_sync_tool_command(subparsers: argparse._SubParsersAction) -> None:
    """Register ``jui sync_tool``."""
    parser = subparsers.add_parser(
        "sync_tool",
        help="Sync project-local platform tools with the home install (~/.jsonui-cli/), preserving extensions/",
    )
    parser.add_argument(
        "--from",
        dest="source",
        help="Source directory (default: $JSONUI_CLI_PATH or ~/.jsonui-cli)",
    )
    parser.add_argument(
        "--platform",
        choices=sorted(PLATFORM_TO_TOOL.keys()),
        help="Sync only one platform (default: all platforms in jui.config.json)",
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help="Delete files in the target that don't exist in the source (outside extensions/)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print actions without modifying any files",
    )


def _resolve_source_root(override: str | None) -> Path:
    """Return the source CLI directory, or raise if none is usable."""
    if override:
        root = Path(override).expanduser().resolve()
    elif os.environ.get("JSONUI_CLI_PATH"):
        root = Path(os.environ["JSONUI_CLI_PATH"]).expanduser().resolve()
    else:
        root = Path.home() / ".jsonui-cli"
    if not root.exists():
        raise FileNotFoundError(
            f"Source CLI directory not found: {root}. "
            "Set $JSONUI_CLI_PATH or run the JsonUI bootstrap."
        )
    return root


def _is_extensions_path(rel_path: Path) -> bool:
    """True if rel_path traverses an ``extensions`` directory."""
    return "extensions" in rel_path.parts


def _should_skip(name: str, is_dir: bool) -> bool:
    if is_dir and name in SKIP_DIR_NAMES:
        return True
    if not is_dir:
        if name in SKIP_FILE_NAMES:
            return True
        if any(name.endswith(suffix) for suffix in SKIP_SUFFIXES):
            return True
    return False


def _iter_source_files(source: Path):
    """Yield (relative_path, absolute_path) for every syncable file under source."""
    if not source.exists():
        return
    for dirpath, dirnames, filenames in os.walk(source):
        # prune skippable dirs in-place so os.walk doesn't descend
        dirnames[:] = [d for d in dirnames if not _should_skip(d, True)]
        dp = Path(dirpath)
        for fn in filenames:
            if _should_skip(fn, False):
                continue
            abs_path = dp / fn
            rel = abs_path.relative_to(source)
            if _is_extensions_path(rel):
                continue
            yield rel, abs_path


def _distribute_shared_core(
    source_root: Path,
    target_tool_dir: Path,
    *,
    dry_run: bool,
) -> int:
    """Copy CLI-root ``shared/core/`` payloads into ``<tool>/shared/core/``.

    The tool font helpers resolve ``<tool_dir>/shared/core/font_weight_mapping.json``
    as their first candidate. That path only exists in a project-local install
    if we place it there — the sibling ``shared/`` tree is not part of the tool
    dir that :func:`_sync_one_tool` mirrors. Returns the number of files
    copied or updated.
    """
    changed = 0
    src_core = source_root / "shared" / "core"
    for rel in SHARED_CORE_PAYLOADS:
        src_file = src_core / rel
        if not src_file.exists():
            # Nothing to distribute (e.g. minimal source tree) — skip quietly.
            continue
        dst_file = target_tool_dir / "shared" / "core" / rel
        if dst_file.exists() and _files_equal(src_file, dst_file):
            continue
        if dry_run:
            action = "update" if dst_file.exists() else "copy"
            print(f"  would {action}: shared/core/{rel}")
        else:
            dst_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_file, dst_file)
        changed += 1
    return changed


def _sync_one_tool(
    source_tool_dir: Path,
    target_tool_dir: Path,
    platform_root: Path,
    *,
    prune: bool,
    dry_run: bool,
    source_root: Path | None = None,
) -> dict[str, int]:
    """Mirror source_tool_dir into target_tool_dir, preserving extensions/.

    Also propagates the tool's ``.ruby-version`` to the platform root so that
    standalone ``rjui build`` / ``sjui build`` invocations (not routed through
    ``jui build`` with its RBENV_VERSION injection) pick up the correct Ruby
    when rbenv walks up from the user's CWD.

    When ``source_root`` is given, CLI-root ``shared/core/`` payloads (see
    :data:`SHARED_CORE_PAYLOADS`) are distributed into ``<tool>/shared/core/``.

    Returns a counters dict: copied / updated / preserved / pruned / ruby_pin /
    shared_core.
    """
    counters = {"copied": 0, "updated": 0, "preserved": 0, "pruned": 0, "ruby_pin": 0, "shared_core": 0}

    if not source_tool_dir.exists():
        raise FileNotFoundError(f"Source tool directory not found: {source_tool_dir}")

    # Copy / update every source file (outside extensions/).
    source_rels: set[Path] = set()
    for rel, src_file in _iter_source_files(source_tool_dir):
        source_rels.add(rel)
        dst_file = target_tool_dir / rel
        if dst_file.exists():
            if _files_equal(src_file, dst_file):
                continue
            if dry_run:
                print(f"  would update: {rel}")
            else:
                dst_file.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src_file, dst_file)
            counters["updated"] += 1
        else:
            if dry_run:
                print(f"  would copy:   {rel}")
            else:
                dst_file.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src_file, dst_file)
            counters["copied"] += 1

    # Count preserved extensions files under target (informational).
    if target_tool_dir.exists():
        for dirpath, _dirnames, filenames in os.walk(target_tool_dir):
            dp = Path(dirpath)
            try:
                rel_dir = dp.relative_to(target_tool_dir)
            except ValueError:
                continue
            if _is_extensions_path(rel_dir) or rel_dir.name == "extensions":
                counters["preserved"] += len(filenames)

    # Propagate Ruby version pin to the platform root. rbenv walks up from
    # the user's CWD; standalone `rjui build` from <platform_root>/ otherwise
    # falls through to the system Ruby, which lacks `filter_map` etc.
    source_ruby_version_file = source_tool_dir / ".ruby-version"
    if source_ruby_version_file.exists():
        want = source_ruby_version_file.read_text().strip()
        target_ruby_version_file = platform_root / ".ruby-version"
        have: str | None = None
        if target_ruby_version_file.exists():
            have = target_ruby_version_file.read_text().strip()
        if have != want:
            if dry_run:
                if have is None:
                    print(f"  would write:  ../.ruby-version  ({want})")
                else:
                    print(f"  would update: ../.ruby-version  ({have} → {want})")
            else:
                target_ruby_version_file.write_text(f"{want}\n")
            counters["ruby_pin"] += 1

    # Distribute CLI-root shared/core payloads into <tool>/shared/core/ so the
    # tool font helpers resolve their first candidate path in project-local
    # installs. These paths are registered in source_rels below so --prune does
    # not delete them (they are legitimately absent from the tool-dir mirror).
    if source_root is not None:
        counters["shared_core"] += _distribute_shared_core(
            source_root, target_tool_dir, dry_run=dry_run
        )
        for rel in SHARED_CORE_PAYLOADS:
            source_rels.add(Path("shared") / "core" / rel)

    # Prune target files not present in source (but never inside extensions/).
    if prune and target_tool_dir.exists():
        for dirpath, _dirnames, filenames in os.walk(target_tool_dir):
            dp = Path(dirpath)
            try:
                rel_dir = dp.relative_to(target_tool_dir)
            except ValueError:
                continue
            # Leave extensions/ alone entirely.
            if "extensions" in rel_dir.parts:
                continue
            for fn in filenames:
                rel = rel_dir / fn
                if rel in source_rels:
                    continue
                if _should_skip(fn, False):
                    continue
                if dry_run:
                    print(f"  would prune:  {rel}")
                else:
                    (dp / fn).unlink()
                counters["pruned"] += 1

    return counters


def _files_equal(a: Path, b: Path) -> bool:
    """Fast equality check: same size then byte-level compare."""
    try:
        if a.stat().st_size != b.stat().st_size:
            return False
    except OSError:
        return False
    try:
        with a.open("rb") as fa, b.open("rb") as fb:
            while True:
                chunk_a = fa.read(64 * 1024)
                chunk_b = fb.read(64 * 1024)
                if chunk_a != chunk_b:
                    return False
                if not chunk_a:
                    return True
    except OSError:
        return False


def _home_relative(path: Path) -> str:
    """Render *path* with the home directory as ``~``.

    The rendered string lands in a consumer project's sync-meta file; a raw
    absolute path would embed a username + machine layout there.
    """
    try:
        return "~/" + path.relative_to(Path.home()).as_posix()
    except ValueError:
        return str(path)


def _write_sync_meta(
    project_root: Path,
    source_root: Path,
    synced: dict[str, str],
    *,
    dry_run: bool,
) -> tuple[Path, bool]:
    """Stamp toolchain coordinates for the platforms just synced.

    Entries merge per platform: syncing only ``web`` must not erase the
    coordinates ``ios`` was synced at earlier. The file is left untouched
    when the coordinates did not change, so repeated syncs don't churn the
    consumer's git status.

    ``syncedAt`` records when THIS version arrived, not when sync last ran,
    which is what keeps both properties: it is written only alongside a
    coordinate that changed, and a no-op sync leaves the old stamp in place.
    Comparison for "did anything change" deliberately ignores it — stamping
    every run would churn the file on every sync, which is the property the
    previous "no timestamps" rule existed to protect.

    Distribution is automatic and notification is manual, so a consumer can
    be measuring while a new version lands under them. Three lanes hit this
    in one day; two of them ended up unable to say afterwards which version
    a recorded number came from, and one downgraded its own ledger from
    "measured at 1.7.33" to "assumed 1.7.33". Asking each face to bracket
    its measurements with ``--version`` is the same procedure copied N
    times, which is the shape of a missing tool feature.

    Returns ``(meta_path, changed)``.
    """
    meta_path = project_root / SYNC_META_DIRNAME / SYNC_META_FILENAME
    platforms: dict = {}
    if meta_path.exists():
        try:
            existing = json.loads(meta_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            existing = {}
        if isinstance(existing.get("platforms"), dict):
            platforms = existing["platforms"]

    version = toolchain_version(source_root)
    sha = source_sha(source_root)
    for platform_name, tool_name in synced.items():
        entry = {
            "tool": tool_name,
            "version": version,
            "sourceSha": sha,
            "sourceRoot": _home_relative(source_root),
        }
        previous = platforms.get(platform_name)
        if isinstance(previous, dict) and previous.get("syncedAt"):
            # Carried, not refreshed: the stamp answers "when did THIS
            # version arrive", so a re-sync of the same coordinates must
            # not move it. Replaced below only when the coordinates differ.
            same = all(previous.get(k) == entry[k] for k in entry)
            if same:
                entry["syncedAt"] = previous["syncedAt"]
        platforms[platform_name] = entry

    def _render(table: dict) -> str:
        return json.dumps({
            "_generated_by": (
                "jui sync_tool — toolchain coordinates of the last sync; "
                "quote these in bug reports. syncedAt is when this version "
                "arrived, not when sync last ran."
            ),
            "platforms": {name: table[name] for name in sorted(table)},
        }, indent=2, sort_keys=True) + "\n"

    def _without_stamps(table: dict) -> dict:
        return {n: {k: v for k, v in e.items() if k != "syncedAt"}
                for n, e in table.items() if isinstance(e, dict)}

    # Unchanged is decided on the coordinates alone. Including the stamp
    # would make every sync a change, which is what the file is written not
    # to do.
    if meta_path.exists():
        try:
            old = json.loads(meta_path.read_text(encoding="utf-8"))
            old_platforms = old.get("platforms")
            if isinstance(old_platforms, dict) and \
                    _without_stamps(old_platforms) == _without_stamps(platforms):
                return meta_path, False
        except (OSError, json.JSONDecodeError):
            pass

    stamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    for entry in platforms.values():
        if isinstance(entry, dict):
            entry.setdefault("syncedAt", stamp)
    content = _render(platforms)
    if not dry_run:
        meta_path.parent.mkdir(parents=True, exist_ok=True)
        meta_path.write_text(content, encoding="utf-8")
    return meta_path, True


def cmd_sync_tool(args: argparse.Namespace) -> int:
    """Execute ``jui sync_tool``."""
    config_mgr = ConfigManager()
    if not config_mgr.exists():
        print("ERROR: jui.config.json not found. Run 'jui init' first.")
        return 1
    config = config_mgr.load()
    project_root = config_mgr.project_root
    platforms = config.get("platforms", {})

    if not platforms:
        print("No platforms configured in jui.config.json; nothing to sync.")
        return 0

    try:
        source_root = _resolve_source_root(args.source)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}")
        return 1

    print(f"Project:      {project_root}")
    print(f"Source:       {source_root}")
    if args.dry_run:
        print("Mode:         DRY RUN (no files written)")

    # Filter to just the requested platform if asked.
    targets = platforms.items()
    if args.platform:
        if args.platform not in platforms:
            print(f"ERROR: platform '{args.platform}' not in jui.config.json (have: {', '.join(platforms)})")
            return 1
        targets = [(args.platform, platforms[args.platform])]

    totals = {"copied": 0, "updated": 0, "preserved": 0, "pruned": 0, "ruby_pin": 0, "shared_core": 0}
    had_error = False
    synced: dict[str, str] = {}  # platform -> tool actually mirrored

    for platform_name, pconfig in targets:
        tool_name = PLATFORM_TO_TOOL.get(platform_name)
        if not tool_name:
            print(f"  [{platform_name}] skipped — no tool mapping for this platform")
            continue

        src = source_root / tool_name
        platform_root_value = pconfig.get("root")
        if not platform_root_value:
            print(f"  [{platform_name}] skipped — no 'root' in platforms.{platform_name}")
            continue
        platform_root = project_root / platform_root_value
        dst = platform_root / tool_name

        if not src.exists():
            print(f"  [{platform_name}] SKIPPED — source missing: {src}")
            had_error = True
            continue
        if not platform_root.exists():
            print(f"  [{platform_name}] SKIPPED — platform root missing: {platform_root}")
            had_error = True
            continue

        print(f"\n== {platform_name} → {tool_name} ==")
        print(f"  src: {src}")
        print(f"  dst: {dst}")

        try:
            counters = _sync_one_tool(
                src, dst, platform_root,
                prune=args.prune,
                dry_run=args.dry_run,
                source_root=source_root,
            )
        except Exception as exc:
            print(f"  ERROR: {exc}")
            had_error = True
            continue

        for key, val in counters.items():
            totals[key] += val
        synced[platform_name] = tool_name
        print(
            f"  copied: {counters['copied']}  updated: {counters['updated']}"
            f"  preserved-in-extensions: {counters['preserved']}"
            f"  ruby-pin: {counters['ruby_pin']}"
            f"  shared-core: {counters['shared_core']}"
            + (f"  pruned: {counters['pruned']}" if args.prune else "")
        )

    # Toolchain-coordinate stamp — with it, a consumer bug report can say
    # exactly which toolchain (version + source SHA) produced its generated
    # code instead of "whatever HEAD was that day".
    if synced:
        meta_path, changed = _write_sync_meta(
            project_root, source_root, synced, dry_run=args.dry_run
        )
        sha = source_sha(source_root)
        label = (
            f"toolchain {toolchain_version(source_root)}"
            f" @ {sha[:12] if sha else 'unstamped source'}"
        )
        try:
            display = meta_path.relative_to(project_root)
        except ValueError:
            display = meta_path
        if not changed:
            print(f"\n  meta: {display} ({label}) — unchanged")
        elif args.dry_run:
            print(f"\n  would write:  {display} ({label})")
        else:
            print(f"\n  meta: {display} ({label})")

    print("\n== total ==")
    print(
        f"  copied: {totals['copied']}  updated: {totals['updated']}"
        f"  preserved-in-extensions: {totals['preserved']}"
        f"  ruby-pin: {totals['ruby_pin']}"
        f"  shared-core: {totals['shared_core']}"
        + (f"  pruned: {totals['pruned']}" if args.prune else "")
    )
    if args.dry_run:
        print("  (dry-run — nothing changed on disk)")

    return 1 if had_error else 0
