# frozen_string_literal: true

require 'fileutils'
require 'tmpdir'
require 'compose/generators/dynamic_registry_types'
require 'compose/generators/dynamic_component_generator'
require 'compose/generators/converter_generator'
require 'compose/generators/view_adapter_generator'
require_relative '../../support/kotlin_compiler'

# The generated DynamicComponentRegistry lists the types it draws
# (`val types`), and the debug DynamicComponentInitializer hands them to
# KotlinJsonUI as Configuration.customComponentTypes (KotlinJsonUI >= 2.42.0).
# What classifies a node by its type in Dynamic mode reads that list, so an
# app's own ProgressBar is `progressBar_<path>` there as in release.
#
# A registry and an initializer written before 1.9.0 have neither. `g
# converter` and `g view` add them when they run, by adding lines only,
# and say so.
RSpec.describe 'kjui g converter: the registry lists its types for Configuration.customComponentTypes' do
  types = KjuiTools::Compose::Generators::DynamicRegistryTypes

  # The shape a registry had before 1.9.0 (the one `g converter` wrote): its
  # cases, no list.
  old_registry = <<~KOTLIN
    package com.example.app.dynamic

    import androidx.compose.runtime.Composable
    import com.google.gson.JsonObject
    import com.example.app.dynamic.components.extensions.FadeHeroViewComponent
    import com.example.app.dynamic.components.extensions.ProgressBarComponent

    /**
     * Registry for dynamic custom components
     * Auto-generated by kjui converter generator
     */
    object DynamicComponentRegistry {
        @Composable
        fun createCustomComponent(
            type: String,
            json: JsonObject,
            data: Map<String, Any>
        ): Boolean {
            return when (type) {
                "FadeHeroView" -> {
                    FadeHeroViewComponent.create(json, data)
                    true
                }
                "ProgressBar" -> {
                    ProgressBarComponent.create(json, data)
                    true
                }
                else -> false
            }
        }
    }
  KOTLIN

  old_initializer = <<~KOTLIN
    package com.example.app

    import androidx.compose.runtime.Composable
    import com.google.gson.JsonObject
    import com.kotlinjsonui.core.Configuration
    import com.example.app.dynamic.DynamicComponentRegistry

    object DynamicComponentInitializer {
        fun initialize() {
            Configuration.customComponentHandler = { type, json, data ->
                DynamicComponentRegistry.createCustomComponent(type, json, data)
            }
        }
    }
  KOTLIN

  listed = ->(content) { content[/#{Regexp.escape(types::TYPES_OPEN)}(.*?)\n\s*\)/m, 1].to_s.scan(/"([^"]+)"/).flatten }

  describe 'the list' do
    it 'is made of the cases a registry without one draws, and added once' do
      expect(types.cases(old_registry)).to eq(%w[FadeHeroView ProgressBar]) # (control)
      content, changed = types.list(old_registry, ['ProgressBar'])
      expect(changed).to be(true)
      expect(listed.call(content)).to eq(%w[FadeHeroView ProgressBar])
      again, changed_again = types.list(content, ['ProgressBar'])
      expect([again, changed_again]).to eq([content, false])
    end

    it 'gains only the types it does not name' do
      content, = types.list(old_registry, [])
      more, changed = types.list(content, %w[FadeHeroView ChatBubble])
      expect(changed).to be(true)
      expect(listed.call(more)).to eq(%w[FadeHeroView ProgressBar ChatBubble])
    end

    it 'is not written into a file with no registry object' do
      expect(types.list("package x\n", ['A'])).to be_nil
    end
  end

  describe 'the initializer' do
    it 'hands the types to KotlinJsonUI first in initialize(), once' do
      content, changed = types.initializer(old_initializer)
      expect(changed).to be(true)
      body = content[/fun initialize\(\) \{\n(.*?)\n        \}/m, 1]
      expect(body.lines.first(2).map(&:strip)).to eq(
        ['// Requires KotlinJsonUI >= 2.42.0 (Configuration.customComponentTypes)', types::ASSIGNMENT]
      )
      expect(types.initializer(content)).to eq([content, false])
    end

    it 'adds the Configuration import where the file has none' do
      bare = old_initializer.sub("import com.kotlinjsonui.core.Configuration\n", '')
      content, = types.initializer(bare)
      expect(content.scan(types::CONFIGURATION_IMPORT).size).to eq(1)
    end
  end

  describe 'jui g converter on a project written before 1.9.0' do
    around do |example|
      Dir.mktmpdir('kjui_registry_types') do |dir|
        @dir = dir
        @registry = File.join(dir, 'src/debug/kotlin/com/example/app/dynamic/DynamicComponentRegistry.kt')
        @initializer = File.join(dir, 'src/debug/kotlin/com/example/app/DynamicComponentInitializer.kt')
        FileUtils.mkdir_p(File.dirname(@registry))
        File.write(@registry, old_registry)
        File.write(@initializer, old_initializer)
        example.run
      end
    end

    before do
      allow(KjuiTools::Core::ConfigManager).to receive(:load_config).and_return(
        '_config_dir' => @dir, 'source_directory' => 'src/main', 'package_name' => 'com.example.app'
      )
      @said = []
      %i[info warn success error debug].each do |level|
        allow(KjuiTools::Core::Logger).to receive(level) { |message| @said << message }
      end
    end

    it 'lists an already registered component, says so, and says nothing changed the second time' do
      generator = KjuiTools::Compose::Generators::DynamicComponentGenerator.new('ProgressBar')
      generator.send(:update_dynamic_registry)
      expect(listed.call(File.read(@registry))).to eq(%w[FadeHeroView ProgressBar])
      expect(@said.last).to include("lists 'ProgressBar' in its types")
      generator.send(:update_dynamic_registry)
      expect(@said.last).to include("Unchanged #{@registry}: it already registers 'ProgressBar'")
    end

    it 'lists a newly registered component with the rest' do
      KjuiTools::Compose::Generators::DynamicComponentGenerator.new('ChatBubble').send(:update_dynamic_registry)
      expect(listed.call(File.read(@registry))).to eq(%w[FadeHeroView ProgressBar ChatBubble])
    end

    it 'gives the existing debug initializer the line, once' do
      generator = KjuiTools::Compose::Generators::ConverterGenerator.new('ProgressBar')
      generator.send(:create_dynamic_initializers)
      expect(File.read(@initializer)).to include(types::ASSIGNMENT)
      expect(@said.join("\n")).to include('sets Configuration.customComponentTypes')
      once = File.read(@initializer)
      generator.send(:create_dynamic_initializers)
      expect(File.read(@initializer)).to eq(once)
    end

    it 'lists a view adapter g view registers with the rest, and gives the initializer the line' do
      generator = KjuiTools::Compose::Generators::ViewAdapterGenerator.new('Home')
      allow(KjuiTools::Core::ProjectFinder).to receive(:get_package_name).and_return('com.example.app')
      generator.generate
      expect(listed.call(File.read(@registry))).to eq(%w[FadeHeroView ProgressBar home])
      expect(File.read(@initializer)).to include(types::ASSIGNMENT)
      generator.generate
      expect(listed.call(File.read(@registry))).to eq(%w[FadeHeroView ProgressBar home])
      expect(File.read(@initializer).scan(types::ASSIGNMENT).size).to eq(1)
    end

    # What the two files hold after the run compiles: the list inside the
    # object, the initializer's line reading it. The files' packages and
    # imports are taken off, and what they import is declared here, as the
    # libraries declare it.
    it 'writes a registry and an initializer that compile together' do
      KjuiTools::Compose::Generators::DynamicComponentGenerator.new('ProgressBar').send(:update_dynamic_registry)
      KjuiTools::Compose::Generators::DynamicComponentGenerator.new('ChatBubble').send(:update_dynamic_registry)
      KjuiTools::Compose::Generators::ConverterGenerator.new('ProgressBar').send(:create_dynamic_initializers)
      body = ->(file) { File.read(file).lines.reject { |l| l.start_with?('package ', 'import ') }.join }
      expect(<<~KOTLIN).to compile_as_kotlin
        @Target(AnnotationTarget.FUNCTION, AnnotationTarget.TYPE)
        annotation class Composable
        class JsonObject
        object Configuration {
            var customComponentTypes: Set<String> = emptySet()
            var customComponentHandler: (@Composable (String, JsonObject, Map<String, Any>) -> Boolean)? = null
        }
        object FadeHeroViewComponent { @Composable fun create(json: JsonObject, data: Map<String, Any>) {} }
        object ProgressBarComponent { @Composable fun create(json: JsonObject, data: Map<String, Any>) {} }
        object DynamicChatBubbleComponent { @Composable fun create(json: JsonObject, data: Map<String, Any>) {} }
        #{body.call(@registry)}
        #{body.call(@initializer)}
      KOTLIN
    end
  end
end
