// Generated by ReactJsonUI — do not edit. Re-run `rjui build` (or `jui sync_tool`) to refresh.
//
// Web counterpart of SwiftJsonUIConfiguration / KotlinJsonUI Configuration.Font.
// Lets the host app supply a single `fontProvider` callback that resolves a
// JsonUI `FontSpec` into a React.CSSProperties chunk; generated components
// merge the result into their inline `style={{ ... }}` so the provider's
// values always win over Tailwind class defaults (CSS specificity: inline
// style > class).
//
// The shape mirrors §3.2 of docs/plans/2026-04-28-font-provider-unification.md
// — keep it in sync with iOS `FontSpec` / Android `FontSpec` / `ResolvedFont`.

import type React from 'react';

/**
 * Cross-platform font specification handed to `Configuration.Font.fontProvider`.
 * One spec per text site is built by the rjui generator from the JSON layout's
 * `fontFamily`, `font` (weight name), `fontSize`, and (future) `italic`
 * attributes.
 */
export interface FontSpec {
  /** Maps to JSON `fontFamily`. */
  family?: string;
  /**
   * Maps to JSON `font`. Either a JsonUI weight name (`bold`, `semibold`,
   * `medium`, ...) or a numeric / CSS weight (`400`, `'600'`, ...). The
   * generator emits the name verbatim — provider implementations should
   * accept both.
   */
  weight?:
    | number
    | 'normal'
    | 'bold'
    | 'medium'
    | 'semibold'
    | 'light'
    | 'thin'
    | 'heavy'
    | string;
  /** Maps to JSON `fontSize` (px). */
  size?: number;
  /** Reserved — JsonUI has no `italic` attribute yet, generator always emits false. */
  italic?: boolean;
}

type FontProvider = (spec: FontSpec) => React.CSSProperties;

const FontConfig = {
  /**
   * Optional host-app callback. When set, every generated text site routes
   * its `FontSpec` through this function and spreads the returned
   * CSSProperties into the component's inline style. When unset, the
   * built-in `defaultCss` fallback (below) is used.
   */
  fontProvider: undefined as FontProvider | undefined,

  /**
   * Generator entry point. Generated components call
   * `Configuration.Font.resolve(spec)` and spread the result into their
   * inline style attribute. Do not call directly from app code unless you
   * are mirroring the generator's behavior in a custom converter.
   */
  resolve(spec: FontSpec): React.CSSProperties {
    if (this.fontProvider) return this.fontProvider(spec);
    return defaultCss(spec);
  },
};

function defaultCss(spec: FontSpec): React.CSSProperties {
  const css: React.CSSProperties = {};
  if (spec.family) css.fontFamily = spec.family;
  if (spec.weight !== undefined) {
    css.fontWeight = spec.weight as React.CSSProperties['fontWeight'];
  }
  if (spec.size !== undefined) css.fontSize = `${spec.size}px`;
  if (spec.italic) css.fontStyle = 'italic';
  return css;
}

export const Configuration = {
  Font: FontConfig,
};
