// NetworkImage.tsx
// Built-in component for async image loading from network URLs
// Generated by ReactJsonUI

/* eslint-disable @next/next/no-img-element -- framework-agnostic by design:
   NetworkImage must work outside Next.js, so it renders a plain <img>
   (no next/image dependency). */
/* eslint-disable react-hooks/set-state-in-effect -- the synchronous setState
   pair at the top of the effect RESETS loading/error when `src` changes
   before the preload starts; it is intentional reset semantics, not
   derived state. */

"use client";

import React, { useState, useEffect } from 'react';

interface NetworkImageProps {
  id?: string;
  src?: string;
  alt?: string;
  className?: string;
  // 'fit' is the canonical JsonUI alias for 'contain' — the converter
  // normalizes it, but accept it here too so the contract can't drift.
  contentMode?: 'cover' | 'contain' | 'fill' | 'none' | 'scaleDown' | 'fit';
  placeholder?: string;
  errorImage?: string;
  onLoad?: () => void;
  onError?: () => void;
}

export const NetworkImage: React.FC<NetworkImageProps> = ({
  id,
  src,
  alt = '',
  className = '',
  contentMode = 'cover',
  placeholder,
  errorImage,
  onLoad,
  onError,
}) => {
  const [imageUrl, setImageUrl] = useState<string | null>(placeholder || null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    if (!src) {
      setLoading(false);
      return;
    }

    setLoading(true);
    setError(false);

    const img = new Image();
    img.onload = () => {
      setImageUrl(src);
      setLoading(false);
      onLoad?.();
    };
    img.onerror = () => {
      setError(true);
      setLoading(false);
      if (errorImage) {
        setImageUrl(errorImage);
      }
      onError?.();
    };
    img.src = src;

    return () => {
      img.onload = null;
      img.onerror = null;
    };
  }, [src, errorImage, onLoad, onError]);

  const objectFitMap: Record<string, string> = {
    cover: 'object-cover',
    contain: 'object-contain',
    fill: 'object-fill',
    none: 'object-none',
    scaleDown: 'object-scale-down',
    fit: 'object-contain',
  };

  const objectFitClass = objectFitMap[contentMode] || 'object-cover';

  if (loading && placeholder) {
    return (
      <img
        id={id}
        src={placeholder}
        alt={alt}
        className={`${className} ${objectFitClass}`}
      />
    );
  }

  if (loading) {
    return (
      <div id={id} className={`${className} animate-pulse bg-gray-200`} />
    );
  }

  if (error && !errorImage) {
    return (
      <div id={id} className={`${className} bg-gray-100 flex items-center justify-center`}>
        <svg className="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
      </div>
    );
  }

  return (
    <img
      id={id}
      src={imageUrl || ''}
      alt={alt}
      className={`${className} ${objectFitClass}`}
    />
  );
};

export default NetworkImage;
