"use client";

import { useCallback, useSyncExternalStore } from 'react';

/**
 * Custom hook for CSS media query matching.
 * Used by JsonUI responsive layouts for orientation-based breakpoints.
 *
 * @param query - CSS media query string (e.g., '(orientation: landscape)')
 * @returns boolean indicating whether the media query matches
 *
 * Generated by ReactJsonUI
 */
export function useMediaQuery(query: string): boolean {
  // useSyncExternalStore instead of useState+useEffect: no synchronous
  // setState inside an effect (react-hooks/set-state-in-effect), and the
  // first client render already reflects the real match state instead of
  // flashing `false` until the effect runs. Server snapshot stays `false`
  // (no window during SSR).
  const subscribe = useCallback(
    (onStoreChange: () => void) => {
      const mediaQuery = window.matchMedia(query);
      mediaQuery.addEventListener('change', onStoreChange);
      return () => mediaQuery.removeEventListener('change', onStoreChange);
    },
    [query]
  );

  return useSyncExternalStore(
    subscribe,
    () => window.matchMedia(query).matches,
    () => false
  );
}

export default useMediaQuery;
