"use client";

import { useState, useEffect } from 'react';
import { ColorManager, ColorMode } from '@/generated/ColorManager';

/**
 * React hook that subscribes to ColorManager's current mode. Returns the
 * current mode string and re-renders the calling component whenever
 * `ColorManager.setMode(...)` is called OR when the OS switches
 * prefers-color-scheme (when `ColorManager.followSystemMode` is true).
 *
 * Usage:
 *   const mode = useColorMode();
 *   return <div style={{ background: ColorManager.accent }}>hello</div>;
 *
 * The `mode` return value is mostly for conditional logic in the JSX
 * (`mode === 'dark' ? X : Y`). For plain color values, reference
 * `ColorManager.<key>` directly — the subscription returned by this
 * hook forces a re-render, which re-evaluates the dynamic accessor.
 *
 * Generated by rjui build — do not edit by hand.
 */
export function useColorMode(): ColorMode {
  const [mode, setMode] = useState<ColorMode>(ColorManager.currentMode);

  useEffect(() => {
    const unsubscribe = ColorManager.subscribe(() => {
      setMode(ColorManager.currentMode);
    });
    // Re-sync once on mount in case mode changed between initial render and
    // subscription (e.g. during hydration).
    setMode(ColorManager.currentMode);
    return unsubscribe;
  }, []);

  return mode;
}

export default useColorMode;
