# frozen_string_literal: true

require 'fileutils'
require 'json'
require_relative '../../core/logger'
require_relative '../../core/generated_marker'
require_relative '../../core/converter_generator_core'
require_relative 'kotlin_component_generator'
require_relative 'dynamic_component_generator'

module KjuiTools
  module Compose
    module Generators
      # Android profile over the shared converter-scaffolder body
      # (lib/core/converter_generator_core.rb — byte-identical mirror of
      # shared/core/converter_generator_core.rb, pinned by
      # spec/core/shared_core_mirror_spec.rb). The overwrite flow, registry
      # patching, attribute-definition JSON and type mapping live in the
      # shared core; this class owns the Compose scaffold template, the
      # Kotlin/Dynamic sub-generators and the DynamicComponentInitializer
      # pair.
      class ConverterGenerator < ::JsonUIShared::ConverterGeneratorCore
        def initialize(name, options = {})
          @name = name
          # Keep original PascalCase name for component
          @component_pascal_case = name  # e.g., MyTestCard
          @component_snake_case = to_snake_case(name)  # e.g., my_test_card
          @class_name = name + "Component"  # e.g., MyTestCardComponent
          @options = options
          @logger = Core::Logger
        end

        def generate
          @logger.info "Generating custom converter: #{@class_name}"

          # Create converter file for static generation
          create_converter_file

          # Update component mappings file
          update_mappings_file

          # Create Kotlin component file using separate generator
          kotlin_generator = KotlinComponentGenerator.new(@name, @options)
          kotlin_generator.generate

          # Generate dynamic component file
          dynamic_generator = DynamicComponentGenerator.new(@name, @options)
          dynamic_generator.generate

          # Create or update DynamicComponentInitializer files
          create_dynamic_initializers

          # Generate attribute definition file
          generate_attribute_definition_file

          @logger.success "Successfully generated converter: #{@class_name}"
          @logger.info "Converter file created at: kjui_tools/lib/compose/components/extensions/#{@component_snake_case}_component.rb"
          @logger.info "Mappings file updated with '#{@component_pascal_case}' => '#{@class_name}'"
        end

        private

        def extensions_dir
          # Resolve relative to this generator file: the scaffold lands in
          # the tool copy the project runs (lib/compose/components/extensions)
          generator_dir = File.dirname(__FILE__)
          File.expand_path(File.join(generator_dir, '..', 'components', 'extensions'))
        end

        def converter_file_name
          "#{@component_snake_case}_component.rb"
        end

        def registry_spec
          {
            file: File.join(extensions_dir, 'component_mappings.rb'),
            const: 'COMPONENT_MAPPINGS',
            # kjui maps to class constants, so the class must be required
            mapping_line: "        '#{@component_pascal_case}' => #{@class_name},",
            require_line: "require_relative '#{@component_snake_case}_component'",
            initial_content: <<~RUBY
              # frozen_string_literal: true

              # This file maps custom component types to their converter classes
              # Auto-generated by kjui g converter command

              require_relative '#{@component_snake_case}_component'

              module KjuiTools
                module Compose
                  module Components
                    module Extensions
                      COMPONENT_MAPPINGS = {
                        '#{@component_pascal_case}' => #{@class_name},
                      }.freeze
                    end
                  end
                end
              end
            RUBY
          }
        end

        def attr_defs_dir
          File.join(extensions_dir, 'attribute_definitions')
        end

        def command_string
          @command ||= build_command_string('kjui g converter')
        end

        def json_marker(source:, generator:)
          Core::GeneratedMarker.json_marker(source: source, generator: generator)
        end

        def converter_template
          <<~RUBY
            # frozen_string_literal: true

            require_relative '../../helpers/modifier_builder'

            module KjuiTools
              module Compose
                module Components
                  module Extensions
                    class #{@class_name}
                      def self.generate(json_data, depth, required_imports = nil, parent_type = nil)
                        required_imports&.add(:box)

                        # Check if this is a container component
                        children = json_data['children'] || json_data['child']
                        is_container = children && children.is_a?(Array) && !children.empty?

                        # Collect parameters
                        params = []

                        # Helper method to format values
                        format_value = lambda do |value, type|
                          case type.downcase
                          when 'string', 'text'
                            # Use ResourceResolver to process strings (checks for resources)
                            Helpers::ResourceResolver.process_text(value, required_imports)
                          when 'int', 'integer', 'float', 'double', 'bool', 'boolean'
                            value.to_s
                          when 'color'
                            # Use ResourceResolver to process colors
                            Helpers::ResourceResolver.process_color(value, required_imports)
                          else
                            value.to_s
                          end
                        end
            #{generate_parameter_collection}

                        # Build modifiers
                        modifiers = []
                        modifiers.concat(Helpers::ModifierBuilder.build_size(json_data, nil, required_imports))
                        modifiers.concat(Helpers::ModifierBuilder.build_offset(json_data, required_imports))
                        modifiers.concat(Helpers::ModifierBuilder.build_padding(json_data))
                        modifiers.concat(Helpers::ModifierBuilder.build_margins(json_data))
                        modifiers.concat(Helpers::ModifierBuilder.build_background(json_data, required_imports))

                        if is_container
                          # Container component with children
                          code = indent("#{@component_pascal_case}(", depth)

                          if !params.empty?
                            params.each_with_index do |param, index|
                              separator = index == params.length - 1 ? '' : ','
                              code += "\\n" + indent("\#{param}\#{separator}", depth + 1)
                            end
                          end

                          if !modifiers.empty?
                            modifier_str = Helpers::ModifierBuilder.format(modifiers, depth)
                            code += (params.empty? ? modifier_str : "," + modifier_str)
                          end

                          code += "\\n" + indent(") {", depth)

                          # Process children - return with metadata for ComposeBuilder to handle
                          return {
                            code: code,
                            children: children,
                            closing: "\\n" + indent("}", depth)
                          }
                        else
                          # Non-container component
                          if params.empty? && modifiers.empty?
                            code = indent("#{@component_pascal_case}()", depth)
                          else
                            code = indent("#{@component_pascal_case}(", depth)

                            if !params.empty?
                              params.each_with_index do |param, index|
                                separator = index == params.length - 1 ? '' : ','
                                code += "\\n" + indent("\#{param}\#{separator}", depth + 1)
                              end
                            end

                            if !modifiers.empty?
                              modifier_str = Helpers::ModifierBuilder.format(modifiers, depth)
                              code += (params.empty? ? modifier_str : "," + modifier_str)
                            end

                            code += "\\n" + indent(")", depth)
                          end
                        end

                        code
                      end

                      private

                      def self.indent(text, level)
                        return text if level == 0
                        spaces = '    ' * level
                        text.split("\\n").map { |line|
                          line.empty? ? line : spaces + line
                        }.join("\\n")
                      end
                    end
                  end
                end
              end
            end
          RUBY
        end

        def generate_parameter_collection
          return "" if !@options[:attributes] || @options[:attributes].empty?

          lines = []
          @options[:attributes].each do |key, type|
            # Check if this is a binding property (starts with @)
            is_binding = key.start_with?('@')
            actual_key = is_binding ? key[1..-1] : key

            lines << "            if json_data['#{actual_key}']"
            lines << "              value = json_data['#{actual_key}']"
            lines << "              if value.is_a?(String) && value.match?(/@\\{([^}]+)\\}/)"
            lines << "                # Handle binding"
            lines << "                prop_name = value[2..-2]"
            lines << "                params << \"#{actual_key} = data.\#{prop_name}\""
            lines << "              else"
            lines << "                # Handle static value"
            lines << "                formatted_value = format_value.call(value, '#{type}')"
            lines << "                params << \"#{actual_key} = \#{formatted_value}\" if formatted_value"
            lines << "              end"
            lines << "            end"
          end
          lines.join("\n")
        end

        def create_dynamic_initializers
          config = Core::ConfigManager.load_config
          base_path = config['_config_dir'] || Dir.pwd
          source_directory = config['source_directory'] || 'src/main'
          package_name = config['package_name'] || Core::ProjectFinder.get_package_name || 'com.example.kotlinjsonui.sample'

          # Create debug version
          debug_dir = File.join(
            base_path,
            source_directory.gsub('main', 'debug'),
            'kotlin',
            package_name.gsub('.', '/')
          )
          FileUtils.mkdir_p(debug_dir)

          debug_file = File.join(debug_dir, 'DynamicComponentInitializer.kt')

          # Only create if it doesn't exist yet
          if !File.exist?(debug_file)
            File.write(debug_file, generate_debug_initializer_content(package_name))
            @logger.info "Created DynamicComponentInitializer (debug)"
          end

          # Create release version
          release_dir = File.join(
            base_path,
            source_directory.gsub('main', 'release'),
            'kotlin',
            package_name.gsub('.', '/')
          )
          FileUtils.mkdir_p(release_dir)

          release_file = File.join(release_dir, 'DynamicComponentInitializer.kt')

          # Only create if it doesn't exist yet
          if !File.exist?(release_file)
            File.write(release_file, generate_release_initializer_content(package_name))
            @logger.info "Created DynamicComponentInitializer (release)"
          end
        end

        def generate_debug_initializer_content(package_name)
          <<~KOTLIN
          package #{package_name}

          import androidx.compose.runtime.Composable
          import com.google.gson.JsonObject
          import com.kotlinjsonui.core.Configuration
          import #{package_name}.dynamic.DynamicComponentRegistry

          /**
           * Debug-only initializer for custom components in dynamic mode
           * Auto-generated by kjui converter generator
           */
          object DynamicComponentInitializer {

              /**
               * Register custom component handler for dynamic mode
               * This is only available in debug builds where DynamicComponentRegistry exists
               */
              fun initialize() {
                  Configuration.customComponentHandler = { type, json, data ->
                      DynamicComponentRegistry.createCustomComponent(type, json, data)
                  }
              }
          }
          KOTLIN
        end

        def generate_release_initializer_content(package_name)
          <<~KOTLIN
          package #{package_name}

          /**
           * Release version of DynamicComponentInitializer (no-op)
           * Auto-generated by kjui converter generator
           */
          object DynamicComponentInitializer {

              /**
               * No-op in release builds
               */
              fun initialize() {
                  // Dynamic component registry is not available in release builds
              }
          }
          KOTLIN
        end
      end
    end
  end
end
