# frozen_string_literal: true

require 'core/generated_orphans'
require 'fileutils'
require 'tmpdir'

# The rule every face uses to clear what a deleted layout left behind
# (shared/core/generated_orphans.rb; this tool's copy is pinned to it by
# shared_core_mirror_spec). Each face's wiring has its own arms beside its
# build command; these hold the rule itself.
#
# Deleted only when all three hold: the file is in the directory declared for
# that output under that output's name, carries @generated in its first lines,
# and no layout has its name. Everything else that is orphaned is named.
RSpec.describe JsonUIShared::GeneratedOrphans do
  around do |example|
    Dir.mktmpdir('orphans') { |dir| @root = dir; example.run }
  end

  let(:layouts) { File.join(@root, 'Layouts') }
  let(:data) { File.join(@root, 'Data') }
  let(:views) { File.join(@root, 'View') }
  let(:viewmodels) { File.join(@root, 'ViewModel') }

  let(:kinds) do
    [
      described_class::Kind.new(dir: data, owner: :generator, pattern: /\A(?<name>\w+)Data\.swift\z/),
      described_class::Kind.new(dir: views, owner: :block, pattern: /\A(?<name>\w+)GeneratedView\.swift\z/),
      described_class::Kind.new(dir: views, owner: :user, pattern: /\A(?<name>\w+?)View\.swift\z/),
      described_class::Kind.new(dir: viewmodels, owner: :user, pattern: /\A(?<name>\w+)ViewModel\.swift\z/)
    ]
  end

  def generated_head
    "// ╔══\n// ║  @generated AUTO-GENERATED FILE — DO NOT EDIT\n// ║  Source:    x\n"
  end

  def write(path, content = '')
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, content)
    path
  end

  def layout(rel)
    write(File.join(layouts, rel), '{"type": "View"}')
  end

  def sweep
    described_class.sweep(layouts_dir: layouts, kinds: kinds)
  end

  before { layout('home.json') }

  it 'deletes a @generated output whose layout is gone, and names it' do
    gone = write(File.join(data, 'GoneData.swift'), generated_head)
    result = sweep
    expect(File.exist?(gone)).to be(false)
    expect(result.removed).to eq([gone])
    lines = described_class.report_lines(result, base: @root).map(&:last)
    expect(lines).to eq(['Pruned 1 generated file(s) whose layout is gone:', '  - Data/GoneData.swift'])
  end

  describe 'what it keeps' do
    it 'keeps a file of the same name with no @generated line, and names it' do
      unmarked = write(File.join(data, 'GoneData.swift'), "// Generated by an older tool - DO NOT EDIT\n")
      result = sweep
      expect(File.exist?(unmarked)).to be(true)
      expect(result.removed).to be_empty
      expect(result.kept).to eq([[unmarked, described_class::WARNINGS[:unmarked]]])
    end

    it 'does not count a @generated line past the first lines as the claim' do
      late = write(File.join(data, 'GoneData.swift'), "#{"// line\n" * described_class::HEAD_LINES}// @generated\n")
      sweep
      expect(File.exist?(late)).to be(true)
    end

    it 'leaves a @generated file outside the declared directory alone, unreported' do
      elsewhere = write(File.join(@root, 'Other', 'GoneData.swift'), generated_head)
      result = sweep
      expect(File.exist?(elsewhere)).to be(true)
      expect(result.removed + result.kept.map(&:first)).not_to include(elsewhere)
    end

    it 'keeps an output whose layout exists, however the name is spelled' do
      layout('tablet_my-page.json')
      layout('screens/deep_one.json')
      live = [write(File.join(data, 'HomeData.swift'), generated_head),
              write(File.join(data, 'TabletMyPageData.swift'), generated_head),
              write(File.join(data, 'TabletmypageData.swift'), generated_head),
              write(File.join(data, 'DeepOneData.swift'), generated_head)]
      result = sweep
      expect(live.select { |f| File.exist?(f) }).to eq(live)
      expect(result.removed).to be_empty
      expect(result.kept).to be_empty
    end

    it 'keeps a responsive variant view while its variant layout exists' do
      layout('home@regular.json')
      kinds[1] = described_class::Kind.new(dir: views, owner: :generator, pattern: /\A(?<name>\w+)GeneratedView\.swift\z/)
      variant = write(File.join(views, 'Home', 'HomeRegularVariantGeneratedView.swift'), generated_head)
      sweep
      expect(File.exist?(variant)).to be(true)
      File.delete(File.join(layouts, 'home@regular.json'))
      expect(sweep.removed).to eq([variant])
    end

    it 'does not take Resources/ or Styles/ under the layouts directory for layouts' do
      layout('Resources/strings.json')
      layout('Styles/card_style.json')
      gone = [write(File.join(data, 'StringsData.swift'), generated_head),
              write(File.join(data, 'CardStyleData.swift'), generated_head)]
      expect(sweep.removed.sort).to eq(gone.sort)
    end

    # An empty set of names cannot tell "every layout was deleted" from "this
    # is not the layouts directory"; acting on it would empty every output.
    it 'deletes nothing when it finds no layout at all' do
      FileUtils.rm_rf(layouts)
      orphan = write(File.join(data, 'GoneData.swift'), generated_head)
      result = sweep
      expect(File.exist?(orphan)).to be(true)
      expect(result.skipped).to include('no layouts under')
      expect(described_class.report_lines(result).first.first).to eq(:warn)
    end
  end

  describe 'what it names without deleting' do
    it 'names an output the generator owns only in part' do
      block = write(File.join(views, 'gone', 'GoneGeneratedView.swift'), generated_head)
      result = sweep
      expect(File.exist?(block)).to be(true)
      expect(result.kept).to include([block, described_class::WARNINGS[:block]])
    end

    it "names the user's View and ViewModel of a name whose generated output was orphaned" do
      write(File.join(data, 'GoneData.swift'), generated_head)
      view = write(File.join(views, 'Gone', 'GoneView.swift'))
      viewmodel = write(File.join(viewmodels, 'GoneViewModel.swift'))
      result = sweep
      expect(result.kept).to contain_exactly([view, described_class::WARNINGS[:user]],
                                             [viewmodel, described_class::WARNINGS[:user]])
      expect(File.exist?(view) && File.exist?(viewmodel)).to be(true)
    end

    it 'says nothing about a hand-written view that never had a layout' do
      toast = write(File.join(views, 'Common', 'ToastView.swift'))
      result = sweep
      expect(File.exist?(toast)).to be(true)
      expect(result.kept).to be_empty
    end

    it 'counts an unmarked or part-owned output as the evidence too' do
      write(File.join(views, 'gone', 'GoneGeneratedView.swift'), generated_head)
      view = write(File.join(views, 'gone', 'GoneView.swift'))
      expect(sweep.kept.map(&:first)).to include(view)
    end
  end

  describe 'directories' do
    it 'removes a directory a deletion emptied, but never the declared one' do
      kinds[1] = described_class::Kind.new(dir: views, owner: :generator, pattern: /\A(?<name>\w+)GeneratedView\.swift\z/)
      write(File.join(views, 'Gone', 'GoneGeneratedView.swift'), generated_head)
      write(File.join(data, 'GoneData.swift'), generated_head)
      sweep
      expect(Dir.exist?(File.join(views, 'Gone'))).to be(false)
      expect(Dir.exist?(views)).to be(true)
      expect(Dir.exist?(data)).to be(true)
    end

    it 'keeps a directory that still holds the hand-written view' do
      kinds[1] = described_class::Kind.new(dir: views, owner: :generator, pattern: /\A(?<name>\w+)GeneratedView\.swift\z/)
      write(File.join(views, 'Gone', 'GoneGeneratedView.swift'), generated_head)
      view = write(File.join(views, 'Gone', 'GoneView.swift'))
      sweep
      expect(File.exist?(view)).to be(true)
    end
  end
end
