# frozen_string_literal: true

require 'swiftui/views/collection_converter'

# A sectioned grid's rows (4f ruling 2026-09-27, round 10): a section's header
# and footer are full-width rows with the view at their start, and the rows —
# header, grid, footer, the next section — are spaced as the grid's rows
# (collectionSpacing: lineSpacing, else itemSpacing, else 0), as the list
# routes and the other two tools draw them. Until jsonui-cli 1.9.0 they were
# the ScrollView's implicit stack: centred, the system's spacing between them
# (measured on the ConformanceHost codegen host, iOS 26.5: a 60-wide header at
# x 70 of a 200-wide grid, rows 8 apart with lineSpacing 4).
#
# The drawn arm is ScrollRuleProbeUITests in SwiftJsonUI's ConformanceHost
# (the codegen half generated by this converter, the Dynamic half beside it).
RSpec.describe SjuiTools::SwiftUI::Views::CollectionConverter do
  before(:all) { described_class.superclass.validation_enabled = false }
  after(:all) { described_class.superclass.validation_enabled = true }

  def grid(extra)
    described_class.new({ 'type' => 'Collection', 'id' => 'grid', 'items' => '@{rows}', 'columns' => 2 }.merge(extra)).convert.to_s
  end

  EDGED_GRID_SECTIONS = [{ 'cell' => 'ACell', 'header' => 'HCell', 'footer' => 'FCell' }, { 'cell' => 'BCell', 'header' => 'HCell' }].freeze

  it 'sections: a leading column spaced as the rows — lineSpacing, else itemSpacing, else 0' do
    [[{ 'lineSpacing' => 4, 'itemSpacing' => 9 }, 4], [{ 'itemSpacing' => 9 }, 9], [{}, 0]].each do |spacing, gap|
      code = grid(spacing.merge('sections' => EDGED_GRID_SECTIONS))
      # (Inside CollectionContentFit when the grid's height is wrapContent or
      # undeclared, 4f ruling 2026-09-27 — hence any indentation.)
      expect(code).to match(/ScrollView\(\.vertical, showsIndicators: true\) \{\n *VStack\(alignment: \.leading, spacing: #{gap}\) \{/), spacing.inspect
    end
  end

  it "a section's header and footer are full-width rows, the view at the start" do
    code = grid('sections' => EDGED_GRID_SECTIONS)
    expect(code.scan(/HCellView\(data: headerData\)\n\s*\.frame\(maxWidth: \.infinity, alignment: \.leading\)/).size).to eq(2)
    expect(code.scan(/FCellView\(data: footerData\)\n\s*\.frame\(maxWidth: \.infinity, alignment: \.leading\)/).size).to eq(1)
  end

  it 'two sections with no edges are a column too; the class-list header and footer are rows of it' do
    expect(grid('sections' => [{ 'cell' => 'ACell' }, { 'cell' => 'BCell' }])).to include('VStack(alignment: .leading, spacing: 0) {')
    legacy = grid('cellClasses' => ['ACell'], 'headerClasses' => ['HCell'], 'footerClasses' => ['FCell'], 'lineSpacing' => 6)
    expect(legacy).to include('VStack(alignment: .leading, spacing: 6) {')
    expect(legacy).to match(/HCellView\(data: \[String: Any\]\(\)\)\n\s*\.frame\(maxWidth: \.infinity, alignment: \.leading\)/)
  end

  it 'control: a lone grid (one section, no header or footer; a class list without them) is emitted as it was' do
    expect(grid('sections' => [{ 'cell' => 'ACell' }])).not_to include('VStack(')
    expect(grid('cellClasses' => ['ACell'])).not_to include('VStack(')
  end

  it 'type-checks, sections and class list', :swift_compile do
    stubs = EmittedSwift::COLLECTION_DATA_SOURCE_STUB + cell_view_stub('ACellView', 'BCellView', 'HCellView', 'FCellView')
    codes = [grid('sections' => EDGED_GRID_SECTIONS, 'lineSpacing' => 4),
             grid('cellClasses' => ['ACell'], 'headerClasses' => ['HCell'], 'footerClasses' => ['FCell'])]
    expect(compilable_view("VStack {\n#{codes.join("\n")}\n}", data: ['var rows: CollectionDataSource? = nil'], stubs: stubs)).to compile_as_swift
  end
end
