#!/usr/bin/env node
/**
 * Web conformance host — fixture codegen.
 *
 * 1. Copies every web-applicable fixture layout from the conformance
 *    manifest into src/Layouts/pages/ under a stable synthetic name
 *    (fx_NNNN.json → component FxNNNN).
 * 2. Runs `rjui build` (rjui_tools React codegen) over them — the exact
 *    production codegen path.
 * 3. Emits src/generated/fixtureRegistry.tsx (fixture id → lazy route),
 *    src/generated/fixture-map.json (metadata for the runner) and
 *    src/generated/conformance-colors.css (named-color utilities).
 *
 * Everything under src/generated/ and src/Layouts/ is a build artifact
 * (@generated) and is gitignored.
 *
 * Paths (all overridable):
 *   --conformance-dir / JSONUI_CONFORMANCE_DIR  default: ../../.. of this script (repo conformance/)
 *   --rjui / RJUI_TOOLS_PATH                    default: <repo>/rjui_tools
 *   --ruby / RUBY_BIN                           default: ruby
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const hostDir = path.resolve(scriptDir, '..');

function arg(name, envName, fallback) {
  const idx = process.argv.indexOf(name);
  if (idx !== -1 && process.argv[idx + 1]) return process.argv[idx + 1];
  if (envName && process.env[envName]) return process.env[envName];
  return fallback;
}

const conformanceDir = path.resolve(
  arg('--conformance-dir', 'JSONUI_CONFORMANCE_DIR', path.resolve(hostDir, '../..'))
);
const rjuiDir = path.resolve(
  arg('--rjui', 'RJUI_TOOLS_PATH', path.resolve(conformanceDir, '../rjui_tools'))
);
const rubyBin = arg('--ruby', 'RUBY_BIN', 'ruby');

const manifestPath = path.join(conformanceDir, 'manifest.json');
if (!fs.existsSync(manifestPath)) {
  console.error(`manifest not found: ${manifestPath} — run \`jui conformance generate\` first`);
  process.exit(1);
}
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

// ---------------------------------------------------------------- clean
const layoutsPagesDir = path.join(hostDir, 'src/Layouts/pages');
const layoutsResourcesDir = path.join(hostDir, 'src/Layouts/Resources');
const generatedDir = path.join(hostDir, 'src/generated');
for (const dir of [layoutsPagesDir, layoutsResourcesDir, generatedDir]) {
  fs.rmSync(dir, { recursive: true, force: true });
}
fs.mkdirSync(layoutsPagesDir, { recursive: true });

// ---------------------------------------------------------------- copy layouts
const webFixtures = manifest.fixtures.filter((f) => f.platforms.includes('web'));
const entries = [];
webFixtures.forEach((fixture, i) => {
  const name = `fx_${String(i + 1).padStart(4, '0')}`;
  const component = `Fx${String(i + 1).padStart(4, '0')}`;
  fs.copyFileSync(
    path.join(conformanceDir, fixture.layout),
    path.join(layoutsPagesDir, `${name}.json`)
  );
  entries.push({ id: fixture.id, component });
});
console.log(`[generate] copied ${entries.length} web-applicable fixture layouts`);

// ---------------------------------------------------------------- rjui build
const rjuiBin = path.join(rjuiDir, 'bin/rjui');
if (!fs.existsSync(rjuiBin)) {
  console.error(`rjui_tools not found: ${rjuiBin} (set RJUI_TOOLS_PATH)`);
  process.exit(1);
}
console.log(`[generate] running rjui build (${rjuiDir})`);
const build = spawnSync(rubyBin, [rjuiBin, 'build'], {
  cwd: hostDir,
  stdio: ['ignore', 'pipe', 'pipe'],
  encoding: 'utf8',
  maxBuffer: 64 * 1024 * 1024,
});
fs.writeFileSync(path.join(hostDir, 'rjui-build.log'), (build.stdout ?? '') + (build.stderr ?? ''));
if (build.status !== 0) {
  console.error('[generate] rjui build failed — see rjui-build.log');
  process.exit(1);
}
const buildErrors = (build.stdout ?? '')
  .split('\n')
  .filter((l) => l.includes('[ERROR]'));
if (buildErrors.length > 0) {
  console.warn(`[generate] rjui build reported ${buildErrors.length} error line(s) — see rjui-build.log`);
}

// ---------------------------------------------------------------- registry
const componentsDir = path.join(generatedDir, 'components');
const dataDir = path.join(generatedDir, 'data');
let generatedCount = 0;
for (const entry of entries) {
  entry.hasComponent = fs.existsSync(path.join(componentsDir, `${entry.component}.tsx`));
  entry.hasData = fs.existsSync(path.join(dataDir, `${entry.component}Data.ts`));
  if (entry.hasComponent) generatedCount += 1;
}
console.log(`[generate] ${generatedCount}/${entries.length} components generated`);

const registryLines = [];
registryLines.push('// @generated by scripts/generate.mjs — DO NOT EDIT');
registryLines.push("import React, { lazy } from 'react';");
registryLines.push('');
registryLines.push('type Entry = { component: React.LazyExoticComponent<React.ComponentType> };');
registryLines.push('');
registryLines.push('export const fixtures: Record<string, Entry> = {');
for (const entry of entries) {
  if (!entry.hasComponent) continue;
  const dataImport = entry.hasData
    ? `const d = await import('./data/${entry.component}Data'); const data = d.create${entry.component}Data();`
    : 'const data = {};';
  registryLines.push(`  ${JSON.stringify(entry.id)}: {`);
  registryLines.push('    component: lazy(async () => {');
  registryLines.push(`      const m = await import('./components/${entry.component}');`);
  registryLines.push(`      ${dataImport}`);
  registryLines.push('      const C = m.default as React.ComponentType<{ data: unknown }>;');
  registryLines.push('      return { default: () => <C data={data} /> };');
  registryLines.push('    }),');
  registryLines.push('  },');
}
registryLines.push('};');
registryLines.push('');
fs.writeFileSync(path.join(generatedDir, 'fixtureRegistry.tsx'), registryLines.join('\n'));

fs.writeFileSync(
  path.join(generatedDir, 'fixture-map.json'),
  JSON.stringify(
    Object.fromEntries(entries.map((e) => [e.id, { component: e.component, hasComponent: e.hasComponent }])),
    null,
    2
  ) + '\n'
);

// ---------------------------------------------------------------- colors css
// rjui build extracts hex colors into Layouts/Resources/colors.json and
// rewrites layouts to named keys (bg-<key> etc.). Emit plain utilities so the
// classes resolve regardless of Tailwind theme configuration.
const colorsPath = path.join(layoutsResourcesDir, 'colors.json');
const cssLines = ['/* @generated by scripts/generate.mjs — DO NOT EDIT */'];
if (fs.existsSync(colorsPath)) {
  const colors = JSON.parse(fs.readFileSync(colorsPath, 'utf8'));
  const palette = colors[colors.fallback_mode || 'light'] || {};
  for (const [key, hex] of Object.entries(palette)) {
    cssLines.push(`.bg-${key} { background-color: ${hex}; }`);
    cssLines.push(`.text-${key} { color: ${hex}; }`);
    cssLines.push(`.border-${key} { border-color: ${hex}; }`);
    cssLines.push(`.placeholder-${key}::placeholder { color: ${hex}; }`);
  }
}
cssLines.push('');
fs.writeFileSync(path.join(generatedDir, 'conformance-colors.css'), cssLines.join('\n'));

console.log('[generate] wrote fixtureRegistry.tsx, fixture-map.json, conformance-colors.css');
const failed = entries.filter((e) => !e.hasComponent);
if (failed.length > 0) {
  console.warn(`[generate] fixtures WITHOUT component (will be reported as error):`);
  for (const f of failed) console.warn(`  - ${f.id}`);
}
