#!/usr/bin/env node
/**
 * Web host typecheck ratchet.
 *
 * The host is generated by the production rjui codegen, so a type error here
 * is a type error in every consumer's @generated tree — and nobody downstream
 * can patch an @generated file. `tsc --noEmit` has always been available as an
 * npm script and never wired to a gate; this closes that.
 *
 * The remaining errors have three separate owners (see typecheck-baseline.json),
 * so waiting for zero before gating would leave the hole open indefinitely.
 * Instead the known count is pinned: more than the baseline fails, fewer prints
 * the one-line edit that tightens it.
 *
 * Usage: node scripts/typecheck_ratchet.mjs
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const hostDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const baselinePath = path.join(hostDir, 'typecheck-baseline.json');

const baseline = JSON.parse(fs.readFileSync(baselinePath, 'utf8'));
const allowed = baseline.maxErrors;

const tsc = spawnSync('npx', ['tsc', '--noEmit'], { cwd: hostDir, encoding: 'utf8' });
const output = `${tsc.stdout ?? ''}${tsc.stderr ?? ''}`;
const errors = output.split('\n').filter((line) => /error TS\d+:/.test(line));

// tsc exits non-zero for a crash too; a crash has no error lines to count.
if (errors.length === 0 && tsc.status !== 0) {
  console.error('[typecheck-ratchet] tsc failed without reporting type errors:');
  console.error(output.trim());
  process.exit(1);
}

console.log(`[typecheck-ratchet] ${errors.length} type error(s), baseline ${allowed}`);

if (errors.length > allowed) {
  const known = new Set(baseline.knownFiles ?? []);
  const fresh = errors.filter((line) => !known.has(line.split('(')[0]));
  console.error(`[typecheck-ratchet] FAIL: ${errors.length - allowed} new type error(s).`);
  console.error('Generated code must typecheck — a consumer cannot patch an @generated file.');
  for (const line of (fresh.length ? fresh : errors).slice(0, 20)) console.error(`  ${line}`);
  process.exit(1);
}

if (errors.length < allowed) {
  console.log(
    `[typecheck-ratchet] ${allowed - errors.length} fewer than the baseline — ` +
    `tighten it: set "maxErrors": ${errors.length} in typecheck-baseline.json`
  );
}
