# frozen_string_literal: true

require 'fileutils'
require 'json'
require_relative '../../core/logger'
require_relative 'react_component_generator'

module RjuiTools
  module React
    module Generators
      class ConverterGenerator
        def initialize(name, options = {}, config = {}, command_line = nil)
          @name = name  # PascalCase name like CodeBlock
          @class_name = "#{name}Converter"
          @options = options
          @config = config
          @command_line = command_line
          @logger = Core::Logger
        end

        def generate
          @logger.info "Generating custom converter: #{@class_name}"

          # Create converter file
          create_converter_file

          # Update mappings file
          update_mappings_file

          # Create React component skeleton
          component_generator = ReactComponentGenerator.new(@name, @options, @config, @command_line)
          component_generator.generate

          # Generate attribute definition file for validation
          generate_attribute_definition_file

          @logger.success "Successfully generated converter: #{@class_name}"
          @logger.info "Converter file: #{converter_file_path}"
          @logger.info "Run 'rjui build' to use the new component in your layouts"
        end

        private

        def extensions_dir
          # Check if we're in the project with rjui_tools at root
          if File.exist?(File.join(Dir.pwd, 'rjui_tools'))
            File.join(Dir.pwd, 'rjui_tools', 'lib', 'react', 'converters', 'extensions')
          else
            File.join(Dir.pwd, 'lib', 'react', 'converters', 'extensions')
          end
        end

        def converter_file_path
          snake_case_name = to_snake_case(@name)
          File.join(extensions_dir, "#{snake_case_name}_converter.rb")
        end

        def create_converter_file
          FileUtils.mkdir_p(extensions_dir)

          file_path = converter_file_path

          if File.exist?(file_path)
            # `jui build` (and other non-interactive flows) set JUI_SKIP_EXISTING=1
            # so the prompt is bypassed and existing converter files are left alone.
            if ENV['JUI_SKIP_EXISTING'] == '1'
              @logger.info "Skipped existing converter: #{file_path}"
              return
            end
            @logger.warn "Converter file already exists: #{file_path}"
            print "Overwrite? (y/n): "
            response = $stdin.gets.chomp.downcase
            return unless response == 'y'
          end

          File.write(file_path, converter_template)
          @logger.info "Created converter file: #{file_path}"
        end

        def update_mappings_file
          mappings_file = File.join(extensions_dir, 'converter_mappings.rb')

          if !File.exist?(mappings_file)
            create_initial_mappings_file(mappings_file)
            return
          end

          content = File.read(mappings_file)

          # Check if mapping already exists
          if content.include?("'#{@name}' =>")
            @logger.warn "Mapping for '#{@name}' already exists in converter_mappings.rb"
            return
          end

          # Add new mapping
          new_mapping = "          '#{@name}' => '#{@class_name}',"

          # Insert the new mapping before the closing brace
          content.sub!(/(CONVERTER_MAPPINGS = \{.*?)(,?)(\s*)(        \}\.freeze)/m) do
            existing = $1
            closing = $4

            if existing =~ /=>/
              "#{existing},\n#{new_mapping}\n#{closing}"
            else
              "#{existing}\n#{new_mapping}\n#{closing}"
            end
          end

          File.write(mappings_file, content)
          @logger.info "Updated converter_mappings.rb"
        end

        def create_initial_mappings_file(mappings_file)
          FileUtils.mkdir_p(File.dirname(mappings_file))

          content = <<~RUBY
            # frozen_string_literal: true

            # This file maps custom component types to their converter classes
            # Auto-generated by rjui g converter command

            module RjuiTools
              module React
                module Converters
                  module Extensions
                    CONVERTER_MAPPINGS = {
                      '#{@name}' => '#{@class_name}',
                    }.freeze
                  end
                end
              end
            end
          RUBY

          File.write(mappings_file, content)
          @logger.info "Created converter_mappings.rb"
        end

        def converter_template
          attr_lines = generate_attribute_lines
          props_lines = generate_props_lines
          is_container = @options[:is_container]

          template = []
          template << '# frozen_string_literal: true'
          template << ''
          template << "# Generated by: #{@command_line}" if @command_line
          template << ''
          template << "require_relative '../base_converter'"
          template << ''
          template << 'module RjuiTools'
          template << '  module React'
          template << '    module Converters'
          template << '      module Extensions'
          template << "        class #{@class_name} < BaseConverter"
          template << '          def convert(indent = 2)'
          template << '            class_name = build_class_name'
          template << '            id_attr = extract_id ? %( id="#{extract_id}") : \'\''
          template << ''
          template.concat(attr_lines)
          template << ''
          template << '            # Build the component JSX'
          template << '            props = []'
          template.concat(props_lines)
          template << '            props_str = props.empty? ? \'\' : " #{props.join(\' \')}"'
          template << ''

          # Add container check
          template.concat(generate_container_check_lines)
          template << ''

          # Generate different output based on container mode
          if is_container == false
            # Force non-container mode
            template << '            <<~JSX.chomp'
            template << "              \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str} />"
            template << '            JSX'
          else
            # Container mode (auto-detect or forced)
            template << '            if is_container'
            template << '              children_jsx = convert_children(indent + 2)'
            template << '              <<~JSX.chomp'
            template << "                \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str}>"
            template << '                #{children_jsx}'
            template << "                \#{indent_str(indent)}</#{@name}>"
            template << '              JSX'
            template << '            else'
            template << '              <<~JSX.chomp'
            template << "                \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str} />"
            template << '              JSX'
            template << '            end'
          end

          template << '          end'
          template << ''
          template << '          protected'
          template << ''
          template << '          def build_class_name'
          template << '            # Get base classes from parent (handles margins, padding, etc.)'
          template << '            base_classes = super'
          template << ''
          template << '            # Add component-specific classes'
          template << "            classes = ['flex', 'flex-col']"
          template << '            classes << base_classes unless base_classes.empty?'
          template << ''
          template << "            classes.compact.reject(&:empty?).join(' ')"
          template << '          end'
          template << '        end'
          template << '      end'
          template << '    end'
          template << '  end'
          template << 'end'

          template.join("\n") + "\n"
        end

        def generate_container_check_lines
          case @options[:is_container]
          when true
            [
              '            # Force container mode',
              '            is_container = true'
            ]
          when false
            [
              '            # Force non-container mode',
              '            is_container = false'
            ]
          else
            [
              '            # Auto-detect container based on children or child',
              "            is_container = (json['children'] && !json['children'].empty?) || (json['child'] && !json['child'].empty?)"
            ]
          end
        end

        def generate_attribute_lines
          return ['            # No custom attributes'] if @options[:attributes].empty?

          @options[:attributes].map do |key, _type|
            "            #{key}_value = json['#{key}']"
          end
        end

        def generate_props_lines
          return ['            # No custom props'] if @options[:attributes].empty?

          lines = []
          @options[:attributes].each do |key, type|
            t = normalize_type(type)

            # Generate binding-aware prop handling
            lines << "            if #{key}_value"
            lines << "              if #{key}_value.is_a?(String) && #{key}_value.start_with?('@{') && #{key}_value.end_with?('}')"
            lines << "                # Handle binding - extract property name"
            lines << "                prop_name = #{key}_value[2..-2]"
            lines << "                props << \"#{key}={\#{prop_name}}\""
            lines << "              else"
            lines.concat(emit_literal_branch(key, t))
            lines << "              end"
            lines << "            end"
          end
          lines
        end

        # Emit the literal-value branch for a single prop, given a normalized
        # type descriptor. Kept separate from generate_props_lines so both the
        # prop emitter and future tests can use it.
        def emit_literal_branch(key, t)
          if t[:array]
            # Array literal — serialize with JSON, then walk VALUES and
            # substitute any that resolve in strings.json. Element fields
            # like `label: "toc_row_x"` become `label: StringManager…`
            # while identifier fields like `id: "a"` fall through unchanged
            # (they don't resolve, so the safety gate in
            # `rewrite_json_string_values` leaves them alone).
            [
              "                require 'json' unless defined?(JSON)",
              "                json_str = rewrite_json_string_values(JSON.generate(#{key}_value))",
              "                props << \"#{key}={\#{json_str}}\""
            ]
          else
            case t[:base]
            when 'string'
              # When the literal is a snake_case key AND registered in
              # strings.json, treat it as a StringManager lookup (same
              # contract the standard Label `text` pass uses) so custom
              # component props participate in localization.
              # `convert_string_key` returns the wrapped
              # `{StringManager.currentLanguage.xxx}` expression, or nil
              # when the key isn't in strings.json (e.g. `"bash"`,
              # `"yaml"` — identifiers that look like snake_case but are
              # not translations). On nil we fall through to a JSX
              # template literal; JSX string attributes (`key="value"`)
              # break on newlines, embedded quotes, backticks, and ${},
              # so the template literal + escape pass handles all four.
              [
                "                if (resolved = convert_string_key(#{key}_value))",
                "                  props << \"#{key}=\#{resolved}\"",
                "                else",
                "                  escaped = #{key}_value.to_s.gsub('\\\\') { '\\\\\\\\' }.gsub('`') { '\\\\`' }.gsub('${') { '\\\\${' }",
                "                  props << \"#{key}={`\#{escaped}`}\"",
                "                end"
              ]
            when 'bool', 'boolean'
              ["                props << \"#{key}={\#{#{key}_value ? 'true' : 'false'}}\""]
            when 'int', 'integer', 'number', 'double', 'float'
              ["                props << \"#{key}={\#{#{key}_value}}\""]
            else
              # Custom / unknown types: literal values aren't safely emittable.
              # Serialize via JSON so the scaffold at least produces valid JSX,
              # and leave a note pointing authors at bindings as the intended path.
              [
                "                # NOTE: #{t[:base]} is a custom type — prefer @{binding} over literal values",
                "                require 'json' unless defined?(JSON)",
                "                props << \"#{key}={\#{JSON.generate(#{key}_value)}}\""
              ]
            end
          end
        end

        # Generate attribute definition file for validation
        def generate_attribute_definition_file
          # Skip if no attributes and not a container
          has_attributes = @options[:attributes] && !@options[:attributes].empty?
          is_container = @options[:is_container] == true
          return if !has_attributes && !is_container

          # Determine directory path based on project structure
          if File.exist?(File.join(Dir.pwd, 'rjui_tools'))
            attr_defs_dir = File.join(Dir.pwd, 'rjui_tools', 'lib', 'react', 'converters', 'extensions', 'attribute_definitions')
          else
            attr_defs_dir = File.join(Dir.pwd, 'lib', 'react', 'converters', 'extensions', 'attribute_definitions')
          end

          # Create directory if it doesn't exist
          FileUtils.mkdir_p(attr_defs_dir)

          # Build attribute definitions
          attributes = {}
          if has_attributes
            @options[:attributes].each do |key, type|
              # Remove @ prefix if this is a binding attribute
              actual_key = key.start_with?('@') ? key[1..-1] : key
              attributes[actual_key] = build_attribute_definition(actual_key, type)
            end
          end

          # Add child/children for container components
          if is_container
            attributes["child"] = { "type" => "array", "description" => "Child component(s)" }
            attributes["children"] = { "type" => "array", "description" => "Child components (alias for child)" }
          end

          # Build JSON structure
          json_content = {
            @name => attributes
          }

          # Write to file
          file_path = File.join(attr_defs_dir, "#{@name}.json")
          File.write(file_path, JSON.pretty_generate(json_content))

          @logger.info "Created attribute definition file: attribute_definitions/#{@name}.json"
        end

        # Normalize a type string that arrives from component specs (`String?`,
        # `[Int]?`, `Bool`, `MyType?` …) into a canonical descriptor so the
        # downstream case dispatches don't end up in a fallback branch and
        # drop `String?` on the binding-only / `.inspect` path.
        #
        # Returns { base: String, array: Boolean, optional: Boolean }.
        def normalize_type(type_str)
          s = type_str.to_s.strip
          optional = s.end_with?('?')
          s = s.chomp('?')
          array = s.start_with?('[') && s.end_with?(']')
          s = s[1..-2] if array
          s = s.chomp('?') # strip inner `Int?` inside `[Int?]`
          { base: s.downcase, array: array, optional: optional }
        end

        # Map type string to JSON schema type (supports binding for all types).
        # Normalizes optional/array suffixes first so `String?` and `[Int]?`
        # from component specs don't fall through to the binding-only branch.
        # @param type [String] The type string from options
        # @return [Array, String] JSON schema type(s) - array for binding support
        def map_type_to_json_type(type)
          t = normalize_type(type)
          return ['array', 'binding'] if t[:array]

          case t[:base]
          when 'string'
            ['string', 'binding']
          when 'int', 'integer', 'number', 'double', 'float'
            ['number', 'binding']
          when 'bool', 'boolean'
            ['boolean', 'binding']
          when 'color'
            # Color accepts a semantic key ("dark_brown_text") or a binding.
            # The React component's color resolver handles both.
            ['string', 'binding']
          else
            # Custom class types must use binding syntax (@{propertyName})
            'binding'
          end
        end

        def build_attribute_definition(actual_key, type)
          {
            "type" => map_type_to_json_type(type),
            "description" => "#{actual_key} attribute"
          }
        end

        def to_snake_case(string)
          string
            .gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
            .gsub(/([a-z\d])([A-Z])/, '\1_\2')
            .downcase
        end
      end
    end
  end
end
