# frozen_string_literal: true

require 'fileutils'
require 'json'
require_relative '../../core/logger'
require_relative '../../core/generated_marker'
require_relative '../../core/converter_generator_core'
require_relative 'react_component_generator'

module RjuiTools
  module React
    module Generators
      # Web profile over the shared converter-scaffolder body
      # (lib/core/converter_generator_core.rb — byte-identical mirror of
      # shared/core/converter_generator_core.rb, pinned by
      # spec/core/shared_core_mirror_spec.rb). The overwrite flow, registry
      # patching, attribute-definition JSON and type mapping live in the
      # shared core; this class owns the JSX scaffold template and the
      # React component sub-generator.
      class ConverterGenerator < ::JsonUIShared::ConverterGeneratorCore
        def initialize(name, options = {}, config = {}, command_line = nil)
          @name = name  # PascalCase name like CodeBlock
          @class_name = "#{name}Converter"
          @options = options
          @config = config
          @command_line = command_line
          @logger = Core::Logger
        end

        def generate
          @logger.info "Generating custom converter: #{@class_name}"

          # Create converter file
          create_converter_file

          # Update mappings file
          update_mappings_file

          # Create React component skeleton
          component_generator = ReactComponentGenerator.new(@name, @options, @config, @command_line)
          component_generator.generate

          # Generate attribute definition file for validation
          generate_attribute_definition_file

          @logger.success "Successfully generated converter: #{@class_name}"
          @logger.info "Converter file: #{converter_file_path}"
          @logger.info "Run 'rjui build' to use the new component in your layouts"
        end

        private

        def extensions_dir
          # Check if we're in the project with rjui_tools at root
          if File.exist?(File.join(Dir.pwd, 'rjui_tools'))
            File.join(Dir.pwd, 'rjui_tools', 'lib', 'react', 'converters', 'extensions')
          else
            File.join(Dir.pwd, 'lib', 'react', 'converters', 'extensions')
          end
        end

        def converter_file_name
          "#{to_snake_case(@name)}_converter.rb"
        end

        def registry_spec
          {
            file: File.join(extensions_dir, 'converter_mappings.rb'),
            const: 'CONVERTER_MAPPINGS',
            mapping_line: "          '#{@name}' => '#{@class_name}',",
            initial_content: <<~RUBY
              # frozen_string_literal: true

              # This file maps custom component types to their converter classes
              # Auto-generated by rjui g converter command

              module RjuiTools
                module React
                  module Converters
                    module Extensions
                      CONVERTER_MAPPINGS = {
                        '#{@name}' => '#{@class_name}',
                      }.freeze
                    end
                  end
                end
              end
            RUBY
          }
        end

        def attr_defs_dir
          File.join(extensions_dir, 'attribute_definitions')
        end

        def command_string
          @command_line || build_command_string('rjui g converter')
        end

        def json_marker(source:, generator:)
          Core::GeneratedMarker.json_marker(source: source, generator: generator)
        end

        def converter_template
          attr_lines = generate_attribute_lines
          props_lines = generate_props_lines
          is_container = @options[:is_container]

          template = []
          template << '# frozen_string_literal: true'
          template << ''
          template << "# Generated by: #{@command_line}" if @command_line
          template << ''
          template << "require_relative '../base_converter'"
          template << ''
          template << 'module RjuiTools'
          template << '  module React'
          template << '    module Converters'
          template << '      module Extensions'
          template << "        class #{@class_name} < BaseConverter"
          template << '          def convert(indent = 2)'
          template << '            class_name = build_class_name'
          template << '            id_attr = extract_id ? %( id="#{extract_id}") : \'\''
          template << ''
          template.concat(attr_lines)
          template << ''
          template << '            # Build the component JSX'
          template << '            props = []'
          template.concat(props_lines)
          template << '            props_str = props.empty? ? \'\' : " #{props.join(\' \')}"'
          template << ''

          # Add container check
          template.concat(generate_container_check_lines)
          template << ''

          # Generate different output based on container mode
          if is_container == false
            # Force non-container mode
            template << '            <<~JSX.chomp'
            template << "              \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str} />"
            template << '            JSX'
          else
            # Container mode (auto-detect or forced)
            template << '            if is_container'
            template << '              children_jsx = convert_children(indent + 2)'
            template << '              <<~JSX.chomp'
            template << "                \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str}>"
            template << '                #{children_jsx}'
            template << "                \#{indent_str(indent)}</#{@name}>"
            template << '              JSX'
            template << '            else'
            template << '              <<~JSX.chomp'
            template << "                \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str} />"
            template << '              JSX'
            template << '            end'
          end

          template << '          end'
          template << ''
          template << '          protected'
          template << ''
          template << '          def build_class_name'
          template << '            # Get base classes from parent (handles margins, padding, etc.)'
          template << '            base_classes = super'
          template << ''
          template << '            # Add component-specific classes'
          template << "            classes = ['flex', 'flex-col']"
          template << '            classes << base_classes unless base_classes.empty?'
          template << ''
          template << "            classes.compact.reject(&:empty?).join(' ')"
          template << '          end'
          template << '        end'
          template << '      end'
          template << '    end'
          template << '  end'
          template << 'end'

          template.join("\n") + "\n"
        end

        def generate_container_check_lines
          case @options[:is_container]
          when true
            [
              '            # Force container mode',
              '            is_container = true'
            ]
          when false
            [
              '            # Force non-container mode',
              '            is_container = false'
            ]
          else
            [
              '            # Auto-detect container based on children or child',
              "            is_container = (json['children'] && !json['children'].empty?) || (json['child'] && !json['child'].empty?)"
            ]
          end
        end

        def generate_attribute_lines
          return ['            # No custom attributes'] if @options[:attributes].empty?

          @options[:attributes].map do |key, _type|
            "            #{key}_value = json['#{key}']"
          end
        end

        def generate_props_lines
          return ['            # No custom props'] if @options[:attributes].empty?

          lines = []
          @options[:attributes].each do |key, type|
            t = normalize_type(type)

            # Generate binding-aware prop handling
            lines << "            if #{key}_value"
            lines << "              if #{key}_value.is_a?(String) && #{key}_value.start_with?('@{') && #{key}_value.end_with?('}')"
            lines << "                # Handle binding - resolve to data.xxx like built-in converters"
            lines << "                prop_name = add_viewmodel_data_prefix(#{key}_value[2..-2])"
            lines << "                props << \"#{key}={\#{prop_name}}\""
            lines << "              else"
            lines.concat(emit_literal_branch(key, t))
            lines << "              end"
            lines << "            end"
          end
          lines
        end

        # Emit the literal-value branch for a single prop, given a normalized
        # type descriptor. Kept separate from generate_props_lines so both the
        # prop emitter and future tests can use it.
        def emit_literal_branch(key, t)
          if t[:array]
            # Array literal — serialize with JSON, then walk VALUES and
            # substitute any that resolve in strings.json. Element fields
            # like `label: "toc_row_x"` become `label: StringManager…`
            # while identifier fields like `id: "a"` fall through unchanged
            # (they don't resolve, so the safety gate in
            # `rewrite_json_string_values` leaves them alone).
            [
              "                require 'json' unless defined?(JSON)",
              "                json_str = rewrite_json_string_values(JSON.generate(#{key}_value))",
              "                props << \"#{key}={\#{json_str}}\""
            ]
          else
            case t[:base]
            when 'string'
              # When the literal is a snake_case key AND registered in
              # strings.json, treat it as a StringManager lookup (same
              # contract the standard Label `text` pass uses) so custom
              # component props participate in localization.
              # `convert_string_key` returns the wrapped
              # `{StringManager.currentLanguage.xxx}` expression, or nil
              # when the key isn't in strings.json (e.g. `"bash"`,
              # `"yaml"` — identifiers that look like snake_case but are
              # not translations). On nil we fall through to a JSX
              # template literal; JSX string attributes (`key="value"`)
              # break on newlines, embedded quotes, backticks, and ${},
              # so the template literal + escape pass handles all four.
              [
                "                if (resolved = convert_string_key(#{key}_value))",
                "                  props << \"#{key}=\#{resolved}\"",
                "                else",
                "                  escaped = #{key}_value.to_s.gsub('\\\\') { '\\\\\\\\' }.gsub('`') { '\\\\`' }.gsub('${') { '\\\\${' }",
                "                  props << \"#{key}={`\#{escaped}`}\"",
                "                end"
              ]
            when 'bool', 'boolean'
              ["                props << \"#{key}={\#{#{key}_value ? 'true' : 'false'}}\""]
            when 'int', 'integer', 'number', 'double', 'float'
              ["                props << \"#{key}={\#{#{key}_value}}\""]
            else
              # Custom / unknown types: literal values aren't safely emittable.
              # Serialize via JSON so the scaffold at least produces valid JSX,
              # and leave a note pointing authors at bindings as the intended path.
              [
                "                # NOTE: #{t[:base]} is a custom type — prefer @{binding} over literal values",
                "                require 'json' unless defined?(JSON)",
                "                props << \"#{key}={\#{JSON.generate(#{key}_value)}}\""
              ]
            end
          end
        end
      end
    end
  end
end
