# frozen_string_literal: true

require 'fileutils'
require 'json'
require_relative '../../core/logger'
require_relative '../../core/generated_marker'
require_relative '../../core/converter_generator_core'
require_relative 'react_component_generator'

module RjuiTools
  module React
    module Generators
      # Web profile over the shared converter-scaffolder body
      # (lib/core/converter_generator_core.rb — byte-identical mirror of
      # shared/core/converter_generator_core.rb, pinned by
      # spec/core/shared_core_mirror_spec.rb). The overwrite flow, registry
      # patching, attribute-definition JSON and type mapping live in the
      # shared core; this class owns the JSX scaffold template and the
      # React component sub-generator.
      class ConverterGenerator < ::JsonUIShared::ConverterGeneratorCore
        def initialize(name, options = {}, config = {}, command_line = nil)
          @name = name  # PascalCase name like CodeBlock
          @class_name = "#{name}Converter"
          @options = options
          @config = config
          @command_line = command_line
          @logger = Core::Logger
        end

        def generate
          @logger.info "Generating custom converter: #{@class_name}"
          track_scaffold_files
          keep_children_declaration

          # Create converter file
          create_converter_file

          # Update mappings file
          update_mappings_file

          # Create React component skeleton
          component_generator = ReactComponentGenerator.new(@name, @options, @config, @command_line)
          component_generator.generate

          # After the scaffold: it says "kept" when the run wrote none.
          warn_outside_attribute_types

          # Generate attribute definition file for validation
          generate_attribute_definition_file

          # What the run did, from what it recorded — each file has said its
          # own line above (Created / Overwrote / Skipped / Kept, with its
          # path). Until 1.8.121: "Successfully generated converter" whatever
          # it had done (ticket g-converter-reports-files-it-did-not-write).
          report_scaffold
          @logger.info "Converter file: #{converter_file_path}"
          @logger.info "Run 'rjui build' to use the new component in your layouts"
        end

        private

        def extensions_dir
          # Check if we're in the project with rjui_tools at root
          if File.exist?(File.join(Dir.pwd, 'rjui_tools'))
            File.join(Dir.pwd, 'rjui_tools', 'lib', 'react', 'converters', 'extensions')
          else
            File.join(Dir.pwd, 'lib', 'react', 'converters', 'extensions')
          end
        end

        def converter_file_name
          "#{to_snake_case(@name)}_converter.rb"
        end

        def registry_spec
          {
            file: File.join(extensions_dir, 'converter_mappings.rb'),
            const: 'CONVERTER_MAPPINGS',
            mapping_line: "          '#{@name}' => '#{@class_name}',",
            initial_content: <<~RUBY
              # frozen_string_literal: true

              # This file maps custom component types to their converter classes
              # Auto-generated by rjui g converter command

              module RjuiTools
                module React
                  module Converters
                    module Extensions
                      CONVERTER_MAPPINGS = {
                        '#{@name}' => '#{@class_name}',
                      }.freeze
                    end
                  end
                end
              end
            RUBY
          }
        end

        def attr_defs_dir
          File.join(extensions_dir, 'attribute_definitions')
        end

        def command_string
          @command_line || build_command_string('rjui g converter')
        end

        def json_marker(source:, generator:)
          Core::GeneratedMarker.json_marker(source: source, generator: generator)
        end

        # The component .tsx a leaf was scaffolded with says nothing of
        # `children` at all (no prop, no render), so a kept one drops the
        # children the converter passes — with no compiler to object where the
        # build does not type-check, or where React's types still add
        # `children` to every FC. (A kept Swift view or composable in the leaf
        # form fails to compile when given content, so sjui and kjui need no
        # such rule.) Read only for a component that was declared a leaf
        # before this run: a component the app wrote without `children` in
        # the default mode is not this ticket's to turn into a leaf.
        def kept_view_leaf_form(path, text)
          return nil unless File.extname(path) == '.tsx'
          return nil unless declared_children == ::JsonUIShared::AttributeValidatorCore::NO_CHILDREN
          return nil if text.include?('children')

          'does not render `children`'
        end

        def converter_template
          attr_lines = generate_attribute_lines
          props_lines = generate_props_lines
          is_container = @options[:is_container]

          template = []
          template << '# frozen_string_literal: true'
          template << ''
          template << "# Generated by: #{@command_line}" if @command_line
          template << ''
          template << "require_relative '../base_converter'"
          template << "require_relative '../../../core/attribute_types'"
          template << ''
          template << 'module RjuiTools'
          template << '  module React'
          template << '    module Converters'
          template << '      module Extensions'
          template << "        class #{@class_name} < BaseConverter"
          template << '          def convert(indent = 2)'
          template << '            class_name = build_class_name'
          template << '            id_attr = extract_id ? %( id="#{extract_id}") : \'\''
          template << ''
          template.concat(attr_lines)
          template << ''
          template << '            # Build the component JSX'
          template << '            props = []'
          template.concat(props_lines)
          template << '            props_str = props.empty? ? \'\' : " #{props.join(\' \')}"'
          template << ''

          # Add container check
          template.concat(generate_container_check_lines)
          template << ''

          # Generate different output based on container mode
          if is_container == false
            # Force non-container mode
            template << '            <<~JSX.chomp'
            template << "              \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str} />"
            template << '            JSX'
          else
            # Container mode (auto-detect or forced)
            template << '            if is_container'
            template << '              children_jsx = convert_children(indent + 2)'
            template << '              <<~JSX.chomp'
            template << "                \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str}>"
            template << '                #{children_jsx}'
            template << "                \#{indent_str(indent)}</#{@name}>"
            template << '              JSX'
            template << '            else'
            template << '              <<~JSX.chomp'
            template << "                \#{indent_str(indent)}<#{@name}\#{id_attr} className=\"\#{class_name}\"\#{props_str} />"
            template << '              JSX'
            template << '            end'
          end

          template << '          end'
          template << ''
          template << '          protected'
          template << ''
          template.concat(format_literal_lines)
          template << ''
          template << '          def build_class_name'
          template << '            # Get base classes from parent (handles margins, padding, etc.)'
          template << '            base_classes = super'
          template << ''
          template << '            # Add component-specific classes'
          template << "            classes = ['flex', 'flex-col']"
          template << '            classes << base_classes unless base_classes.empty?'
          template << ''
          template << "            classes.compact.reject(&:empty?).join(' ')"
          template << '          end'
          template << '        end'
          template << '      end'
          template << '    end'
          template << '  end'
          template << 'end'

          template.join("\n") + "\n"
        end

        def generate_container_check_lines
          case @options[:is_container]
          when true
            [
              '            # Force container mode',
              '            is_container = true'
            ]
          when false
            [
              '            # Force non-container mode',
              '            is_container = false'
            ]
          else
            [
              '            # Auto-detect container based on children or child',
              "            is_container = (json['children'] && !json['children'].empty?) || (json['child'] && !json['child'].empty?)"
            ]
          end
        end

        def generate_attribute_lines
          return ['            # No custom attributes'] if @options[:attributes].empty?

          @options[:attributes].map do |key, _type|
            "            #{key}_value = json['#{key}']"
          end
        end

        def generate_props_lines
          return ['            # No custom props'] if @options[:attributes].empty?

          lines = []
          @options[:attributes].each do |key, type|
            # Binding-aware, and by key, not by value: a `false` the layout
            # gives is a value too. A literal goes through the shared
            # vocabulary (format_literal); one of another kind is not
            # written, and said — until 1.8.121 `if value` dropped a false
            # and every literal was written unchecked (ticket
            # rjui-literal-props-are-not-checked-against-the-type).
            lines << "            if #{key}_value.is_a?(String) && #{key}_value.start_with?('@{') && #{key}_value.end_with?('}')"
            lines << "              # Handle binding - resolve to data.xxx like built-in converters"
            lines << "              prop_name = add_viewmodel_data_prefix(#{key}_value[2..-2])"
            lines << "              props << \"#{key}={\#{prop_name}}\""
            lines << "            elsif !#{key}_value.nil?"
            lines << "              literal = format_literal(#{key}_value, '#{type}')"
            lines << "              if literal"
            lines << "                props << \"#{key}={\#{literal}}\""
            lines << "              else"
            lines << "                warn JsonUIShared::AttributeTypes.unwritten_warning('rjui', '#{@name}', '#{key}', " \
                     "#{key}_value, '#{type}')"
            lines << "              end"
            lines.concat(null_literal_branch(key, type))
            lines << "            end"
          end
          lines
        end

        # The converter's one literal writer: the TypeScript the prop's type
        # takes, by the shared vocabulary (JsonUIShared::AttributeTypes
        # .ts_literal — the table the component is scaffolded from, and the
        # rules the sjui and kjui converters write theirs by), nil when the
        # value is not of that type. A string that is a strings.json key
        # becomes its StringManager lookup, as the Label `text` pass does;
        # any other string a template literal, escaped by the shared escaper
        # (StringLiterals.ts_template_body). A list's JSON goes through
        # rewrite_json_string_values, so `items: [{label: "toc_row_x"}]`
        # localizes its element fields as it always has.
        def format_literal_lines
          [
            '          # A literal the layout gives a prop, as the TypeScript its type takes (nil: it cannot be written).',
            '          def format_literal(value, type)',
            '            literal = JsonUIShared::AttributeTypes.ts_literal(type, value) do |canonical, text|',
            "              next nil unless canonical == 'string' && text.is_a?(String)",
            '',
            '              resolved = convert_string_key(text)',
            '              resolved ? resolved[1..-2] : "`#{JsonUIShared::StringLiterals.ts_template_body(text)}`"',
            '            end',
            '            return literal unless literal && JsonUIShared::AttributeTypes.parse(type).kind == :list',
            '',
            '            rewrite_json_string_values(literal)',
            '          end'
          ]
        end

        # A JSON null the layout gives a prop: never written (every prop is
        # optional in TypeScript, and `null` is not one of the types the
        # component declares), and — for a type that takes no null on any
        # tool (JsonUIShared::AttributeTypes.takes_null?: `String`, `[Int]`,
        # `Object`, `Row!!` …) — said, in the sentence the sjui and kjui
        # converters print for a literal they cannot write. Until 1.8.121 rjui
        # dropped it without a word for every type. Ticket
        # converter-writes-nil-for-a-forced-model-prop.
        def null_literal_branch(key, type)
          return [] if JsonUIShared::AttributeTypes.takes_null?(type)

          [
            "            elsif json.key?('#{key}') && #{key}_value.nil?",
            "              warn JsonUIShared::AttributeTypes.unwritten_warning('rjui', '#{@name}', '#{key}', nil, '#{type}')"
          ]
        end
      end
    end
  end
end
