# frozen_string_literal: true

require 'fileutils'
require_relative '../../core/logger'

module RjuiTools
  module React
    module Generators
      class ReactComponentGenerator
        def initialize(name, options = {}, config = {}, command_line = nil)
          @name = name  # PascalCase name like CodeBlock
          @options = options
          @config = config
          @command_line = command_line
          @logger = Core::Logger
        end

        def generate
          @logger.info "Generating React component: #{@name}"

          create_component_file

          @logger.info "Created component file: #{component_file_path}"
        end

        private

        def components_dir
          # Use extensions_directory from config, or default to src/components/extensions
          @config['extensions_directory'] || 'src/components/extensions'
        end

        def component_file_path
          File.join(components_dir, "#{@name}.tsx")
        end

        def create_component_file
          FileUtils.mkdir_p(components_dir)

          file_path = component_file_path

          if File.exist?(file_path)
            @logger.warn "Component file already exists: #{file_path}"
            print "Overwrite? (y/n): "
            response = $stdin.gets.chomp.downcase
            return unless response == 'y'
          end

          File.write(file_path, component_template)
        end

        def component_template
          props_interface = generate_props_interface
          props_destructure = generate_props_destructure
          is_container = @options[:is_container]

          command_comment = @command_line ? "// Generated by: #{@command_line}\n" : ''

          # Generate body based on container mode
          body = if is_container == false
                   # Force non-container mode
                   "{/* TODO: Implement #{@name} component */}"
                 else
                   # Container mode (auto-detect or forced)
                   "{children}\n          {/* TODO: Implement #{@name} component */}"
                 end

          <<~TSX
            // #{@name}.tsx
            // Custom component - Edit this file to implement your component
            #{command_comment}
            import React from 'react';

            #{props_interface}

            export const #{@name}: React.FC<#{@name}Props> = (#{props_destructure}) => {
              return (
                <div className="#{to_kebab_case(@name)}">
                  #{body}
                </div>
              );
            };

            export default #{@name};
          TSX
        end

        def generate_props_interface
          is_container = @options[:is_container]
          lines = ["interface #{@name}Props {"]

          # Only include children prop if container mode
          lines << "  children?: React.ReactNode;" unless is_container == false
          lines << "  className?: string;"

          @options[:attributes].each do |key, type|
            ts_type = ruby_type_to_typescript(type)
            lines << "  #{key}?: #{ts_type};"
          end

          lines << "}"
          lines.join("\n")
        end

        def generate_props_destructure
          is_container = @options[:is_container]
          props = []

          # Only include children in destructure if container mode
          props << 'children' unless is_container == false
          props << 'className'
          props += @options[:attributes].keys

          "{ #{props.join(', ')} }"
        end

        def ruby_type_to_typescript(type)
          case type.downcase
          when 'string'
            'string'
          when 'int', 'integer', 'number', 'double', 'float'
            'number'
          when 'bool', 'boolean'
            'boolean'
          when 'array'
            'any[]'
          when 'object', 'hash'
            'Record<string, any>'
          else
            'any'
          end
        end

        def to_kebab_case(string)
          string
            .gsub(/([A-Z]+)([A-Z][a-z])/, '\1-\2')
            .gsub(/([a-z\d])([A-Z])/, '\1-\2')
            .downcase
        end
      end
    end
  end
end
