# frozen_string_literal: true

require 'fileutils'
require_relative '../../core/attribute_types'
require_relative '../../core/logger'
require_relative '../../core/converter_generator_core'

module RjuiTools
  module React
    module Generators
      class ReactComponentGenerator
        def initialize(name, options = {}, config = {}, command_line = nil)
          @name = name  # PascalCase name like CodeBlock
          @options = options
          @config = config
          @command_line = command_line
          @logger = Core::Logger
        end

        def generate
          @logger.info "Generating React component: #{@name}"

          # Said by the write itself, and only when it wrote: "Created" when
          # there was no file, "Overwrote" when it replaced one. The line used
          # to follow the call unconditionally, so a run that kept the file
          # (--skip-existing, "n", a closed stdin) printed "Skipped existing
          # …" and then "Created component file" for the same untouched file;
          # until 1.8.121 a replaced file was "Created" too.
          create_component_file
        end

        private

        def components_dir
          # Use extensions_directory from config, or default to src/components/extensions
          @config['extensions_directory'] || 'src/components/extensions'
        end

        def component_file_path
          File.join(components_dir, "#{@name}.tsx")
        end

        def create_component_file
          FileUtils.mkdir_p(components_dir)

          file_path = component_file_path

          # The converter core's one overwrite decision (JUI_SKIP_EXISTING /
          # --skip-existing keep, --force replaces, otherwise ask; a closed
          # stdin is "n"). This file kept its own copy of the same rules
          # until 1.8.113 — the same behaviour, a second place to drift.
          JsonUIShared::ConverterGeneratorCore.write_scaffold(
            file_path, @options, @logger, noun: 'component', label: 'component file', exists_label: 'Component file'
          ) { component_template }
        end

        def component_template
          props_interface = generate_props_interface
          props_destructure = generate_props_destructure
          is_container = @options[:is_container]

          command_comment = @command_line ? "// Generated by: #{@command_line}\n" : ''

          # Generate body based on container mode
          body = if is_container == false
                   # Force non-container mode
                   "{/* TODO: Implement #{@name} component */}"
                 else
                   # Container mode (auto-detect or forced)
                   "{children}\n          {/* TODO: Implement #{@name} component */}"
                 end

          <<~TSX
            // #{@name}.tsx
            // Custom component - Edit this file to implement your component
            #{command_comment}
            import React from 'react';

            #{props_interface}

            export const #{@name}: React.FC<#{@name}Props> = (#{props_destructure}) => {
              return (
                <div id={id} className="#{to_kebab_case(@name)}">
                  #{body}
                </div>
              );
            };

            export default #{@name};
          TSX
        end

        def generate_props_interface
          is_container = @options[:is_container]
          lines = ["interface #{@name}Props {"]

          # The converter emits id="..." whenever the layout node has one
          # (BaseConverter#build_id_attr), so the scaffold contract must
          # accept it.
          lines << '  id?: string;'
          # Only include children prop if container mode
          lines << "  children?: React.ReactNode;" unless is_container == false
          lines << "  className?: string;"

          @options[:attributes].each do |key, type|
            ts_type = ruby_type_to_typescript(type)
            lines << "  #{key}?: #{ts_type};"
          end

          lines << "}"
          lines.join("\n")
        end

        def generate_props_destructure
          is_container = @options[:is_container]
          props = ['id']

          # Only include children in destructure if container mode
          props << 'children' unless is_container == false
          props << 'className'
          props += @options[:attributes].keys

          "{ #{props.join(', ')} }"
        end

        # From the shared vocabulary (lib/core/attribute_types.rb), the table
        # sjui and kjui scaffold from. Until 1.8.121 a Long, a CGFloat, a Color,
        # `String?` or `[String]` became `any` here without a word (ticket
        # kjui-sjui-converter-attr-types-do-not-compile). `array`, `object`
        # and `hash` keep their old answers.
        def ruby_type_to_typescript(type)
          case type.to_s.strip.downcase
          when 'array' then 'any[]'
          when 'object', 'hash' then 'Record<string, any>'
          else JsonUIShared::AttributeTypes.ts_type(JsonUIShared::AttributeTypes.parse(type))
          end
        end

        def to_kebab_case(string)
          string
            .gsub(/([A-Z]+)([A-Z][a-z])/, '\1-\2')
            .gsub(/([a-z\d])([A-Z])/, '\1-\2')
            .downcase
        end
      end
    end
  end
end
