source 'https://rubygems.org'

gem 'json'
gem 'fileutils'
gem 'pathname'
gem 'optparse'
gem 'find'
gem 'nokogiri'
gem 'rexml'

group :test do
  gem 'rspec', '~> 3.12'
  gem 'simplecov', require: false
end
