# @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
# Source of truth: shared/core/attribute_definitions.json
# Regenerate: jui generate attr-bindings --lang ruby
# frozen_string_literal: true

module JsonUI
  module Generated
    # `@{expr}` binding pattern (multiline-safe, anchored).
    BINDING_PATTERN = /\A@\{(.+)\}\z/m.freeze

    # Static value or `@{binding}` expression for a binding-capable
    # attribute (Ruby counterpart of Swift/Kotlin `AttrValue<T>`).
    class AttrValue
      attr_reader :value, :binding_expression

      def initialize(value: nil, binding_expression: nil)
        @value = value
        @binding_expression = binding_expression
      end

      def binding?
        !@binding_expression.nil?
      end

      def ==(other)
        other.is_a?(AttrValue) &&
          other.value == value &&
          other.binding_expression == binding_expression
      end
    end

    # Warning hook — generated extractors never raise on malformed input.
    # Unknown enum values / dimension keywords are reported here and
    # extracted as nil.
    module AttrWarnings
      class << self
        attr_accessor :handler
      end

      def self.emit(message)
        handler&.call(message)
      end
    end

    # Coercion engine shared by all generated `extract` methods.
    module AttrCoerce
      # Canonical-name lookup with alias fallback (aliases are resolved in
      # generated code so raw / non-normalized JSON keeps working).
      def self.lookup(hash, canonical, aliases)
        return hash[canonical] unless hash[canonical].nil?

        aliases.each do |alias_name|
          return hash[alias_name] unless hash[alias_name].nil?
        end
        nil
      end

      # `"@{expr}"` → `"expr"`; anything else → nil.
      def self.binding_expression(raw)
        return nil unless raw.is_a?(String)

        match = BINDING_PATTERN.match(raw)
        match && match[1]
      end

      def self.string(raw)
        raw.is_a?(String) ? raw : nil
      end

      def self.number(raw)
        raw.is_a?(Numeric) && !raw.is_a?(Complex) ? raw : nil
      end

      def self.boolean(raw)
        raw == true || raw == false ? raw : nil
      end

      def self.object(raw)
        raw.is_a?(Hash) ? raw : nil
      end

      def self.array(raw)
        raw.is_a?(Array) ? raw : nil
      end

      def self.enum(raw, allowed, context)
        s = string(raw)
        return nil if s.nil?
        return s if allowed.include?(s)

        AttrWarnings.emit("#{context}: unknown enum value '#{s}'")
        nil
      end

      # number | keyword union (width / height): numbers and known keyword
      # strings pass through; unknown keyword strings warn and become nil.
      def self.dimension(raw, keywords, context)
        n = number(raw)
        return n unless n.nil?
        s = string(raw)
        return nil if s.nil?
        return s if keywords.include?(s)

        AttrWarnings.emit("#{context}: unknown dimension keyword '#{s}'")
        nil
      end

      # Row table interpreter — rows are generated per component module.
      def self.extract_table(hash, attrs, component)
        out = {}
        attrs.each do |row|
          raw = lookup(hash, row[:name], row[:aliases] || [])
          next if raw.nil?

          value = coerce_row(raw, row, component)
          out[row[:name]] = value unless value.nil?
        end
        out
      end

      def self.coerce_row(raw, row, component)
        context = "#{component}.#{row[:name]}"
        if row[:bindable]
          expr = binding_expression(raw)
          return AttrValue.new(binding_expression: expr) if expr
        end

        value =
          case row[:kind]
          when :string, :color then string(raw)
          when :number then number(raw)
          when :boolean then boolean(raw)
          when :object then object(raw)
          when :array then array(raw)
          when :enum then enum(raw, row[:values], context)
          when :dimension then dimension(raw, row[:keywords], context)
          when :binding then binding_expression(raw) || string(raw)
          else raw # :any / :raw — accepted as-is
          end
        return nil if value.nil?

        row[:bindable] ? AttrValue.new(value: value) : value
      end
    end
  end
end
