# @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
# Source of truth: shared/core/attribute_definitions.json
# Regenerate: jui generate attr-bindings --lang ruby
# frozen_string_literal: true

require_relative 'attr_support'

module JsonUI
  module Generated
    # Attributes shared across all components (emitted once).
    module CommonAttributes
      # Declared-attribute rows — part of the public metadata
      # contract together with `rows` / `declared?` / `alias_map`
      # (see the directory README).
      ATTRS = [
        # Hide view
        { name: 'hidden', kind: :boolean, bindable: true }.freeze,
        # Unique identifier for the component
        { name: 'id', kind: :string }.freeze,
        # Click handler (camelCase) - binding only (@{functionName})
        { name: 'onClick', kind: :binding }.freeze,
        # Opacity/alpha value (0-1)
        { name: 'opacity', kind: :number, bindable: true, aliases: ['alpha'].freeze }.freeze,
        # Shadow configuration (string or object) [accepts: string | object]
        { name: 'shadow', kind: :raw }.freeze,
        # View visibility state (can be data binding)
        { name: 'visibility', kind: :enum, bindable: true, values: ['visible', 'invisible', 'gone'].freeze }.freeze,
        # Width (number, 'matchParent', 'wrapContent') - binding supported [required]
        { name: 'width', kind: :dimension, bindable: true, keywords: ['matchParent', 'wrapContent'].freeze }.freeze,
      ].freeze

      # Returns a Hash keyed by canonical attribute name.
      # `canonical_only: true` disables alias fallback for
      # L1-normalized input (aliases are already rewritten).
      def self.extract(hash, canonical_only: false)
        AttrCoerce.extract_table(hash, ATTRS, 'common',
                                 canonical_only: canonical_only)
      end

      # Canonical name => extraction row (common rows merged
      # first; component rows override on name collision).
      def self.rows
        @rows ||= AttrTable.build_rows(ATTRS)
      end

      # True when `key` is a declared canonical name or alias
      # spelling.
      def self.declared?(key)
        rows.key?(key) || alias_map.key?(key)
      end

      # Alias spelling => canonical attribute name.
      def self.alias_map
        @alias_map ||= AttrTable.build_alias_map(rows)
      end
    end
  end
end
