# @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
# Source of truth: shared/core/attribute_definitions.json
# Regenerate: jui generate attr-bindings --lang ruby
# frozen_string_literal: true

require_relative 'attr_support'
require_relative 'common_attributes'

module JsonUI
  module Generated
    # Typed attribute extraction for the `Label` component.
    # Overrides the common definition of: `shadow`.
    module LabelAttributes
      ATTRS = [
        # Two-way binding @{variable} [binding: two-way]
        { name: 'bind', kind: :binding }.freeze,
        # Label internal padding [DEPRECATED: Compose Text has no edgeInset; use padding* instead.]
        { name: 'edgeInset', kind: :number }.freeze,
        # Highlight color - hex string or color name from colors.json
        { name: 'highlightColor', kind: :string, aliases: ['hilightColor'].freeze }.freeze,
        # Partial text styling
        { name: 'partialAttributes', kind: :array }.freeze,
        # Label-specific shadow override (object only)
        { name: 'shadow', kind: :object }.freeze,
        # Text content (supports data binding)
        { name: 'text', kind: :string, bindable: true }.freeze,
        # Text transformation (legacy spellings kept for compat) [default: none]
        { name: 'textTransform', kind: :enum, values: ['none', 'wrap-reverse', 'Flow', 'flow'].freeze }.freeze,
        # Associated value
        { name: 'value', kind: :any }.freeze,
      ].freeze

      # Returns a Hash keyed by canonical attribute name.
      # Common attributes are merged first; component-level
      # definitions override on name collision.
      def self.extract(hash)
        out = CommonAttributes.extract(hash)
        out.merge!(AttrCoerce.extract_table(hash, ATTRS, 'Label'))
        out
      end
    end
  end
end
