#!/usr/bin/env ruby

require "fileutils"

module SjuiTools
  module UIKit
    module XcodeProject
      module Setup
        class AppDelegateSetup
          def initialize(project_file_path)
            @project_file_path = project_file_path
          end

          def add_hotloader_functionality
            puts "Adding HotLoader functionality to AppDelegate..."
            
            # AppDelegate.swiftファイルを探す
            # @project_file_pathが.xcodeprojかproject.pbxprojかを確認
            if @project_file_path.end_with?('.pbxproj')
              # project.pbxprojの場合は2階層上がプロジェクトディレクトリ
              project_dir = File.dirname(File.dirname(File.dirname(@project_file_path)))
            else
              # .xcodeprojディレクトリの場合は親ディレクトリがプロジェクトディレクトリ
              project_dir = File.dirname(@project_file_path)
            end
            
            app_delegate_path = find_app_delegate_file(project_dir)
            
            if app_delegate_path.nil?
              puts "Warning: Could not find AppDelegate.swift file. HotLoader functionality not added."
              return
            end

            puts "Updating AppDelegate: #{app_delegate_path}"
            
            # AppDelegate.swiftの内容を読み込む
            content = File.read(app_delegate_path)
            
            # この版の生成節（マーカー）が既に在るかだけを見る。
            # ⚠️ 2026-09-14 まではここが `content.include?("HotLoader.instance")` だった。
            # 旧生成物は必ずその文字列を含むので、**既に setup 済のプロジェクトには以後どんな変更も届かず**、
            # しかも "already exists" と成功の顔で印字されていた（scene 移行が構造的に配れない）。
            if current_region?(content)
              puts "HotLoader region is already up to date in AppDelegate"
              return
            end
            
            # AppDelegate.swiftにHotLoader機能を追加
            updated_content = add_hotloader_content(content)
            
            # ファイルに書き戻す
            File.write(app_delegate_path, updated_content)
            puts "HotLoader functionality added to AppDelegate successfully"
          end

          private

          def find_app_delegate_file(project_dir)
            # プロジェクトディレクトリから再帰的にAppDelegate.swiftを検索
            # ただし、DerivedData、Build、Pods、Carthageなどのディレクトリは除外
            app_delegate_files = Dir.glob("#{project_dir}/**/AppDelegate.swift").reject do |path|
              path.include?('DerivedData') || 
              path.include?('Build') || 
              path.include?('Pods') || 
              path.include?('Carthage') ||
              path.include?('.build') ||
              path.include?('node_modules')
            end
            
            # 最もプロジェクトルートに近いものを選択
            app_delegate_files.min_by { |path| path.split('/').length }
          end

          # 生成した節はマーカーで囲む。削除はこの区間だけを対象にし、
          # 区間の外側（消費側が書いた行）には一切触れない。
          # 区間は版を名乗る。ガードは「マーカーが在るか」でなく
          # 「**この版の**マーカーが在るか」を見る——版を上げた setup（例: 注入先を
          # SceneDelegate に移す変更）が、既に setup 済のプロジェクトに届くようにするため。
          # 版が古い区間は剥がして貼り直す（区間の外は触らない）。
          REGION_VERSION = 1
          MARKER_PREFIX  = "// sjui:hotloader:begin"
          MARKER_BEGIN   = "#{MARKER_PREFIX} v#{REGION_VERSION} — generated by `sjui setup`; この行から end までは再生成されます"
          MARKER_END     = "// sjui:hotloader:end"
          LIFECYCLE_METHODS = [
            ["applicationDidBecomeActive",   "true"],
            ["applicationDidEnterBackground", "false"],
            ["applicationWillTerminate",      "false"],
          ].freeze
          IF_DEBUG_LINE   = /\A\s*#if DEBUG\s*\z/
          ENDIF_LINE      = /\A\s*#endif\s*\z/
          HOTLOADER_LINE  = /\A\s*HotLoader\.instance\.isHotLoadEnabled\s*=\s*(?:true|false)\s*\z/
          VIEWCREATOR_LINE = /\A\s*UIViewCreator\.(?:prepare|copyResourcesToDocuments)\(\)\s*\z/

          # 「この版の区間が在る」= 何もしなくてよい。版が違えば貼り直す。
          def current_region?(content)
            content.include?(MARKER_BEGIN)
          end

          def marker_block(code_lines, indent)
            ([MARKER_BEGIN] + code_lines + [MARKER_END]).map { |l| "#{indent}#{l}\n" }.join
          end

          def add_hotloader_content(content)
            # import文を追加
            unless content.include?("import SwiftJsonUI")
              content = content.gsub(/^import UIKit/, "import UIKit\nimport SwiftJsonUI")
            end

            # 前版の生成物を落とす。マーカー区間 → 旧生成物（行単位）の順。
            content = strip_generated_regions(content)
            content = strip_legacy_hotloader_lines(content)

            content = add_hotloader_to_did_finish_launching(content)
            LIFECYCLE_METHODS.each do |name, enabled|
              content = ensure_lifecycle_block(content, name, enabled)
            end

            content
          end

          # マーカー区間だけを行単位で落とす（区間外は 1 バイトも触らない）
          def strip_generated_regions(content)
            out = []
            inside = false
            content.each_line do |line|
              if line.include?(MARKER_PREFIX)
                inside = true
                next
              end
              if line.include?(MARKER_END)
                inside = false
                next
              end
              out << line unless inside
            end
            out.join
          end

          # マーカーが無い旧生成物: 生成した行だけを行単位で剥がす。
          # ⚠️ 以前はここが正規表現でメソッド本文ごと削除しており、
          #   (1) 生成節の後ろにユーザーが足した行を巻き込み、
          #   (2) HotLoader 以外の `#if DEBUG` を持つメソッドでは閉じ括弧を残さず消して
          #       brace が -1 になりビルドが壊れた（初回 setup で到達する）。
          def strip_legacy_hotloader_lines(content)
            lines = content.lines
            out = []
            i = 0
            while i < lines.length
              line = lines[i]
              if line =~ IF_DEBUG_LINE && lines[i + 1].to_s =~ HOTLOADER_LINE && lines[i + 2].to_s =~ ENDIF_LINE
                i += 3
                next
              end
              # 単独で在る `UIViewCreator.*` は旧生成物が didFinishLaunching に書いた行なので落とす
              # （残すと再 setup で二重になる。変異で確認済み）。
              # ⚠️ 単独の `HotLoader.instance…` は**落とさない**: 三行組の外に在るそれは
              #   消費側が自分で書いた行でありうる。変異でこの枝を消しても腕が 1 本も
              #   赤くならず、検体を作って調べたら「冗長」ではなく「消してはいけない物を
              #   消す枝」だった（下の腕がその境界を守る）。
              if line =~ VIEWCREATOR_LINE
                i += 1
                next
              end
              out << line
              i += 1
            end
            out.join
          end

          # ⚠️ 「空になった旧メソッドを消す」処理は置かない。剥がした後に空で残っても
          #   ensure_lifecycle_block がその本体にマーカー区間を入れるので最終形は同じで、
          #   実測の差は空行 1 行だけだった（変異で殺せない＝冗長なコードを腕で守ることになる）。
          def add_hotloader_to_did_finish_launching(content)
            did_finish_pattern = /^([ \t]*)(func application\([^)]+didFinishLaunchingWithOptions[^{]*\{)[ \t]*\n/

            if (m = content.match(did_finish_pattern))
              body_indent = m[1] + "    "
              block = marker_block([
                "UIViewCreator.prepare()",
                "UIViewCreator.copyResourcesToDocuments()",
                "#if DEBUG",
                "HotLoader.instance.isHotLoadEnabled = true",
                "#endif",
              ], body_indent)
              content.sub(m[0], m[0] + block)
            else
              add_method_to_class_safely(content, generate_did_finish_launching_method)
            end
          end

          # 既にメソッドが在れば**本文を残したまま**先頭にマーカー区間を足す。
          # 無ければメソッドごと生成する。
          # ⚠️ 以前は「在れば何もしない」で、既存のライフサイクルメソッドを持つアプリでは
          #   HotLoader の on/off が黙って注入されないままだった。
          def ensure_lifecycle_block(content, method_name, enabled)
            pattern = /^([ \t]*)(func\s+#{method_name}\s*\([^)]*\)\s*\{)[ \t]*\n/
            if (m = content.match(pattern))
              block = marker_block(["#if DEBUG", "HotLoader.instance.isHotLoadEnabled = #{enabled}", "#endif"], m[1] + "    ")
              content.sub(m[0], m[0] + block)
            else
              add_method_to_class_safely(content, generate_lifecycle_method(method_name, enabled))
            end
          end

          def generate_lifecycle_method(method_name, enabled)
            <<~SWIFT.strip
              func #{method_name}(_ application: UIApplication) {
              #{marker_block(["#if DEBUG", "HotLoader.instance.isHotLoadEnabled = #{enabled}", "#endif"], "    ").chomp}
              }
            SWIFT
          end

          def generate_did_finish_launching_method
            <<~SWIFT.strip
              func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
              #{marker_block(["UIViewCreator.prepare()", "UIViewCreator.copyResourcesToDocuments()", "#if DEBUG", "HotLoader.instance.isHotLoadEnabled = true", "#endif"], "    ").chomp}
                  return true
              }
            SWIFT
          end

          def add_method_to_class_safely(content, method_code)
            # より安全なアプローチ：クラスの最後の行を見つけて追加
            lines = content.lines
            
            # 最後の非空行のインデックスを見つける
            last_content_index = -1
            lines.reverse_each.with_index do |line, reverse_index|
              if line.strip.length > 0
                last_content_index = lines.length - 1 - reverse_index
                break
              end
            end
            
            # クラスの終端 } を見つける
            class_end_index = nil
            (last_content_index..lines.length-1).each do |i|
              if lines[i] && lines[i].strip == "}"
                class_end_index = i
                break
              end
            end
            
            if class_end_index
              # メソッドを正しいインデントで整形
              formatted_lines = []
              method_code.lines.each do |line|
                if line.strip.empty?
                  formatted_lines << ""
                else
                  formatted_lines << "    #{line.chomp}"
                end
              end
              formatted_lines << ""  # 1行の空行のみ
              
              # クラス終端の前に挿入
              formatted_lines.reverse_each do |formatted_line|
                lines.insert(class_end_index, "#{formatted_line}\n")
              end
              
              lines.join
            else
              # クラス終端が見つからない場合はそのまま返す
              content
            end
          end
        end
      end
    end
  end
end

# コマンドライン実行
if __FILE__ == $0
  if ARGV.length != 1
    puts "Usage: ruby app_delegate_setup.rb <project_file_path>"
    puts "Example: ruby app_delegate_setup.rb /path/to/project.pbxproj"
    exit 1
  end

  project_file_path = ARGV[0]
  
  begin
    setup = SjuiTools::UIKit::XcodeProject::Setup::AppDelegateSetup.new(project_file_path)
    setup.add_hotloader_functionality
  rescue => e
    puts "Error: #{e.message}"
    exit 1
  end
end