#!/usr/bin/env ruby

require "fileutils"

module SjuiTools
  module UIKit
    module XcodeProject
      module Setup
        class AppDelegateSetup
          def initialize(project_file_path)
            @project_file_path = project_file_path
          end

          def add_hotloader_functionality
            puts "Adding HotLoader functionality to AppDelegate..."
            
            # AppDelegate.swiftファイルを探す
            # @project_file_pathが.xcodeprojかproject.pbxprojかを確認
            if @project_file_path.end_with?('.pbxproj')
              # project.pbxprojの場合は2階層上がプロジェクトディレクトリ
              project_dir = File.dirname(File.dirname(File.dirname(@project_file_path)))
            else
              # .xcodeprojディレクトリの場合は親ディレクトリがプロジェクトディレクトリ
              project_dir = File.dirname(@project_file_path)
            end
            
            app_delegate_path = find_app_delegate_file(project_dir)
            
            if app_delegate_path.nil?
              puts "Warning: Could not find AppDelegate.swift file. HotLoader functionality not added."
              return
            end

            puts "Updating AppDelegate: #{app_delegate_path}"
            
            # AppDelegate.swiftの内容を読み込む
            content = File.read(app_delegate_path)
            
            # この版の生成節（マーカー）が既に在るかだけを見る。
            # ⚠️ 2026-09-14 まではここが `content.include?("HotLoader.instance")` だった。
            # 旧生成物は必ずその文字列を含むので、**既に setup 済のプロジェクトには以後どんな変更も届かず**、
            # しかも "already exists" と成功の顔で印字されていた（scene 移行が構造的に配れない）。
            if current_region?(content) && scene_up_to_date?(project_dir)
              puts "HotLoader region is already up to date in AppDelegate"
              return
            end
            
            # AppDelegate.swiftにHotLoader機能を追加
            updated_content = add_hotloader_content(content)
            
            # ファイルに書き戻す
            File.write(app_delegate_path, updated_content)
            puts "HotLoader functionality added to AppDelegate successfully"

            # v2: on/off は scene 側。届かないときは**黙って AppDelegate に戻さない**
            # （戻すと、アプリが scene 化した後の再 setup で旧型に巻き戻り、
            #  消費側は壊れたことに気づけない）。
            update_scene_delegate(project_dir)
          end

          private

          def find_app_delegate_file(project_dir)
            # プロジェクトディレクトリから再帰的にAppDelegate.swiftを検索
            # ただし、DerivedData、Build、Pods、Carthageなどのディレクトリは除外
            app_delegate_files = Dir.glob("#{project_dir}/**/AppDelegate.swift").reject do |path|
              path.include?('DerivedData') || 
              path.include?('Build') || 
              path.include?('Pods') || 
              path.include?('Carthage') ||
              path.include?('.build') ||
              path.include?('node_modules')
            end
            
            # 最もプロジェクトルートに近いものを選択
            app_delegate_files.min_by { |path| path.split('/').length }
          end

          # 生成した節はマーカーで囲む。削除はこの区間だけを対象にし、
          # 区間の外側（消費側が書いた行）には一切触れない。
          # 区間は版を名乗る。ガードは「マーカーが在るか」でなく
          # 「**この版の**マーカーが在るか」を見る——版を上げた setup（例: 注入先を
          # SceneDelegate に移す変更）が、既に setup 済のプロジェクトに届くようにするため。
          # 版が古い区間は剥がして貼り直す（区間の外は触らない）。
          # v2 (2026-09-14): ライフサイクルの on/off は SceneDelegate 側へ移した。
          # iOS 27 SDK では scene ライフサイクル必須で、`application*` は呼ばれない。
          REGION_VERSION = 2
          MARKER_PREFIX  = "// sjui:hotloader:begin"
          MARKER_BEGIN   = "#{MARKER_PREFIX} v#{REGION_VERSION} — generated by `sjui setup`; この行から end までは再生成されます"
          MARKER_END     = "// sjui:hotloader:end"
          # AppDelegate 側（v1 まで注入していた先）。v2 では**注入せず、剥がすだけ**。
          APP_LIFECYCLE_METHODS = %w[
            applicationDidBecomeActive applicationDidEnterBackground applicationWillTerminate
          ].freeze
          # SceneDelegate 側（v2 の注入先）
          SCENE_LIFECYCLE_METHODS = [
            ["sceneDidBecomeActive",   "true"],
            ["sceneDidEnterBackground", "false"],
            ["sceneDidDisconnect",      "false"],
          ].freeze
          IF_DEBUG_LINE   = /\A\s*#if DEBUG\s*\z/
          ENDIF_LINE      = /\A\s*#endif\s*\z/
          HOTLOADER_LINE  = /\A\s*HotLoader\.instance\.isHotLoadEnabled\s*=\s*(?:true|false)\s*\z/
          VIEWCREATOR_LINE = /\A\s*UIViewCreator\.(?:prepare|copyResourcesToDocuments)\(\)\s*\z/

          # 「この版の区間が在る」= 何もしなくてよい。版が違えば貼り直す。
          def current_region?(content)
            content.include?(MARKER_BEGIN)
          end

          def marker_block(code_lines, indent)
            ([MARKER_BEGIN] + code_lines + [MARKER_END]).map { |l| "#{indent}#{l}\n" }.join
          end

          def add_hotloader_content(content)
            # import文を追加
            unless content.include?("import SwiftJsonUI")
              content = content.gsub(/^import UIKit/, "import UIKit\nimport SwiftJsonUI")
            end

            # 前版の生成物を落とす。マーカー区間 → 旧生成物（行単位）の順。
            content = strip_generated_regions(content)
            content = strip_legacy_hotloader_lines(content)

            content = add_hotloader_to_did_finish_launching(content)
            # v2: `application*` には注入しない。v1 の区間を剥がした結果 空になった
            # 生成メソッドだけを畳む（本文が 1 行でも残っていれば残す）。
            # ⚠️ この畳み込みは v1 では冗長だった（剥がした直後に同じメソッドへ
            #   注入し直していたので最終形が同じ）。注入先を scene に移した v2 で
            #   初めて効く——「冗長」の判定は版に紐づく。
            content = remove_emptied_app_lifecycle_methods(content)

            content
          end

          # マーカー区間だけを行単位で落とす（区間外は 1 バイトも触らない）
          def strip_generated_regions(content)
            out = []
            inside = false
            content.each_line do |line|
              if line.include?(MARKER_PREFIX)
                inside = true
                next
              end
              if line.include?(MARKER_END)
                inside = false
                next
              end
              out << line unless inside
            end
            out.join
          end

          # マーカーが無い旧生成物: 生成した行だけを行単位で剥がす。
          # ⚠️ 以前はここが正規表現でメソッド本文ごと削除しており、
          #   (1) 生成節の後ろにユーザーが足した行を巻き込み、
          #   (2) HotLoader 以外の `#if DEBUG` を持つメソッドでは閉じ括弧を残さず消して
          #       brace が -1 になりビルドが壊れた（初回 setup で到達する）。
          def strip_legacy_hotloader_lines(content)
            lines = content.lines
            out = []
            i = 0
            while i < lines.length
              line = lines[i]
              if line =~ IF_DEBUG_LINE && lines[i + 1].to_s =~ HOTLOADER_LINE && lines[i + 2].to_s =~ ENDIF_LINE
                i += 3
                next
              end
              # 単独で在る `UIViewCreator.*` は旧生成物が didFinishLaunching に書いた行なので落とす
              # （残すと再 setup で二重になる。変異で確認済み）。
              # ⚠️ 単独の `HotLoader.instance…` は**落とさない**: 三行組の外に在るそれは
              #   消費側が自分で書いた行でありうる。変異でこの枝を消しても腕が 1 本も
              #   赤くならず、検体を作って調べたら「冗長」ではなく「消してはいけない物を
              #   消す枝」だった（下の腕がその境界を守る）。
              if line =~ VIEWCREATOR_LINE
                i += 1
                next
              end
              out << line
              i += 1
            end
            out.join
          end

          # v1 の区間を剥がした結果、本文が空になった `application*` を畳む。
          # 本文に 1 行でも残っていれば消さない（消費側の処理を保つ）。
          def remove_emptied_app_lifecycle_methods(content)
            APP_LIFECYCLE_METHODS.each do |name|
              content = content.gsub(
                /^[ \t]*func\s+#{name}\s*\([^)]*\)\s*\{[ \t]*\n(?:[ \t]*\n)*[ \t]*\}[ \t]*\n(?:[ \t]*\n)?/,
                ""
              )
            end
            content
          end

          def add_hotloader_to_did_finish_launching(content)
            did_finish_pattern = /^([ \t]*)(func application\([^)]+didFinishLaunchingWithOptions[^{]*\{)[ \t]*\n/

            if (m = content.match(did_finish_pattern))
              body_indent = m[1] + "    "
              block = marker_block([
                "UIViewCreator.prepare()",
                "UIViewCreator.copyResourcesToDocuments()",
                "#if DEBUG",
                "HotLoader.instance.isHotLoadEnabled = true",
                "#endif",
              ], body_indent)
              content.sub(m[0], m[0] + block)
            else
              add_method_to_class_safely(content, generate_did_finish_launching_method)
            end
          end

          # 既にメソッドが在れば**本文を残したまま**先頭にマーカー区間を足す。
          # 無ければメソッドごと生成する。
          # ⚠️ 以前は「在れば何もしない」で、既存のライフサイクルメソッドを持つアプリでは
          #   HotLoader の on/off が黙って注入されないままだった。
          def ensure_lifecycle_block(content, method_name, enabled)
            pattern = /^([ \t]*)(func\s+#{method_name}\s*\([^)]*\)\s*\{)[ \t]*\n/
            if (m = content.match(pattern))
              block = marker_block(["#if DEBUG", "HotLoader.instance.isHotLoadEnabled = #{enabled}", "#endif"], m[1] + "    ")
              content.sub(m[0], m[0] + block)
            else
              add_method_to_class_safely(content, generate_lifecycle_method(method_name, enabled))
            end
          end

          def generate_lifecycle_method(method_name, enabled)
            <<~SWIFT.strip
              func #{method_name}(_ application: UIApplication) {
              #{marker_block(["#if DEBUG", "HotLoader.instance.isHotLoadEnabled = #{enabled}", "#endif"], "    ").chomp}
              }
            SWIFT
          end

          def generate_did_finish_launching_method
            <<~SWIFT.strip
              func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
              #{marker_block(["UIViewCreator.prepare()", "UIViewCreator.copyResourcesToDocuments()", "#if DEBUG", "HotLoader.instance.isHotLoadEnabled = true", "#endif"], "    ").chomp}
                  return true
              }
            SWIFT
          end

          # ── SceneDelegate 側（v2 の注入先）────────────────────────────────
          #
          # iOS 27 SDK は scene ライフサイクル必須で、`applicationDidBecomeActive`
          # などは呼ばれない。HotLoader の on/off をそこに置いたままにすると、
          # scene 化したアプリで**ホットリロードだけが黙って死ぬ**。
          SCENE_MISSING_WARNING =
            "Warning: SceneDelegate.swift が見つかりません。HotLoader の on/off を注入できません。" \
            "iOS 27 SDK では UIScene ライフサイクルが必須で、未採用のアプリは起動しません " \
            "(UIScene life cycle is required for apps built with this SDK)。" \
            "AppDelegate 側への注入には**戻しません**（戻すと scene 化後の再 setup で旧型に巻き戻ります）。"
          MANIFEST_MISSING_WARNING =
            "Warning: Info.plist に UIApplicationSceneManifest がありません。HotLoader の on/off を注入できません。" \
            "iOS 27 SDK では UIScene ライフサイクルが必須で、未採用のアプリは起動しません。" \
            "AppDelegate 側への注入には**戻しません**。"

          # 「注入が届いている」= scene 側にこの版の区間が在る。
          # ⚠️ 最初の実装は「SceneDelegate が無ければ最新扱い」で true を返していた。
          #   その結果、2 回目以降は早期 return で**警告が消え**、届いていないのに
          #   "already up to date" だけが出た——直そうとしている「成功の顔」そのもの。
          #   自分の腕（警告は毎回出る）が捕まえた。
          def scene_up_to_date?(project_dir)
            path = find_scene_delegate_file(project_dir)
            return false if path.nil? || !scene_manifest?(project_dir)

            current_region?(File.read(path))
          rescue StandardError
            false
          end

          def update_scene_delegate(project_dir)
            path = find_scene_delegate_file(project_dir)
            if path.nil?
              puts SCENE_MISSING_WARNING
              return :missing_file
            end
            unless scene_manifest?(project_dir)
              puts MANIFEST_MISSING_WARNING
              return :missing_manifest
            end

            content = File.read(path)
            unless content.include?("import SwiftJsonUI")
              content = content.gsub(/^import UIKit/, "import UIKit\nimport SwiftJsonUI")
            end
            content = strip_generated_regions(content)
            SCENE_LIFECYCLE_METHODS.each do |name, enabled|
              content = ensure_scene_block(content, name, enabled)
            end
            File.write(path, content)
            puts "HotLoader lifecycle hooks written to SceneDelegate: #{path}"
            :injected
          end

          def find_scene_delegate_file(project_dir)
            files = Dir.glob("#{project_dir}/**/SceneDelegate.swift").reject do |path|
              path.include?("DerivedData") || path.include?("Build") || path.include?("Pods") ||
                path.include?("Carthage") || path.include?(".build") || path.include?("node_modules") ||
                path.include?("Tests") || path.include?("UITests")
            end
            files.min_by { |path| path.split("/").length }
          end

          # scene 採用の判定は Info.plist の Manifest 有無で行う。
          # ⚠️ SceneDelegate.swift が在るだけでは足りない: Xcode のテンプレートは
          #   ファイルを置いたまま Manifest を消せる（その形は iOS 27 で起動しない）。
          def scene_manifest?(project_dir)
            plist = Dir.glob("#{project_dir}/**/Info.plist").reject do |path|
              path.include?("DerivedData") || path.include?("Build") || path.include?("Pods") ||
                path.include?("Carthage") || path.include?(".build") || path.include?("node_modules")
            end.min_by { |path| path.split("/").length }
            return false if plist.nil?

            File.read(plist).include?("UIApplicationSceneManifest")
          rescue StandardError
            false
          end

          def ensure_scene_block(content, method_name, enabled)
            pattern = /^([ \t]*)(func\s+#{method_name}\s*\([^)]*\)[^{]*\{)[ \t]*\n/
            if (m = content.match(pattern))
              block = marker_block(["#if DEBUG", "HotLoader.instance.isHotLoadEnabled = #{enabled}", "#endif"], m[1] + "    ")
              content.sub(m[0], m[0] + block)
            else
              add_method_to_class_safely(content, generate_scene_method(method_name, enabled))
            end
          end

          def generate_scene_method(method_name, enabled)
            arg = method_name == "sceneDidDisconnect" ? "_ scene: UIScene" : "_ scene: UIScene"
            <<~SWIFT.strip
              func #{method_name}(#{arg}) {
              #{marker_block(["#if DEBUG", "HotLoader.instance.isHotLoadEnabled = #{enabled}", "#endif"], "    ").chomp}
              }
            SWIFT
          end

          def add_method_to_class_safely(content, method_code)
            # より安全なアプローチ：クラスの最後の行を見つけて追加
            lines = content.lines
            
            # 最後の非空行のインデックスを見つける
            last_content_index = -1
            lines.reverse_each.with_index do |line, reverse_index|
              if line.strip.length > 0
                last_content_index = lines.length - 1 - reverse_index
                break
              end
            end
            
            # クラスの終端 } を見つける
            class_end_index = nil
            (last_content_index..lines.length-1).each do |i|
              if lines[i] && lines[i].strip == "}"
                class_end_index = i
                break
              end
            end
            
            if class_end_index
              # メソッドを正しいインデントで整形
              formatted_lines = []
              method_code.lines.each do |line|
                if line.strip.empty?
                  formatted_lines << ""
                else
                  formatted_lines << "    #{line.chomp}"
                end
              end
              formatted_lines << ""  # 1行の空行のみ
              
              # クラス終端の前に挿入
              formatted_lines.reverse_each do |formatted_line|
                lines.insert(class_end_index, "#{formatted_line}\n")
              end
              
              lines.join
            else
              # クラス終端が見つからない場合はそのまま返す
              content
            end
          end
        end
      end
    end
  end
end

# コマンドライン実行
if __FILE__ == $0
  if ARGV.length != 1
    puts "Usage: ruby app_delegate_setup.rb <project_file_path>"
    puts "Example: ruby app_delegate_setup.rb /path/to/project.pbxproj"
    exit 1
  end

  project_file_path = ARGV[0]
  
  begin
    setup = SjuiTools::UIKit::XcodeProject::Setup::AppDelegateSetup.new(project_file_path)
    setup.add_hotloader_functionality
  rescue => e
    puts "Error: #{e.message}"
    exit 1
  end
end