# frozen_string_literal: true

# Generated by: rjui g converter CodeBlock --attributes file:String,language:String,showPreview:Boolean

require_relative '../base_converter'

module RjuiTools
  module React
    module Converters
      module Extensions
        class CodeBlockConverter < BaseConverter
          def convert(indent = 2)
            class_name = build_class_name
            id_attr = build_id_attr

            file_value = json['file']
            language_value = json['language']
            showPreview_value = json['showPreview']

            # Build the component JSX
            props = []
            props << %(file="#{file_value}") if file_value
            props << %(language="#{language_value}") if language_value
            props << "showPreview={#{showPreview_value}}" unless showPreview_value.nil?
            props_str = props.empty? ? '' : " #{props.join(' ')}"

            # Auto-detect container based on children or child
            is_container = (json['children'] && !json['children'].empty?) || (json['child'] && !json['child'].empty?)

            if is_container
              children_jsx = convert_children(indent + 2)
              <<~JSX.chomp
                #{indent_str(indent)}<CodeBlock#{id_attr} className="#{class_name}"#{props_str}>
                #{children_jsx}
                #{indent_str(indent)}</CodeBlock>
              JSX
            else
              <<~JSX.chomp
                #{indent_str(indent)}<CodeBlock#{id_attr} className="#{class_name}"#{props_str} />
              JSX
            end
          end

          protected

          def build_class_name
            # Get base classes from parent (handles margins, padding, etc.)
            base_classes = super

            # Add component-specific classes
            classes = ['flex', 'flex-col']
            classes << base_classes unless base_classes.empty?

            classes.compact.reject(&:empty?).join(' ')
          end
        end
      end
    end
  end
end
