# frozen_string_literal: true

# Generated by: rjui g converter ComponentsSidebar

require_relative '../base_converter'

module RjuiTools
  module React
    module Converters
      module Extensions
        class ComponentsSidebarConverter < BaseConverter
          def convert(indent = 2)
            class_name = build_class_name
            id_attr = build_id_attr

            # No custom attributes

            # Build the component JSX
            props = []
            # No custom props
            props_str = props.empty? ? '' : " #{props.join(' ')}"

            <<~JSX.chomp
              #{indent_str(indent)}<ComponentsSidebar#{id_attr} className="#{class_name}"#{props_str} />
            JSX
          end

          protected

          def build_class_name
            classes = ['flex', 'flex-col']

            classes << TailwindMapper.map_width(json['width']) if json['width']
            classes << TailwindMapper.map_flex_grow(json['weight']) if json['weight']

            classes.compact.reject(&:empty?).join(' ')
          end
        end
      end
    end
  end
end
