# frozen_string_literal: true

require 'open3'
require 'tmpdir'
require 'json'
require 'fileutils'

# What `rjui g view / component / collection` print about each file, held to
# what happened on disk (a snapshot before and after each run), on a new
# project and on a run again over the same files with stdin closed. rjui was
# truthful here when the family was measured (1b80b5ba + the reporting
# fixes, 2026-09-26: "Created …" for what it wrote, "… already exists" and
# nothing more for what it kept); this pins it beside its counterparts on the
# other two tools. Ticket kjui-g-view-reports-what-it-did-not-do.
RSpec.describe 'what rjui g view / component / collection say they did, against the disk' do
  def tool_root
    File.expand_path('../..', __dir__)
  end

  # [label, mode, generate arguments]
  def self.commands
    [
      ['view', nil, %w[view home]],
      ['component', nil, %w[component Card]],
      ['collection', nil, %w[collection item_cell]]
    ]
  end

  # No rjui.config.json: rjui writes its defaults, as leaf_children_build_spec.rb.
  def project(dir, _mode)
    tool = File.join(dir, 'rjui_tools')
    FileUtils.mkdir_p(tool)
    %w[bin lib].each do |d|
      raise "could not copy #{d}" unless system('cp', '-RL', File.join(tool_root, d), tool)
    end
    FileUtils.mkdir_p(File.join(dir, 'src', 'Layouts'))
    tool
  end

  def snapshot(dir)
    Dir.glob(File.join(dir, '**', '*'), File::FNM_DOTMATCH).select { |f| File.file?(f) }
       .reject { |f| f.include?('/rjui_tools/') }
       .to_h { |f| [File.realpath(f), File.mtime(f)] }
  end

  def run_twice(mode, args)
    dir = Dir.mktmpdir('rjui_g_report')
    tool = project(dir, mode)
    %w[new again].map do |run|
      before = snapshot(dir)
      sleep 0.01
      said, = Open3.capture2e('ruby', File.join(tool, 'bin', 'rjui'), 'g', *args, chdir: dir, stdin_data: '')
      after = snapshot(dir)
      disk = after.to_h { |f, m| [f, !before.key?(f) ? :created : (before[f] == m ? :untouched : :rewritten)] }
      [run, said.gsub(/\e\[[0-9;]*m/, ''), disk, dir]
    end
  end

  before(:all) do
    @runs = self.class.commands.to_h { |label, mode, args| [label, run_twice(mode, args)] }
  end

  after(:all) { @runs.values.flatten(1).map(&:last).uniq.each { |dir| FileUtils.rm_rf(dir) } }

  # The file a line names (resolved in the project), or nil.
  def named_file(line, dir)
    token = line[%r{(?:/|\b)[\w./-]+\.(?:tsx|ts|json)\b}]
    return nil unless token

    full = File.expand_path(token, dir)
    File.exist?(full) ? File.realpath(full) : nil
  end

  def claim(line)
    case line
    when /\bKept\b|\bkept\b|Skipped existing|already exists|Unchanged/ then :untouched
    when /Overwrote|\(overwritten\)/ then :rewritten
    when /\bCreated\b|\(created\)|File created/ then :created
    end
  end

  def scaffold(disk)
    disk
  end

  it 'runs each command twice as it is meant to (the precondition): the first run creates files' do
    aggregate_failures do
      @runs.each do |label, ((_, said, disk, _), _)|
        expect(scaffold(disk).values).to include(:created), "#{label}: #{said}"
      end
    end
  end

  it 'says of each file what happened to it on disk' do
    checked = 0
    aggregate_failures do
      @runs.each do |label, runs|
        runs.each do |run, said, disk, dir|
          said.lines.each do |line|
            file = named_file(line, dir)
            want = claim(line)
            next unless file && want && disk.key?(file)

            checked += 1
            expect(disk[file]).to eq(want), "#{label} (#{run}): #{line.strip} — on disk #{disk[file]}"
          end
        end
      end
    end
    expect(checked).to be >= 8
  end

  it 'says nothing was generated by a run that wrote no scaffold file' do
    aggregate_failures do
      @runs.each do |label, runs|
        runs.each do |run, said, disk, _|
          next if scaffold(disk).values.any? { |s| s != :untouched }

          expect(said).not_to match(/Created |Successfully generated|^Generated |Files? created/),
                              "#{label} (#{run}): #{said}"
        end
      end
    end
  end
end
