# frozen_string_literal: true

require 'cli/commands/build'
require 'compose/compose_builder'
require 'compose/data_model_updater'
require 'fileutils'
require 'tmpdir'

# jui-build-leaves-native-generated-files-of-a-deleted-layout, Android face.
#
# The Compose build now clears what a deleted layout left by the rule the
# three faces share (lib/core/generated_orphans.rb; the rule's own arms are in
# sjui_tools/spec/core/generated_orphans_spec.rb). Here the Data model is
# @generated and is deleted. The GeneratedView is not deleted: this generator
# owns only its GENERATED_CODE block ("DO NOT EDIT between GENERATED_CODE
# markers") and keeps the rest as the scaffold left it, so it is named — as
# iOS, whose build rewrites the whole GeneratedView, does not need to.
RSpec.describe KjuiTools::CLI::Commands::Build do
  let(:build) { described_class.new }

  around do |example|
    Dir.mktmpdir('kjui-orphans') { |dir| @root = dir; example.run }
  end

  # A data directory away from the default, so an arm fails if the sweep
  # spelled the directory itself instead of asking the Data writer.
  let(:config) do
    {
      'source_directory' => 'src/main', 'layouts_directory' => 'assets/Layouts',
      'view_directory' => 'kotlin/views', 'viewmodel_directory' => 'kotlin/viewmodels',
      'data_directory' => 'kotlin/app/models', 'package_name' => 'com.example.probe'
    }
  end

  before do
    allow(KjuiTools::Core::ConfigManager).to receive(:load_config).and_return(config)
    allow(KjuiTools::Core::ProjectFinder).to receive(:get_full_source_path).and_return(@root)
    allow(KjuiTools::Core::Logger).to receive(:info)
    allow(KjuiTools::Core::Logger).to receive(:warn)
    write('src/main/assets/Layouts/home.json', '{"type": "View"}')
  end

  def write(rel, content = '')
    path = File.join(@root, rel)
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, content)
    path
  end

  def generated(rel)
    write(rel, "// ║  @generated AUTO-GENERATED FILE — DO NOT EDIT\n// ║  Source:    Layouts/x.json\n")
  end

  def generated_view(rel)
    write(rel, "package com.example.probe.views.gone\n\n// Generated by kjui_tools - DO NOT EDIT between GENERATED_CODE markers\n" \
               "@Composable\nfun GoneGeneratedView() {\n    // >>> GENERATED_CODE_START\n    // >>> GENERATED_CODE_END\n}\n")
  end

  def prune
    build.send(:prune_layout_orphans, KjuiTools::Compose::ComposeBuilder.new)
  end

  it "deletes a deleted layout's Data model and names it" do
    data = generated('src/main/kotlin/app/models/GoneData.kt')
    prune
    expect(File.exist?(data)).to be(false)
    expect(KjuiTools::Core::Logger).to have_received(:info).with('  - src/main/kotlin/app/models/GoneData.kt')
  end

  it 'keeps its GeneratedView and names it, with what to check before deleting it' do
    view = generated_view('src/main/kotlin/views/gone/GoneGeneratedView.kt')
    prune
    expect(File.exist?(view)).to be(true)
    expect(KjuiTools::Core::Logger).to have_received(:warn)
      .with("  - src/main/kotlin/views/gone/GoneGeneratedView.kt: #{JsonUIShared::GeneratedOrphans::WARNINGS[:block]}")
  end

  it 'keeps the hand-written View and ViewModel of that layout and names them' do
    generated('src/main/kotlin/app/models/GoneData.kt')
    view = write('src/main/kotlin/views/gone/GoneView.kt')
    viewmodel = write('src/main/kotlin/viewmodels/GoneViewModel.kt')
    prune
    expect(File.exist?(view) && File.exist?(viewmodel)).to be(true)
    expect(KjuiTools::Core::Logger).to have_received(:warn).with(a_string_starting_with('  - src/main/kotlin/views/gone/GoneView.kt: '))
    expect(KjuiTools::Core::Logger).to have_received(:warn).with(a_string_starting_with('  - src/main/kotlin/viewmodels/GoneViewModel.kt: '))
  end

  # The older marker this generator wrote before @generated: not the claim
  # the rule deletes on, so the file is named instead.
  it 'keeps a Data model that carries only the older marker, and names it' do
    old = write('src/main/kotlin/app/models/GoneStyleData.kt', "// Generated by kjui_tools - DO NOT EDIT\npackage x\n")
    prune
    expect(File.exist?(old)).to be(true)
    expect(KjuiTools::Core::Logger).to have_received(:warn)
      .with("  - src/main/kotlin/app/models/GoneStyleData.kt: #{JsonUIShared::GeneratedOrphans::WARNINGS[:unmarked]}")
  end

  describe 'boundaries — each one is kept' do
    it 'a @generated file outside the directory the config declares' do
      stray = generated('src/main/kotlin/app/data/GoneData.kt')
      prune
      expect(File.exist?(stray)).to be(true)
    end

    it 'the outputs of a layout that still exists' do
      live = generated('src/main/kotlin/app/models/HomeData.kt')
      prune
      expect(File.exist?(live)).to be(true)
      expect(KjuiTools::Core::Logger).not_to have_received(:info).with(/Pruned/)
    end
  end
end
