"""Every copyable `baseline update` recipe carries `--fail-on-moved`.

🔻 WHY A TEST AND NOT A SENTENCE. `--fail-on-moved` is `action="store_true"`,
so the default bake rewrites every changed picture and exits 0 — the command's
own help says "a regression that gets absorbed stops being a regression". The
only thing between that and the baseline was a reader getting to the end of a
long output. On 2026-09-15 a reader did not: `tail -5` showed three `unstable`
lines, and the two `MOVED` lines above them were classified by guess.

⚠️ THE FLAG WAS ALREADY IMPLEMENTED AND ALREADY DOCUMENTED — in a paragraph
about what it CANNOT hold to an exact match. It appeared nowhere a person
copies a command from. Adding it to the recipes is the whole fix; this test is
what stops the recipes drifting back, because prose has no gate and a recipe
that loses a flag loses it silently.

📌 The assertion is per-recipe and BY FILE, not a count. A count would let one
recipe gain the flag while another loses it.
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

#: Files that carry a `baseline update` line a person is meant to run, and how
#: many such lines each holds. Listing the count per file means a recipe that
#: is ADDED without the flag fails here rather than passing unnoticed.
RECIPE_FILES = {
    "conformance/baselines/README.md": 3,
    ".github/workflows/ci.yml": 1,
    "conformance/hosts/web/README.md": 1,
    "dev-guide/08-testing-conformance.md": 1,
}

#: Prose that merely NAMES the command ("@generated by `jui conformance
#: baseline update`") is not a recipe. A recipe names a platform, because the
#: argument is required — that is the discriminator, and it is the command's
#: own grammar rather than a guess about formatting.
RECIPE = re.compile(r"baseline update[^\n`]*--platform")


def _recipes(text: str) -> list[str]:
    """Each recipe as one logical line, shell continuations joined.

    A recipe is often split across lines with `\\`, and the flag may sit on
    either half — matching per physical line would report a false failure for
    a recipe that is in fact correct.
    """
    joined = re.sub(r"\\\s*\n\s*(?:#\s*)?", " ", text)
    return [m.group(0) for m in re.finditer(r"baseline update[^\n`]*", joined) if "--platform" in m.group(0)]


class EveryBakeRecipeForcesTheReview(unittest.TestCase):

    def test_every_recipe_carries_the_flag(self):
        for rel, expected in sorted(RECIPE_FILES.items()):
            path = REPO / rel
            self.assertTrue(path.is_file(), f"{rel} is gone — update this test with it")
            found = _recipes(path.read_text())
            self.assertEqual(
                len(found), expected,
                f"{rel}: expected {expected} bake recipe(s), found {len(found)}. "
                "A new recipe must be added to RECIPE_FILES with the flag, not "
                "left out of the count.",
            )
            for r in found:
                self.assertIn(
                    "--fail-on-moved", r,
                    f"{rel}: a bake recipe without --fail-on-moved — "
                    f"it would rewrite every changed picture and exit 0: {r!r}",
                )

    def test_the_flag_the_recipes_name_still_exists(self):
        """🔑 The recipes are only worth pinning while the flag is real.

        Without this, renaming the option leaves four documents telling people
        to pass a flag the CLI rejects, and this file would still be green —
        it would be checking that the docs agree with each other.
        """
        src = (REPO / "jui_tools/jui_cli/commands/conformance_cmd.py").read_text()
        self.assertIn('"--fail-on-moved"', src)
        self.assertIn("if fail_on_moved and summary.moved:", src,
                      "the flag is declared but nothing acts on it")

    def test_the_flag_is_still_opt_in_which_is_why_the_recipes_matter(self):
        """The reason this test exists, asserted rather than narrated.

        If the default ever becomes fail-on-moved, the recipes stop being the
        thing that forces the review and this whole file can go.
        """
        src = (REPO / "jui_tools/jui_cli/commands/conformance_cmd.py").read_text()
        block = src[src.index('"--fail-on-moved"'):]
        self.assertIn('action="store_true"', block[:400],
                      "the flag is no longer opt-in — re-read whether these "
                      "recipes still need to name it")


if __name__ == "__main__":
    unittest.main()
