"""Every `baseline update` recipe in the tree carries `--fail-on-moved`.

🔻 WHY THE FLAG MATTERS. `--fail-on-moved` is `action="store_true"`, so the
default bake rewrites every changed picture and exits 0 — the command's own
help says "a regression that gets absorbed stops being a regression". The only
thing between that and the baseline was a reader reaching the end of a long
output. On 2026-09-15 a reader did not: `tail -5` showed three `unstable`
lines, and the two `MOVED` lines above them were classified by guess.

⚠️ The bake was NOT failing to classify — it prints `MOVED` and `unstable` with
separate words and separate counters. What was missing is that a long, correct
output exits 0. The flag turns it into a stop.

🔑 THE POPULATION IS DERIVED, NOT LISTED, AND THAT IS THE WHOLE DESIGN.
The first version of this file named four files and asserted a recipe count in
each. Its own docstring claimed a recipe "ADDED without the flag fails here" —
true only INSIDE those four. A peer lane ran the same predicate over
`git ls-files` and found SEVEN files matching, three of them unscanned, one of
which was the heaviest site in the repo (a runtime error string handing the
operator a re-bake command at the exact moment before a bake). A
hand-maintained population moves the maintenance up one level; it does not
remove it. So the root here is the tracked tree, the same property
`visual_stability` gives its set by deriving it from declarations: a new file
of the same shape joins without anyone maintaining a list, and a match that
should NOT carry the flag arrives as a NAMED REFUSAL rather than as silence.
"""

from __future__ import annotations

import re
import subprocess
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

#: A recipe names a platform, because `--platform` is required. That is the
#: command's own grammar, not a guess about formatting — prose that merely
#: NAMES the command ("@generated by `jui conformance baseline update`") is
#: not something anyone runs.
RECIPE = re.compile(r"baseline update[^\n`]*")

#: Matches that must NOT carry the flag, each with the reason. An entry here is
#: a decision on the record; an unlisted match without the flag is a failure.
#: 🔑 The reason is REQUIRED, because "add it to the exemption list" must cost
#: more than "add the flag" — otherwise the exemption list becomes the escape
#: hatch that empties this test.
EXEMPT: dict[str, str] = {
    "jui_tools/jui_cli/commands/conformance_cmd.py":
        "the argparse usage synopsis printed on a bad subcommand "
        "(`... --platform <ios|android|web> [options]`). A synopsis names the "
        "REQUIRED arguments and collapses the rest into [options]; listing one "
        "optional flag there would start a list that can only go stale.",
}


def recipes_in(text: str) -> list[str]:
    """Each recipe as one logical line, shell continuations joined.

    A recipe is often split with a trailing `\\`, and the flag may sit on
    either half — matching per physical line reports a false failure for a
    recipe that is in fact correct. YAML/py comment leaders on the joined
    line are dropped for the same reason.
    """
    joined = re.sub(r"\\\s*\n\s*(?:#\s*)?", " ", text)
    return [m.group(0) for m in RECIPE.finditer(joined) if "--platform" in m.group(0)]


def tracked_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True
    ).stdout.split("\n")
    return [f for f in out if f]


def _scan() -> dict[str, list[str]]:
    found: dict[str, list[str]] = {}
    for rel in tracked_files():
        path = REPO / rel
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue  # binaries and unreadable blobs carry no recipe
        hits = recipes_in(text)
        if hits:
            found[rel] = hits
    return found


class EveryBakeRecipeForcesTheReview(unittest.TestCase):

    def test_every_recipe_in_the_tree_carries_the_flag(self):
        found = _scan()
        offenders = []
        for rel, hits in sorted(found.items()):
            if rel in EXEMPT:
                continue
            for r in hits:
                if "--fail-on-moved" not in r:
                    offenders.append(f"{rel}: {r.strip()!r}")
        self.assertEqual(
            offenders, [],
            "bake recipe(s) without --fail-on-moved — each would rewrite every "
            "changed picture and exit 0. Add the flag, or add the file to "
            "EXEMPT with a reason saying why this site must not carry it:\n  "
            + "\n  ".join(offenders),
        )

    def test_the_scan_actually_reached_the_tree(self):
        """🔻 An empty scan satisfies the assertion above and proves nothing.

        `git ls-files` returning nothing, a cwd mistake, or a predicate that
        stops matching would each make this file green while checking no
        recipes at all — the shape that has already produced a false "they
        agree" in this repo today.
        """
        found = _scan()
        self.assertGreaterEqual(len(tracked_files()), 100, "the tree scan found almost nothing")
        self.assertGreaterEqual(
            sum(len(v) for v in found.values()), 5,
            f"only {sum(len(v) for v in found.values())} recipe(s) matched — the "
            "predicate has probably stopped matching, not the recipes stopped existing",
        )

    def test_every_exemption_is_still_a_real_match(self):
        """An exemption for a site that no longer matches is a stale licence.

        Left in place it would silently cover a DIFFERENT recipe if one later
        appeared in the same file.
        """
        found = _scan()
        stale = [rel for rel in EXEMPT if rel not in found]
        self.assertEqual(stale, [], f"EXEMPT names file(s) with no recipe any more: {stale}")
        for rel, reason in EXEMPT.items():
            self.assertGreater(len(reason), 60, f"{rel}: an exemption needs a reason, not a label")

    def test_the_flag_the_recipes_name_still_exists(self):
        """🔑 The recipes are only worth pinning while the flag is real.

        Without this, renaming the option leaves every document telling people
        to pass a flag the CLI rejects, and this file would still be green —
        it would be checking that the docs agree with each other.
        """
        src = (REPO / "jui_tools/jui_cli/commands/conformance_cmd.py").read_text()
        self.assertIn('"--fail-on-moved"', src)
        self.assertIn("if fail_on_moved and summary.moved:", src,
                      "the flag is declared but nothing acts on it")

    def test_the_flag_is_still_opt_in_which_is_why_the_recipes_matter(self):
        """If the default ever becomes fail-on-moved, the recipes stop being
        the thing that forces the review and this whole file can go."""
        src = (REPO / "jui_tools/jui_cli/commands/conformance_cmd.py").read_text()
        block = src[src.index('"--fail-on-moved"'):]
        self.assertIn('action="store_true"', block[:400],
                      "the flag is no longer opt-in — re-read whether these "
                      "recipes still need to name it")

    def test_the_runtime_instruction_carries_it_too(self):
        """🔴 The site no document can cover, pinned by name.

        `baseline.py` hands the operator a re-bake command when a comparison
        stops on an env mismatch — the moment immediately before a bake, to
        the reader who is following the tool rather than the README. The
        general scan above would catch this too; it is named separately
        because losing THIS one is not the same size of mistake as losing a
        line in a schema document.
        """
        src = (REPO / "jui_tools/jui_cli/conformance/baseline.py").read_text()
        self.assertIn("re-bake with `jui conformance baseline update", src,
                      "the env-mismatch instruction is gone — re-read this test")
        for r in recipes_in(src):
            self.assertIn("--fail-on-moved", r, f"runtime instruction lost the flag: {r!r}")


if __name__ == "__main__":
    unittest.main()
