"""``jui conformance compat-doc`` — generate the attribute compatibility doc.

Replaces the hand-maintained ``attribute_compatibility.md`` style documents
with an ``@generated`` markdown rendered from the two live sources of truth:

- ``shared/core/attribute_definitions.json`` — canonical names, aliases,
  types, deprecations (per component + ``common``)
- ``conformance/manifest.json`` + ``results/<platform>.results.json`` —
  per-attribute conformance coverage measured on the platform's dynamic host

Output is deterministic: same inputs produce byte-identical markdown.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class CompatDocSummary:
    out_path: Path
    components: int = 0
    attributes: int = 0
    covered: int = 0  # attributes with >=1 fixture for the platform
    warnings: list = field(default_factory=list)


def _fmt_type(t) -> str:
    if isinstance(t, list):
        return " \\| ".join(str(x) for x in t)
    return str(t) if t is not None else ""


def _fmt_aliases(a) -> str:
    if not a:
        return ""
    if isinstance(a, list):
        return ", ".join(f"`{x}`" for x in a)
    return f"`{a}`"


def _attr_rows(defs: dict) -> dict:
    """component -> sorted list of (attr, attr_def dict)."""
    out = {}
    for component, attrs in sorted(defs.items()):
        if not isinstance(attrs, dict):
            continue
        rows = [
            (name, d)
            for name, d in sorted(attrs.items())
            if isinstance(d, dict)
        ]
        if rows:
            out[component] = rows
    return out


def _coverage_index(manifest: dict, results: dict) -> dict:
    """(component, attribute) -> {status -> count} for the platform results."""
    status_by_id = {r["id"]: r.get("status", "unknown") for r in results.get("results", [])}
    cov: dict = {}
    for fx in manifest.get("fixtures", []):
        key = (fx.get("component", ""), fx.get("attribute", ""))
        status = status_by_id.get(fx.get("id"))
        if status is None:
            continue
        cov.setdefault(key, {})
        cov[key][status] = cov[key].get(status, 0) + 1
    return cov


def _rollup(counts: dict) -> str:
    if not counts:
        return "—"
    total = sum(counts.values())
    passed = counts.get("pass", 0)
    skipped = counts.get("skipped", 0)
    failed = total - passed - skipped
    if failed:
        return f"❌ {passed}/{total} pass ({failed} fail/error)"
    if passed and skipped:
        return f"✅ {passed} pass / {skipped} skipped"
    if passed:
        return f"✅ {passed} pass"
    return f"⏭ {skipped} skipped"


def generate_compat_doc(
    definitions_path: Path,
    conformance_dir: Path,
    platform: str,
    out_path: Path,
) -> CompatDocSummary:
    defs = json.loads(Path(definitions_path).read_text())
    manifest_path = conformance_dir / "manifest.json"
    results_path = conformance_dir / "results" / f"{platform}.results.json"

    manifest = json.loads(manifest_path.read_text()) if manifest_path.is_file() else {}
    results = json.loads(results_path.read_text()) if results_path.is_file() else {}

    summary = CompatDocSummary(out_path=out_path)
    if not manifest:
        summary.warnings.append(f"manifest not found: {manifest_path} — coverage column omitted")
    if not results:
        summary.warnings.append(f"results not found: {results_path} — coverage column omitted")

    cov = _coverage_index(manifest, results) if manifest and results else {}
    components = _attr_rows(defs)

    lines: list = []
    lines.append("<!-- @generated by `jui conformance compat-doc` — DO NOT EDIT.")
    lines.append("     Regenerate:")
    lines.append(f"       jui conformance compat-doc --platform {platform} -o <this file>")
    lines.append("     Sources: shared/core/attribute_definitions.json (canonical names,")
    lines.append("     aliases, types, deprecations) + conformance manifest/results")
    lines.append(f"     ({platform} dynamic host measurements). -->")
    lines.append("")
    lines.append("# JsonUI Attribute Compatibility")
    lines.append("")
    lines.append("Canonical attribute names, their aliases, and per-attribute conformance")
    lines.append(f"coverage measured on the **{platform}** dynamic host. The single source")
    lines.append("of truth for attribute semantics is `shared/core/attribute_definitions.json`;")
    lines.append("mode-specific implementation notes formerly maintained by hand in this")
    lines.append("document are superseded by that file plus the conformance suite.")
    lines.append("")

    for component, rows in components.items():
        lines.append(f"## {component}")
        lines.append("")
        lines.append("| attribute | aliases | type | deprecated | conformance |")
        lines.append("|---|---|---|---|---|")
        for name, d in rows:
            summary.attributes += 1
            counts = cov.get((component, name), {})
            if counts:
                summary.covered += 1
            deprecated = "yes" if d.get("deprecated") else ""
            lines.append(
                f"| `{name}` | {_fmt_aliases(d.get('aliases'))} | "
                f"{_fmt_type(d.get('type'))} | {deprecated} | {_rollup(counts)} |"
            )
        lines.append("")
        summary.components += 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    return summary
