import React, { Suspense } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
// Generated by scripts/generate.mjs — run `npm run generate` before typechecking.
import { fixtures } from './generated/fixtureRegistry';

type RegistryEntry = {
  component: React.LazyExoticComponent<React.ComponentType>;
};

const registry: Record<string, RegistryEntry> = fixtures;

function FixtureIndex() {
  const ids = Object.keys(registry).sort();
  return (
    <div id="fixture_index" style={{ padding: 16, fontFamily: 'monospace' }}>
      <h1>JsonUI Web Conformance Host — {ids.length} fixtures</h1>
      <ul>
        {ids.map((id) => (
          <li key={id}>
            <a href={`/fixture/${id}`}>{id}</a>
          </li>
        ))}
      </ul>
    </div>
  );
}

function FixtureHost() {
  const path = decodeURIComponent(window.location.pathname);
  const match = path.match(/^\/fixture\/(.+)$/);
  if (!match) {
    return <FixtureIndex />;
  }
  const id = match[1];
  const entry = registry[id];
  if (!entry) {
    return <div id="fixture_error">Unknown fixture: {id}</div>;
  }
  const Component = entry.component;
  return (
    <Suspense fallback={<div id="fixture_loading" />}>
      <Component />
    </Suspense>
  );
}

createRoot(document.getElementById('app-root')!).render(<FixtureHost />);
