"""Web (TypeScript / ReactJsonUI) file generator.

Output layout follows the rjui convention:

    {generated_viewmodels_directory}/{Name}ViewModelBase.ts   (autogen)
    {viewmodels_directory}/{Name}ViewModel.ts                 (user impl)
    src/repository/{Name}Repository.ts                        (single file)
    src/usecase/{Name}UseCase.ts                              (single file)

Unlike iOS/Android there is no separate protocol/interface file —
``has_separate_protocol = False`` signals to generate_cmd.py that
protocol generation should be skipped.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ..core.spec_extractor import (
    ScreenSpec, RepositoryDef, UseCaseDef, MethodDef,
)
from ..core.type_mapper import TypeMapper
from ..core.generated_marker import comment_header, comment_footer
from ..core.spec_validator import SpecWarning, resolve_platforms


# Component types whose event attributes land as optional function props in
# the rjui-generated <Name>Data interface even without a `data` declaration
# (mirrors rjui_tools data_model_generator.rb extract_event_handler_bindings).
_EVENT_HANDLER_ATTRS: dict[str, tuple[str, ...]] = {
    "Switch": ("onValueChange",),
    "Toggle": ("onValueChange",),
    "Slider": ("onValueChange",),
    "Radio": ("onValueChange",),
    "Segment": ("onValueChange",),
    "SelectBox": ("onValueChanged", "onChange"),
    "TextView": ("onTextChange", "onChange"),
}


def resolve_layout_path(layouts_dir: Path, spec: ScreenSpec) -> Path:
    """Map a spec to its Layout JSON path (metadata.layoutFile or snake name)."""
    layout_file = spec.layout_file or _to_snake(spec.name)
    name = layout_file if layout_file.endswith(".json") else f"{layout_file}.json"
    return layouts_dir / name


def collect_layout_event_names(layout_path: Path) -> set[str] | None:
    """Collect names that exist as members of the rjui <Name>Data interface.

    ``<Name>Data`` is generated by rjui from the Layout JSON, so only
    handlers present there may appear in the ViewModelBase
    ``initializeEventHandlers`` ``updateData`` literal — anything else is
    a TS2353. Returns None when the layout can't be read (callers fall
    back to initializing every spec method).
    """
    try:
        data = json.loads(layout_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    names: set[str] = set()
    _collect_data_member_names(data, names)
    return names


def _binding_name(value: object) -> str | None:
    if isinstance(value, str) and value.startswith("@{") and value.endswith("}"):
        return value[2:-1]
    return None


def _collect_data_member_names(node: object, names: set[str]) -> None:
    if isinstance(node, dict):
        data_section = node.get("data")
        if isinstance(data_section, list):
            for entry in data_section:
                if isinstance(entry, dict) and isinstance(entry.get("name"), str):
                    names.add(entry["name"])
        # `onclick` selector strings become optional function props verbatim.
        onclick = node.get("onclick")
        if isinstance(onclick, str) and onclick:
            names.add(onclick)
        comp = node.get("type")
        for attr in _EVENT_HANDLER_ATTRS.get(comp, ()):  # type: ignore[arg-type]
            bound = _binding_name(node.get(attr))
            if bound:
                names.add(bound)
        # TextField text binding without an explicit handler derives an
        # on<X>Change prop in Data.
        if comp == "TextField":
            bound = _binding_name(node.get("text"))
            if bound and not node.get("onTextChange") and not node.get("onChange"):
                names.add(f"on{bound[:1].upper()}{bound[1:]}Change")
        for value in node.values():
            _collect_data_member_names(value, names)
    elif isinstance(node, list):
        for item in node:
            _collect_data_member_names(item, names)


class WebGenerator:
    """Generates TypeScript files for ReactJsonUI projects."""

    has_separate_protocol = False

    def __init__(self, root: Path, config: dict, type_mapper: TypeMapper):
        self._root = root
        self._config = config
        self._type_mapper = type_mapper
        rjui_config = self._load_rjui_config()
        self._generated_vm_dir = root / rjui_config.get(
            "generated_viewmodels_directory", "src/generated/viewmodels"
        )
        self._impl_vm_dir = root / rjui_config.get(
            "viewmodels_directory", "src/viewmodels"
        )
        self._data_import_base = rjui_config.get(
            "data_directory", "src/generated/data"
        ).replace("src/", "@/")
        self._generated_vm_import_base = rjui_config.get(
            "generated_viewmodels_directory", "src/generated/viewmodels"
        ).replace("src/", "@/")
        self._repo_dir = root / "src" / "repository"
        self._usecase_dir = root / "src" / "usecase"
        #: Findings raised while emitting, drained by the caller onto the
        #: build's warning stream. One generator serves every screen of a
        #: platform, so this accumulates across the run.
        self.warnings: list[SpecWarning] = []

    def _load_rjui_config(self) -> dict:
        """Read rjui.config.json if present."""
        rjui_config = self._root / "rjui.config.json"
        if rjui_config.exists():
            try:
                return json.loads(rjui_config.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                pass
        return {}

    # --- Path helpers ---

    def viewmodel_protocol_path(self, name: str, subdir: str = "") -> Path:
        """Path of the auto-generated base class (regenerated every build)."""
        base = self._generated_vm_dir
        if subdir:
            base = base / _subdir_to_pascal(subdir)
        return base / f"{name}ViewModelBase.ts"

    def viewmodel_impl_path(self, name: str, subdir: str = "") -> Path:
        """Path of the user-authored implementation (never overwritten)."""
        base = self._impl_vm_dir
        if subdir:
            base = base / _subdir_to_pascal(subdir)
        return base / f"{name}ViewModel.ts"

    def repository_protocol_path(self, name: str) -> Path:
        """Web doesn't split protocol/impl — return the impl path."""
        return self.repository_impl_path(name)

    def repository_impl_path(self, name: str) -> Path:
        return self._repo_dir / f"{name}.ts"

    def usecase_protocol_path(self, name: str) -> Path:
        return self.usecase_impl_path(name)

    def usecase_impl_path(self, name: str) -> Path:
        return self._usecase_dir / f"{name}.ts"

    # --- ViewModel ---

    def generate_viewmodel_protocol(
        self,
        spec: ScreenSpec,
        impl_source: str | None = None,  # web ignores impl markers — accepted for signature parity
        layout_event_names: set[str] | None = None,
    ) -> str:
        """Generate the ViewModel base class (auto-regenerated).

        ``dataFlow.viewModel.methods`` entries whose ``platforms`` excludes
        ``"web"`` are filtered out. Non-observable ``vars`` (those the Impl
        wants on the Base directly) are emitted as public fields;
        observable vars live inside ``<Name>Data`` and aren't re-emitted.

        Marker blocks (``@jui:protocol``) are not consulted for Web — the
        Base has a fixed ``getter + initializeEventHandlers`` shape.
        """
        del impl_source  # noqa — documented; web is spec-only.

        data_type = f"{spec.name}Data"
        vm = spec.view_model
        web_methods = [
            m for m in vm.methods
            if not m.platforms or "web" in m.platforms
        ]
        web_vars_base = [
            v for v in vm.vars
            if "web" in resolve_platforms(v.platforms) and not v.observable
        ]

        # `updateData` takes Partial<XxxData>, and XxxData only contains
        # layout-derived members — spec-only methods (lifecycle/fetch
        # helpers, cell handlers) are plain subclass methods and writing
        # them into the literal is a TS2353. When the layout is unknown
        # (layout_event_names is None) fall back to initializing all.
        init_methods = web_methods
        if layout_event_names is not None:
            init_methods = [
                m for m in web_methods if m.name in layout_event_names
            ]
        event_defaults = "\n".join(
            f"      {m.name}: () => {{}}," for m in init_methods
        )
        event_body = event_defaults if event_defaults else "      // no methods declared"

        header = comment_header(
            source=f"docs/screens/json/{_to_snake(spec.name)}.spec.json",
            generator="jui build",
        )
        # Collect extra TS imports for custom types used in non-observable
        # vars. TypeMapper's `imports` hint carries per-type module paths
        # (e.g. ``"imports": ["@/types/ItemImage"]``).
        seen_imports: set[str] = set()
        extra_import_lines: list[str] = []
        for v in web_vars_base:
            for line in self._import_lines(v.type):
                if line in seen_imports:
                    continue
                seen_imports.add(line)
                extra_import_lines.append(line)

        lines = [
            header,
            "",
            'import { AppRouterInstance } from "next/dist/shared/lib/app-router-context.shared-runtime";',
            f'import {{ {data_type} }} from "{self._data_import_base}/{data_type}";',
            *extra_import_lines,
            "",
            f"export class {spec.name}ViewModelBase {{",
            "  protected router: AppRouterInstance;",
            f"  protected _getData: () => {data_type};",
            f"  protected _setData: (data: {data_type} | ((prev: {data_type}) => {data_type})) => void;",
        ]
        # Non-observable vars emitted as public fields on the Base class.
        # Observable vars live inside <Name>Data (uiVariables handle that).
        for v in web_vars_base:
            lines.append(self._var_base_declaration(v, spec.name))
        lines += [
            "",
            f"  get data(): {data_type} {{",
            "    return this._getData();",
            "  }",
            "",
            "  constructor(",
            "    router: AppRouterInstance,",
            f"    getData: () => {data_type},",
            f"    setData: (data: {data_type} | ((prev: {data_type}) => {data_type})) => void",
            "  ) {",
            "    this.router = router;",
            "    this._getData = getData;",
            "    this._setData = setData;",
            "  }",
            "",
            "  // Update data and trigger re-render",
            f"  updateData = (updates: Partial<{data_type}>) => {{",
            "    this._setData((prev) => ({ ...prev, ...updates }));",
            "  };",
            "",
            "  // Set external variables (e.g., route params, props from parent)",
            f"  setVars = (vars: Partial<{data_type}>) => {{",
            "    this.updateData(vars);",
            "  };",
            "",
            "  // Initialize event handlers — call this in subclass constructor",
            "  protected initializeEventHandlers = () => {",
            "    this.updateData({",
            event_body,
            "    });",
            "  };",
            "}",
            "",
            comment_footer(),
            "",
        ]
        return "\n".join(lines)

    def generate_viewmodel_impl(self, spec: ScreenSpec) -> str:
        """Generate the user-editable ViewModel subclass."""
        data_type = f"{spec.name}Data"
        uc_name = f"{spec.name}UseCase"
        has_uc = any(uc.name == uc_name for uc in spec.use_cases)

        subdir = _layout_subdir(spec.layout_file)
        base_import = self._generated_vm_import_base
        if subdir:
            base_import = f"{base_import}/{_subdir_to_pascal(subdir).as_posix()}"

        lines = [
            f"// ViewModel for {spec.name}",
            'import { AppRouterInstance } from "next/dist/shared/lib/app-router-context.shared-runtime";',
            f'import {{ {data_type} }} from "{self._data_import_base}/{data_type}";',
            f'import {{ {spec.name}ViewModelBase }} from "{base_import}/{spec.name}ViewModelBase";',
        ]
        if has_uc:
            lines.append(f'import {{ {uc_name} }} from "@/usecase/{uc_name}";')
        lines += [
            "",
            f"export class {spec.name}ViewModel extends {spec.name}ViewModelBase {{",
        ]
        if has_uc:
            lines.append(f"  private readonly useCase: {uc_name};")
            lines.append("")
        lines += [
            "  constructor(",
            "    router: AppRouterInstance,",
            f"    getData: () => {data_type},",
            f"    setData: (data: {data_type} | ((prev: {data_type}) => {data_type})) => void",
            "  ) {",
            "    super(router, getData, setData);",
        ]
        if has_uc:
            lines.append(f"    this.useCase = new {uc_name}();")
        lines += [
            "    this.initializeEventHandlers();",
            "  }",
            "",
            "  protected initializeEventHandlers = () => {",
            "    this.updateData({",
            "      // TODO: Implement event handlers",
            "    });",
            "  };",
            "}",
            "",
        ]
        return "\n".join(lines)

    # --- Repository (single file, no protocol) ---

    def generate_repository_protocol(self, name: str, repo: RepositoryDef) -> str:
        """Not used — web has no protocol file. Same content as impl."""
        return self.generate_repository_impl(name, repo)

    def generate_repository_impl(self, name: str, repo: RepositoryDef) -> str:
        lines = [
            "// Generated by jui - edit the implementation as needed",
            'import { ApiClient, HttpMethod } from "@/core/network/apiClient";',
            'import { ApiEndpoint } from "@/core/network/apiEndpoints";',
            "",
            f"export class {name} {{",
        ]
        for method in repo.methods:
            sig = self._ts_method_signature(method, with_async=True)
            lines.append(f"  {sig} {{")
            lines.append(f'    throw new Error("TODO: Implement {method.name}");')
            lines.append("  }")
            lines.append("")
        lines += ["}", ""]
        return "\n".join(lines)

    # --- UseCase (single file, no protocol) ---

    def generate_usecase_protocol(self, name: str, uc: UseCaseDef) -> str:
        return self.generate_usecase_impl(name, uc)

    def generate_usecase_impl(self, name: str, uc: UseCaseDef) -> str:
        imports = []
        for dep in uc.repositories:
            imports.append(f'import {{ {dep} }} from "@/repository/{dep}";')

        lines = [f"// UseCase: {name}"] + imports + [
            "",
            f"export class {name} {{",
        ]

        if uc.repositories:
            for dep in uc.repositories:
                prop_name = _lower_first(dep)
                lines.append(f"  private readonly {prop_name}: {dep};")
            lines.append("")
            lines.append("  constructor() {")
            for dep in uc.repositories:
                prop_name = _lower_first(dep)
                lines.append(f"    this.{prop_name} = new {dep}();")
            lines.append("  }")
            lines.append("")

        for method in uc.methods:
            sig = self._ts_method_signature(method, with_async=True)
            lines.append(f"  {sig} {{")
            lines.append(f'    throw new Error("TODO: Implement {method.name}");')
            lines.append("  }")
            lines.append("")

        lines += ["}", ""]
        return "\n".join(lines)

    # --- Helpers ---

    def _map_type(self, spec_type: str) -> str:
        """Resolve a spec type to TypeScript. Same shape as iOS/Android.

        The type map is the one place that answers "what is this type on
        this platform" — optional suffixes (``String?`` → ``string |
        undefined``), collections, unions and all. This generator used to
        carry a private five-word table instead, which is how ``String?``
        reached the output verbatim and became invalid TS: the table only
        matched exact spellings, so every suffixed type missed it.

        Closure types walk sub-expression by sub-expression and then take
        the two TS-only touches the type map does not spell: Swift's ``->``
        arrow, and a trailing ``?`` that the ``$T?`` pattern cannot match
        across the ``>`` of an arrow.
        """
        if "->" in spec_type:
            ts = self._type_mapper.resolve_in_string(spec_type, "web")
            ts = ts.replace("->", "=>")
            if ts.endswith("?"):
                ts = f"{ts[:-1]} | undefined"
            return ts
        return self._type_mapper.resolve_class(spec_type, "web")

    def _import_lines(self, spec_type: str) -> list[str]:
        """``import { X } from "..."`` for each custom type in *spec_type*.

        The identifier is what gets imported, so it is resolved on its own.
        Importing the whole type expression emitted ``import { ItemImage? }``
        (plus a duplicate line) whenever the var carried an optional suffix.
        """
        lines: list[str] = []
        for ident in dict.fromkeys(_TYPE_IDENT_RE.findall(spec_type)):
            imports = self._type_mapper.resolve_imports(ident, "web")
            if not imports:
                continue
            symbol = self._type_mapper.resolve_class(ident, "web")
            lines.extend(f'import {{ {symbol} }} from "{imp}";' for imp in imports)
        return lines

    def _var_default_value(self, var) -> str | None:
        """TS initializer for a non-observable var, or None if there is none.

        Mirrors ``IosGenerator``/``AndroidGenerator._var_default_value``: the
        declared ``defaultValue`` from the type map wins, and there is no
        second opinion about what a zero value is.
        """
        if var.optional:
            # `?:` already admits absence — TS wants no initializer, and
            # writing one would contradict the declaration.
            return None
        try:
            default = self._type_mapper.resolve_default(var.type, "web")
        except Exception:  # pragma: no cover — defensive; TypeMapper is total
            default = None
        if default is not None:
            return _ts_literal(default)
        # A type that admits `undefined` (`[String]?`, `callback`, …) has a
        # zero value even though the type map declares no `defaultValue`:
        # `undefined` is inside the declared type, so writing it invents
        # nothing. Only types with no inhabitant we can name fall through
        # to the `!` branch.
        if _admits_undefined(self._map_type(var.type)):
            return "undefined"
        return None

    def _var_base_declaration(self, var, spec_name: str) -> str:
        """TypeScript public-field declaration for a non-observable var.

        Observable vars are part of ``<Name>Data`` so they're not re-emitted
        here.
        """
        type_str = self._map_type(var.type)
        if var.optional:
            # `optional: true` is a statement about the member; a `?` in the
            # type is a statement about the type. Both are kept — collapsing
            # either would silence something the spec said.
            return f"  public {var.name}?: {type_str};"
        init = self._var_default_value(var)
        if init is not None:
            return f"  public {var.name}: {type_str} = {init};"
        # Nothing can be synthesized: a custom type with no `defaultValue`
        # in .jsonui-type-map.json. iOS/Kotlin emit a bare declaration here
        # and let the compiler ask the author — which works only because
        # their output is a scaffold written once and editable afterwards.
        # This file is @generated and rewritten every build, so the same
        # emit is a dead end (TS2564) the consumer cannot clear. `!` is the
        # one TS spelling that neither invents a value nor rewrites the
        # declared type, but it is a promise nothing checks, so it never
        # goes out silently.
        self.warnings.append(SpecWarning(
            spec_name=spec_name,
            message=(
                f"dataFlow.viewModel.vars.{var.name}: '{var.type}' has no "
                f"declared defaultValue, so the web ViewModelBase declares it "
                f"with `!` (definite assignment) — a promise nothing verifies. "
                f"Either add a \"defaultValue\" for '{var.type}' to "
                f".jsonui-type-map.json, or declare the var \"optional\": true."
            ),
        ))
        return f"  public {var.name}!: {type_str};"

    def _ts_method_signature(self, method: MethodDef, with_async: bool = False) -> str:
        params = ", ".join(
            f"{p.name}: {self._type_mapper.resolve_class(p.type, 'web')}"
            for p in method.params
        )
        async_prefix = "async " if with_async and method.is_async else ""
        sig = f"{async_prefix}{method.name}({params})"
        if method.return_type:
            rt = self._type_mapper.resolve_class(method.return_type, "web")
            if method.is_async:
                sig += f": Promise<{rt}>"
            else:
                sig += f": {rt}"
        return sig


def _to_snake(name: str) -> str:
    return re.sub(r"([A-Z])", r"_\1", name).lower().lstrip("_")


def _lower_first(name: str) -> str:
    return name[0].lower() + name[1:] if name else name


def _layout_subdir(layout_file: str) -> str:
    """Extract the directory portion of a layout file path (without filename)."""
    if not layout_file or "/" not in layout_file:
        return ""
    return "/".join(layout_file.split("/")[:-1])


def _subdir_to_pascal(subdir: str) -> Path:
    """Convert a subdir path (e.g. 'my_page/settings') to PascalCase Path."""
    parts = [
        "".join(word.capitalize() for word in segment.split("_"))
        for segment in subdir.split("/") if segment
    ]
    return Path(*parts) if parts else Path()


_TYPE_IDENT_RE = re.compile(r"[A-Za-z_]\w*")

_BRACKETS = {"<": ">", "(": ")", "[": "]", "{": "}"}


def _admits_undefined(ts_type: str) -> bool:
    """True if ``undefined`` is one of *ts_type*'s top-level union members.

    Depth-aware on purpose: ``Record<string, string | undefined>`` admits no
    undefined *itself*, and a suffix match would say it does.
    """
    return any(member == "undefined" for member in _split_top_level(ts_type))


def _split_top_level(ts_type: str) -> list[str]:
    """Split a TS type on ``|`` that sits outside any bracket pair."""
    parts: list[str] = []
    buf: list[str] = []
    stack: list[str] = []
    for ch in ts_type:
        if ch in _BRACKETS:
            stack.append(_BRACKETS[ch])
        elif stack and ch == stack[-1]:
            stack.pop()
        if ch == "|" and not stack:
            parts.append("".join(buf).strip())
            buf = []
            continue
        buf.append(ch)
    parts.append("".join(buf).strip())
    return parts


def _ts_literal(value) -> str:
    """Render a Python default-value as a TypeScript literal."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list):
        return "[" + ", ".join(_ts_literal(v) for v in value) + "]"
    return str(value)
