"""Kotlin emitter — typed attribute extraction data classes (Kotlin 2.x).

Dependency choice
-----------------
The generated parsers take a plain ``Map<String, Any?>`` — **zero external
dependencies** (pure Kotlin stdlib). Both realistic call sites convert
cheaply:

- ``org.json``:   ``JSONObject.toMap()`` (or a 5-line manual walk)
- kotlinx:        ``JsonObject`` → primitive map via a small adapter

This keeps ``library-dynamic`` free to keep (or change) its JSON library
without regenerating, and keeps the generated code compilable with nothing
but ``kotlinc``.

Emitted files mirror the Swift emitter: ``AttrCodegenSupport.kt``,
``CommonAttributes.kt`` (shared base, emitted once), and per-component
``<Component>Attributes.kt`` diffs embedding ``common``.
"""
from __future__ import annotations

from ...core.type_mapper import TypeMapper
from .model import Attribute, AttrKind, AttrModel, Component
from .swift_emitter import _pascal, _split_words, dimension_type_name, enum_cases

PACKAGE = "com.kotlinjsonui.dynamic.generated"

HEADER = (
    "// @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.\n"
    "// Source of truth: shared/core/attribute_definitions.json\n"
    "// Regenerate: jui generate attr-bindings --lang kotlin\n"
)

_KOTLIN_KEYWORDS = frozenset({
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun",
    "if", "in", "interface", "is", "null", "object", "package", "return",
    "super", "this", "throw", "true", "try", "typealias", "typeof", "val",
    "var", "when", "while",
})


def emit(model: AttrModel) -> dict[str, str]:
    """Return ``{relative_path: content}`` for the Kotlin output (sorted)."""
    mapper = TypeMapper()
    files: dict[str, str] = {}
    files["AttrCodegenSupport.kt"] = _support_file(model)
    files["CommonAttributes.kt"] = _component_file(model.common, model, mapper)
    for comp in model.components:
        files[f"{comp.name}Attributes.kt"] = _component_file(comp, model, mapper)
    return dict(sorted(files.items()))


# ---------------------------------------------------------------------------
# Support file
# ---------------------------------------------------------------------------

def _support_file(model: AttrModel) -> str:
    parts = [HEADER.rstrip("\n"), "", f"package {PACKAGE}", ""]
    parts.append('''\
/**
 * Static value or `@{binding}` expression for a binding-capable attribute.
 */
sealed class AttrValue<out T> {
    data class Value<T>(val value: T) : AttrValue<T>()

    /** The expression inside `@{...}` (without the wrapper). */
    data class Binding(val expression: String) : AttrValue<Nothing>()

    fun valueOrNull(): T? = when (this) {
        is Value -> value
        is Binding -> null
    }

    fun bindingExpressionOrNull(): String? = when (this) {
        is Value -> null
        is Binding -> expression
    }
}

/**
 * Warning hook — generated parsers never crash on malformed input.
 * Unknown enum values / dimension keywords are reported here and parsed
 * as null.
 */
object AttrWarnings {
    var handler: ((String) -> Unit)? = null

    fun emit(message: String) {
        handler?.invoke(message)
    }
}

/** Coercion helpers used by the generated `parse(json)` implementations. */
object AttrCoerce {
    /**
     * Canonical-name lookup with alias fallback (aliases are resolved in
     * generated code so raw / non-normalized JSON keeps working).
     */
    fun lookup(
        json: Map<String, Any?>,
        canonical: String,
        aliases: List<String> = emptyList()
    ): Any? {
        json[canonical]?.let { return it }
        for (alias in aliases) {
            json[alias]?.let { return it }
        }
        return null
    }

    /** `"@{expr}"` → `"expr"`; anything else → null. */
    fun bindingExpression(raw: Any?): String? {
        val s = raw as? String ?: return null
        if (!s.startsWith("@{") || !s.endsWith("}") || s.length <= 3) return null
        return s.substring(2, s.length - 1)
    }

    /** Binding-only attributes accept `@{fn}` (canonical) or a bare name. */
    fun bindingExprOrName(raw: Any?): String? =
        bindingExpression(raw) ?: string(raw)

    fun string(raw: Any?): String? = raw as? String

    fun number(raw: Any?): Double? = (raw as? Number)?.toDouble()

    fun boolean(raw: Any?): Boolean? = raw as? Boolean

    fun obj(raw: Any?): Map<String, Any?>? {
        val m = raw as? Map<*, *> ?: return null
        val out = LinkedHashMap<String, Any?>(m.size)
        for ((k, v) in m) {
            if (k == null) continue
            out[k.toString()] = v
        }
        return out
    }

    fun array(raw: Any?): List<Any?>? = (raw as? List<*>)?.toList()

    /** Binding-capable attribute: `@{expr}` wins, then static coercion. */
    fun <T : Any> attrValue(raw: Any?, coerce: (Any) -> T?): AttrValue<T>? {
        if (raw == null) return null
        bindingExpression(raw)?.let { return AttrValue.Binding(it) }
        val v = coerce(raw) ?: return null
        return AttrValue.Value(v)
    }
}''')

    for keywords in model.dimension_keyword_sets:
        parts.append("")
        parts.append(_dimension_type(keywords))

    return "\n".join(parts) + "\n"


def _dimension_type(keywords: tuple[str, ...]) -> str:
    name = dimension_type_name(keywords)
    lines = [
        f"/** `number | {' | '.join(repr(k) for k in keywords)}` union "
        "(used by dimension-style attributes). */",
        f"sealed class {name} {{",
        f"    data class Number(val value: Double) : {name}()",
    ]
    for k in keywords:
        lines.append(f"    object {_pascal(k)} : {name}()")
    lines += [
        "",
        "    companion object {",
        f"        fun parse(raw: Any?, context: String): {name}? {{",
        "            AttrCoerce.number(raw)?.let { return Number(it) }",
        "            val s = raw as? String ?: return null",
        "            return when (s) {",
    ]
    for k in keywords:
        lines.append(f"                {_kotlin_str(k)} -> {_pascal(k)}")
    lines += [
        "                else -> {",
        "                    AttrWarnings.emit(\"$context: unknown dimension keyword '$s'\")",
        "                    null",
        "                }",
        "            }",
        "        }",
        "    }",
        "}",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Component files
# ---------------------------------------------------------------------------

def _component_file(comp: Component, model: AttrModel, mapper: TypeMapper) -> str:
    is_common = comp.name == "common"
    class_name = "CommonAttributes" if is_common else f"{comp.name}Attributes"

    parts = [HEADER.rstrip("\n"), "", f"package {PACKAGE}", ""]
    if is_common:
        parts.append("/** Attributes shared across all components (emitted once). */")
    else:
        parts.append(f"/** Typed attribute extraction for the `{comp.name}` component.")
        parts.append(" * Shared attributes are available via [common].")
        if comp.common_overrides:
            names = ", ".join(f"`{n}`" for n in comp.common_overrides)
            parts.append(
                f" * Overrides the common definition of: {names} "
                "(use the property on this class)."
            )
        parts.append(" */")

    parts.append(f"data class {class_name}(")
    ctor: list[str] = []
    if not is_common:
        ctor.append("    /** Attributes shared across all components. */")
        ctor.append("    val common: CommonAttributes,")
    for attr in comp.attrs:
        doc = _doc_comment(attr)
        if doc:
            ctor.append(f"    /** {doc} */")
        ctor.append(
            f"    val {_escape_ident(attr.name)}: {_prop_type(attr, mapper)}? = null,"
        )
    parts.extend(ctor)
    parts.append(") {")

    enums = [a for a in comp.attrs if a.kind is AttrKind.ENUM]
    for attr in enums:
        parts.extend(_enum_decl(attr))
        parts.append("")

    parts.append("    companion object {")
    parts.append(f"        fun parse(json: Map<String, Any?>): {class_name} = {class_name}(")
    if not is_common:
        parts.append("            common = CommonAttributes.parse(json),")
    for attr in comp.attrs:
        parts.append(
            f"            {_escape_ident(attr.name)} = {_parse_expr(attr)},"
        )
    parts.append("        )")
    for attr in enums:
        parts.append("")
        parts.extend(_enum_parse_func(attr))
    parts.append("    }")
    parts.append("}")
    return "\n".join(parts) + "\n"


def _enum_decl(attr: Attribute) -> list[str]:
    """Kotlin enum with a `from(raw)` mapping.

    Legacy value spellings that merge into one entry after identifier
    derivation (e.g. `"flow"` / `"Flow"`) all map to the same entry in
    `from`; `json` keeps the canonical (first-listed) spelling.
    """
    type_name = _pascal(attr.name)
    cases = enum_cases(attr.enum_values, _entry_name)
    lines = [f"    enum class {type_name}(val json: String) {{"]
    entries = [
        f"        {name}({_kotlin_str(canonical)})"
        for name, canonical, _ in cases
    ]
    lines.append(",\n".join(entries) + ";")
    lines += [
        "",
        "        companion object {",
        f"            fun from(raw: String): {type_name}? = when (raw) {{",
    ]
    for name, _, accepted in cases:
        rendered = ", ".join(_kotlin_str(v) for v in accepted)
        lines.append(f"                {rendered} -> {name}")
    lines += [
        "                else -> null",
        "            }",
        "        }",
        "    }",
    ]
    return lines


def _enum_parse_func(attr: Attribute) -> list[str]:
    type_name = _pascal(attr.name)
    return [
        f"        private fun parse{type_name}(raw: Any?): {type_name}? {{",
        "            val s = raw as? String ?: return null",
        f"            val v = {type_name}.from(s)",
        "            if (v == null) {",
        f"                AttrWarnings.emit(\"{attr.context}: unknown enum value '$s'\")",
        "            }",
        "            return v",
        "        }",
    ]


def _prop_type(attr: Attribute, mapper: TypeMapper) -> str:
    base = _base_type(attr, mapper)
    if attr.bindable:
        return f"AttrValue<{base}>"
    return base


def _base_type(attr: Attribute, mapper: TypeMapper) -> str:
    kind = attr.kind
    if kind in (AttrKind.STRING, AttrKind.COLOR, AttrKind.BINDING):
        return mapper.resolve_class("String", "android")
    if kind is AttrKind.NUMBER:
        return mapper.resolve_class("Double", "android")
    if kind is AttrKind.BOOLEAN:
        return mapper.resolve_class("Bool", "android")
    if kind is AttrKind.OBJECT:
        return "Map<String, Any?>"
    if kind is AttrKind.ARRAY:
        return "List<Any?>"
    if kind is AttrKind.ENUM:
        return _pascal(attr.name)
    if kind is AttrKind.DIMENSION:
        return dimension_type_name(attr.dimension_keywords)
    return "Any"  # ANY / RAW


def _parse_expr(attr: Attribute) -> str:
    aliases = ""
    if attr.aliases:
        rendered = ", ".join(_kotlin_str(a) for a in attr.aliases)
        aliases = f", listOf({rendered})"
    lookup = f"AttrCoerce.lookup(json, {_kotlin_str(attr.name)}{aliases})"

    kind = attr.kind
    if kind is AttrKind.BINDING:
        return f"AttrCoerce.bindingExprOrName({lookup})"

    coercers = {
        AttrKind.STRING: "AttrCoerce.string(it)",
        AttrKind.COLOR: "AttrCoerce.string(it)",
        AttrKind.NUMBER: "AttrCoerce.number(it)",
        AttrKind.BOOLEAN: "AttrCoerce.boolean(it)",
        AttrKind.OBJECT: "AttrCoerce.obj(it)",
        AttrKind.ARRAY: "AttrCoerce.array(it)",
        AttrKind.ANY: "it",
        AttrKind.RAW: "it",
    }
    if kind is AttrKind.ENUM:
        inner = f"parse{_pascal(attr.name)}(it)"
    elif kind is AttrKind.DIMENSION:
        type_name = dimension_type_name(attr.dimension_keywords)
        inner = f"{type_name}.parse(it, {_kotlin_str(attr.context)})"
    else:
        inner = coercers[kind]

    if attr.bindable:
        return f"AttrCoerce.attrValue({lookup}) {{ {inner} }}"

    if kind is AttrKind.ENUM:
        return f"parse{_pascal(attr.name)}({lookup})"
    if kind is AttrKind.DIMENSION:
        type_name = dimension_type_name(attr.dimension_keywords)
        return f"{type_name}.parse({lookup}, {_kotlin_str(attr.context)})"
    if kind in (AttrKind.ANY, AttrKind.RAW):
        return lookup
    call = inner.replace("(it)", "")
    return f"{call}({lookup})"


# ---------------------------------------------------------------------------
# Naming / escaping
# ---------------------------------------------------------------------------

def _doc_comment(attr: Attribute) -> str:
    notes: list[str] = []
    if attr.required:
        notes.append("required")
    if attr.default is not None:
        notes.append(f"default: {attr.default}")
    if attr.aliases:
        notes.append("aliases: " + ", ".join(attr.aliases))
    if attr.binding_direction:
        notes.append(f"binding: {attr.binding_direction}")
    if attr.kind is AttrKind.RAW and attr.raw_kinds:
        notes.append("accepts: " + " | ".join(attr.raw_kinds))
    if attr.deprecated:
        note = attr.deprecation_note or "deprecated"
        notes.append(f"DEPRECATED: {note}")
    doc = attr.description
    if notes:
        doc = (doc + " " if doc else "") + "[" + "; ".join(notes) + "]"
    return doc


def _entry_name(value: str) -> str:
    """SCREAMING_SNAKE_CASE Kotlin enum entry from a JSON value."""
    words: list[str] = []
    for chunk in _split_words(value):
        if not chunk:
            continue
        # Split camelCase chunks into words.
        current = chunk[0]
        for ch in chunk[1:]:
            if ch.isupper() and not current[-1].isupper():
                words.append(current)
                current = ch
            else:
                current += ch
        words.append(current)
    name = "_".join(w.upper() for w in words) or "EMPTY"
    if name[0].isdigit():
        name = "V_" + name
    return name


def _escape_ident(name: str) -> str:
    if name in _KOTLIN_KEYWORDS:
        return f"`{name}`"
    return name


def _kotlin_str(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
    )
    return f'"{escaped}"'
