"""Ruby emitter — typed attribute extraction modules.

Matches the ``rjui_tools`` converter style (``frozen_string_literal``,
plain modules, ``self.`` class methods). Each component gets a module with
``self.extract(hash)`` returning a Hash keyed by **canonical** attribute
name — this replaces hand-written ``json['text'] || json['label']`` alias
fallbacks in the codegen converters.

Representation:

- Extraction is table-driven: each module declares a frozen ``ATTRS`` row
  table and delegates to the shared ``AttrCoerce.extract_table`` engine in
  ``attr_support.rb`` (generated once).
- Binding-capable attributes are wrapped in ``AttrValue``
  (``value`` | ``binding_expression``), mirroring Swift/Kotlin
  ``AttrValue<T>``.
- Binding-only attributes (``type: "binding"``) also come back as an
  ``AttrValue``: ``@{expr}`` becomes a ``binding_expression``, anything
  else (bare handler name, action-object Hash, ...) is preserved raw as
  ``value`` — never de-wrapped to a bare string, never dropped.
- Enum attributes match case-insensitively; unknown values are reported
  through the ``AttrWarnings`` hook and PASSED THROUGH raw (never
  dropped, never a crash) — the raw string is the open-enum
  representation in Ruby.
- ``extract(hash, canonical_only: true)`` disables alias fallback for
  L1-normalized input (the normalizer has already rewritten aliases).
- ``ATTRS`` plus the ``rows`` / ``declared?`` / ``alias_map`` helpers are
  the documented public metadata contract for bridge layers.
- Component ``extract`` merges ``CommonAttributes.extract`` first, so a
  component-level redefinition (e.g. ``TextField.borderStyle``) wins.
"""
from __future__ import annotations

from .model import Attribute, AttrKind, AttrModel, Component

HEADER = (
    "# @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.\n"
    "# Source of truth: shared/core/attribute_definitions.json\n"
    "# Regenerate: jui generate attr-bindings --lang ruby\n"
)

SUPPORT_FILE = "attr_support.rb"


def emit(model: AttrModel) -> dict[str, str]:
    """Return ``{relative_path: content}`` for the Ruby output (sorted)."""
    files: dict[str, str] = {}
    files[SUPPORT_FILE] = _support_file()
    files["common_attributes.rb"] = _component_file(model.common)
    for comp in model.components:
        files[f"{_snake(comp.name)}_attributes.rb"] = _component_file(comp)
    return dict(sorted(files.items()))


# ---------------------------------------------------------------------------
# Support file
# ---------------------------------------------------------------------------

def _support_file() -> str:
    return HEADER + '''# frozen_string_literal: true

module JsonUI
  module Generated
    # `@{expr}` binding pattern (multiline-safe, anchored).
    BINDING_PATTERN = /\\A@\\{(.+)\\}\\z/m.freeze

    # Static value or `@{binding}` expression for a binding-capable
    # attribute (Ruby counterpart of Swift/Kotlin `AttrValue<T>`).
    class AttrValue
      attr_reader :value, :binding_expression

      def initialize(value: nil, binding_expression: nil)
        @value = value
        @binding_expression = binding_expression
      end

      def binding?
        !@binding_expression.nil?
      end

      # The original layout representation: `"@{expr}"` for a binding,
      # the static value otherwise (the `@{}` wrapper is always
      # recoverable).
      def raw
        binding? ? "@{#{@binding_expression}}" : @value
      end

      def ==(other)
        other.is_a?(AttrValue) &&
          other.value == value &&
          other.binding_expression == binding_expression
      end
    end

    # Warning hook — generated extractors never raise on malformed input.
    # Unknown enum values / dimension keywords are reported here and
    # extracted as nil.
    module AttrWarnings
      class << self
        attr_accessor :handler
      end

      def self.emit(message)
        handler&.call(message)
      end
    end

    # Declared-attribute metadata helpers — every generated module
    # exposes `rows` / `declared?` / `alias_map` built on these (public
    # metadata contract, see the directory README).
    module AttrTable
      # Canonical name => row. Earlier tables first; later tables
      # override on name collision (component rows override common —
      # same precedence as the generated `extract` methods).
      def self.build_rows(*tables)
        rows = {}
        tables.each { |table| table.each { |row| rows[row[:name]] = row } }
        rows.freeze
      end

      # Alias spelling => canonical name. Alias spellings that are ALSO
      # declared rows (e.g. `alpha` next to `opacity`) keep their own
      # row and are not redirected.
      def self.build_alias_map(rows)
        map = {}
        rows.each_value do |row|
          Array(row[:aliases]).each do |alias_name|
            map[alias_name] = row[:name] unless rows.key?(alias_name)
          end
        end
        map.freeze
      end
    end

    # Coercion engine shared by all generated `extract` methods.
    module AttrCoerce
      # Canonical-name lookup with alias fallback (aliases are resolved in
      # generated code so raw / non-normalized JSON keeps working). Pass
      # `canonical_only: true` for L1-normalized input — aliases are then
      # never consulted.
      def self.lookup(hash, canonical, aliases, canonical_only: false)
        return hash[canonical] unless hash[canonical].nil?
        return nil if canonical_only

        aliases.each do |alias_name|
          return hash[alias_name] unless hash[alias_name].nil?
        end
        nil
      end

      # `"@{expr}"` → `"expr"`; anything else → nil.
      def self.binding_expression(raw)
        return nil unless raw.is_a?(String)

        match = BINDING_PATTERN.match(raw)
        match && match[1]
      end

      # Binding-only attribute (`type: "binding"`): an AttrValue is
      # ALWAYS returned — `@{expr}` becomes a binding_expression,
      # anything else (bare handler name, action-object Hash, ...) is
      # preserved raw as `value`. Never de-wrapped, never dropped.
      def self.binding_value(raw)
        expr = binding_expression(raw)
        return AttrValue.new(binding_expression: expr) if expr

        AttrValue.new(value: raw)
      end

      def self.string(raw)
        raw.is_a?(String) ? raw : nil
      end

      def self.number(raw)
        raw.is_a?(Numeric) && !raw.is_a?(Complex) ? raw : nil
      end

      def self.boolean(raw)
        raw == true || raw == false ? raw : nil
      end

      def self.object(raw)
        raw.is_a?(Hash) ? raw : nil
      end

      def self.array(raw)
        raw.is_a?(Array) ? raw : nil
      end

      # Lenient enum matching: values match the declared set
      # case-insensitively; unknown values (including non-strings) are
      # reported through AttrWarnings and PASSED THROUGH raw — codegen
      # consumers must never lose author input to a definitions gap.
      # The raw value is Ruby's open-enum representation.
      def self.enum(raw, allowed, context)
        return raw if raw.is_a?(String) && allowed.any? { |v| v.casecmp?(raw) }

        shown = raw.is_a?(String) ? raw : raw.inspect
        AttrWarnings.emit("#{context}: unknown enum value '#{shown}'")
        raw
      end

      # number | keyword union (width / height): numbers and known keyword
      # strings pass through; unknown keyword strings warn and become nil.
      def self.dimension(raw, keywords, context)
        n = number(raw)
        return n unless n.nil?
        s = string(raw)
        return nil if s.nil?
        return s if keywords.include?(s)

        AttrWarnings.emit("#{context}: unknown dimension keyword '#{s}'")
        nil
      end

      # Row table interpreter — rows are generated per component module.
      def self.extract_table(hash, attrs, component, canonical_only: false)
        out = {}
        attrs.each do |row|
          raw = lookup(hash, row[:name], row[:aliases] || [],
                       canonical_only: canonical_only)
          next if raw.nil?

          value = coerce_row(raw, row, component)
          out[row[:name]] = value unless value.nil?
        end
        out
      end

      def self.coerce_row(raw, row, component)
        context = "#{component}.#{row[:name]}"
        if row[:bindable]
          expr = binding_expression(raw)
          return AttrValue.new(binding_expression: expr) if expr
        end

        value =
          case row[:kind]
          when :string, :color then string(raw)
          when :number then number(raw)
          when :boolean then boolean(raw)
          when :object then object(raw)
          when :array then array(raw)
          when :enum then enum(raw, row[:values], context)
          when :dimension then dimension(raw, row[:keywords], context)
          when :binding then binding_value(raw)
          else raw # :any / :raw — accepted as-is
          end
        return nil if value.nil?

        row[:bindable] ? AttrValue.new(value: value) : value
      end
    end
  end
end
'''


# ---------------------------------------------------------------------------
# Component files
# ---------------------------------------------------------------------------

def _component_file(comp: Component) -> str:
    is_common = comp.name == "common"
    module_name = "CommonAttributes" if is_common else f"{comp.name}Attributes"

    lines = [HEADER + "# frozen_string_literal: true", ""]
    lines.append(f"require_relative 'attr_support'")
    if not is_common:
        lines.append("require_relative 'common_attributes'")
    lines.append("")
    lines.append("module JsonUI")
    lines.append("  module Generated")
    if is_common:
        lines.append("    # Attributes shared across all components (emitted once).")
    else:
        lines.append(
            f"    # Typed attribute extraction for the `{comp.name}` component."
        )
        if comp.alias_of:
            lines.append(
                f"    # Component alias of `{comp.alias_of}` — full clone of the "
                "canonical table (the runtime selects tables by raw spelling)."
            )
        if comp.common_overrides:
            names = ", ".join(f"`{n}`" for n in comp.common_overrides)
            lines.append(
                f"    # Overrides the common definition of: {names}."
            )
    lines.append(f"    module {module_name}")
    lines.append("      # Declared-attribute rows — part of the public metadata")
    lines.append("      # contract together with `rows` / `declared?` / `alias_map`")
    lines.append("      # (see the directory README).")
    lines.append("      ATTRS = [")
    for attr in comp.attrs:
        doc = _doc_comment(attr)
        if doc:
            lines.append(f"        # {doc}")
        lines.append(f"        {_row(attr)}.freeze,")
    lines.append("      ].freeze")
    lines.append("")
    lines.append("      # Returns a Hash keyed by canonical attribute name.")
    lines.append("      # `canonical_only: true` disables alias fallback for")
    lines.append("      # L1-normalized input (aliases are already rewritten).")
    if is_common:
        lines.append("      def self.extract(hash, canonical_only: false)")
        lines.append("        AttrCoerce.extract_table(hash, ATTRS, 'common',")
        lines.append("                                 canonical_only: canonical_only)")
        lines.append("      end")
    else:
        lines.append("      # Common attributes are merged first; component-level")
        lines.append("      # definitions override on name collision.")
        lines.append("      def self.extract(hash, canonical_only: false)")
        lines.append(
            "        out = CommonAttributes.extract(hash, "
            "canonical_only: canonical_only)"
        )
        lines.append(
            "        out.merge!(AttrCoerce.extract_table(hash, ATTRS, "
            f"{_ruby_str(comp.name)},"
        )
        lines.append(
            "                                            "
            "canonical_only: canonical_only))"
        )
        lines.append("        out")
        lines.append("      end")
    lines.append("")
    lines.append("      # Canonical name => extraction row (common rows merged")
    lines.append("      # first; component rows override on name collision).")
    lines.append("      def self.rows")
    if is_common:
        lines.append("        @rows ||= AttrTable.build_rows(ATTRS)")
    else:
        lines.append(
            "        @rows ||= AttrTable.build_rows(CommonAttributes::ATTRS, ATTRS)"
        )
    lines.append("      end")
    lines.append("")
    lines.append("      # True when `key` is a declared canonical name or alias")
    lines.append("      # spelling.")
    lines.append("      def self.declared?(key)")
    lines.append("        rows.key?(key) || alias_map.key?(key)")
    lines.append("      end")
    lines.append("")
    lines.append("      # Alias spelling => canonical attribute name.")
    lines.append("      def self.alias_map")
    lines.append("        @alias_map ||= AttrTable.build_alias_map(rows)")
    lines.append("      end")
    lines.append("    end")
    lines.append("  end")
    lines.append("end")
    return "\n".join(lines) + "\n"


def _row(attr: Attribute) -> str:
    parts = [f"name: {_ruby_str(attr.name)}", f"kind: :{_kind_symbol(attr)}"]
    if attr.bindable:
        parts.append("bindable: true")
    if attr.aliases:
        rendered = ", ".join(_ruby_str(a) for a in attr.aliases)
        parts.append(f"aliases: [{rendered}].freeze")
    if attr.kind is AttrKind.ENUM:
        rendered = ", ".join(_ruby_str(v) for v in attr.enum_values)
        parts.append(f"values: [{rendered}].freeze")
    if attr.kind is AttrKind.DIMENSION:
        rendered = ", ".join(_ruby_str(k) for k in attr.dimension_keywords)
        parts.append(f"keywords: [{rendered}].freeze")
    return "{ " + ", ".join(parts) + " }"


def _kind_symbol(attr: Attribute) -> str:
    return attr.kind.value


def _doc_comment(attr: Attribute) -> str:
    notes: list[str] = []
    if attr.required:
        notes.append("required")
    if attr.default is not None:
        notes.append(f"default: {attr.default}")
    if attr.binding_direction:
        notes.append(f"binding: {attr.binding_direction}")
    if attr.kind is AttrKind.RAW and attr.raw_kinds:
        notes.append("accepts: " + " | ".join(attr.raw_kinds))
    if attr.deprecated:
        note = attr.deprecation_note or "deprecated"
        notes.append(f"DEPRECATED: {note}")
    doc = attr.description
    if notes:
        doc = (doc + " " if doc else "") + "[" + "; ".join(notes) + "]"
    return doc


def _snake(name: str) -> str:
    out = ""
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and (
            not name[i - 1].isupper()
            or (i + 1 < len(name) and name[i + 1].islower())
        ):
            out += "_"
        out += ch.lower()
    return out


def _ruby_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"
