// @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
// Source of truth: shared/core/attribute_definitions.json
// Regenerate: jui generate attr-bindings --lang kotlin

package com.kotlinjsonui.dynamic.generated

/** Attributes shared across all components (emitted once). */
data class CommonAttributes(
    /** Hide view */
    val hidden: AttrValue<Boolean>? = null,
    /** Unique identifier for the component */
    val id: String? = null,
    /** Click handler (camelCase) - binding only (@{functionName}) */
    val onClick: String? = null,
    /** Opacity/alpha value (0-1) [aliases: alpha] */
    val opacity: AttrValue<Double>? = null,
    /** Shadow configuration (string or object) [accepts: string | object] */
    val shadow: Any? = null,
    /** View visibility state (can be data binding) */
    val visibility: AttrValue<Visibility>? = null,
    /** Width (number, 'matchParent', 'wrapContent') - binding supported [required] */
    val width: AttrValue<DimensionValue>? = null,
) {
    enum class Visibility(val json: String) {
        VISIBLE("visible"),
        INVISIBLE("invisible"),
        GONE("gone");

        companion object {
            fun from(raw: String): Visibility? = when (raw) {
                "visible" -> VISIBLE
                "invisible" -> INVISIBLE
                "gone" -> GONE
                else -> null
            }
        }
    }

    companion object {
        fun parse(json: Map<String, Any?>): CommonAttributes = CommonAttributes(
            hidden = AttrCoerce.attrValue(AttrCoerce.lookup(json, "hidden")) { AttrCoerce.boolean(it) },
            id = AttrCoerce.string(AttrCoerce.lookup(json, "id")),
            onClick = AttrCoerce.bindingExprOrName(AttrCoerce.lookup(json, "onClick")),
            opacity = AttrCoerce.attrValue(AttrCoerce.lookup(json, "opacity", listOf("alpha"))) { AttrCoerce.number(it) },
            shadow = AttrCoerce.lookup(json, "shadow"),
            visibility = AttrCoerce.attrValue(AttrCoerce.lookup(json, "visibility")) { parseVisibility(it) },
            width = AttrCoerce.attrValue(AttrCoerce.lookup(json, "width")) { DimensionValue.parse(it, "common.width") },
        )

        private fun parseVisibility(raw: Any?): Visibility? {
            val s = raw as? String ?: return null
            val v = Visibility.from(s)
            if (v == null) {
                AttrWarnings.emit("common.visibility: unknown enum value '$s'")
            }
            return v
        }
    }
}
