// @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
// Source of truth: shared/core/attribute_definitions.json
// Regenerate: jui generate attr-bindings --lang kotlin

package com.kotlinjsonui.dynamic.generated

/** Typed attribute extraction for the `Label` component.
 * Shared attributes are available via [common].
 * Overrides the common definition of: `shadow` (use the property on this class).
 */
data class LabelAttributes(
    /** Attributes shared across all components. */
    val common: CommonAttributes,
    /** Two-way binding @{variable} [binding: two-way] */
    val bind: String? = null,
    /** Label internal padding [DEPRECATED: Compose Text has no edgeInset; use padding* instead.] */
    val edgeInset: Double? = null,
    /** Highlight color - hex string or color name from colors.json [aliases: hilightColor] */
    val highlightColor: String? = null,
    /** Partial text styling */
    val partialAttributes: List<Any?>? = null,
    /** Label-specific shadow override (object only) */
    val shadow: Map<String, Any?>? = null,
    /** Text content (supports data binding) */
    val text: AttrValue<String>? = null,
    /** Text transformation (legacy spellings kept for compat) [default: none] */
    val textTransform: TextTransform? = null,
    /** Associated value */
    val value: Any? = null,
) {
    enum class TextTransform(val json: String) {
        NONE("none"),
        WRAP_REVERSE("wrap-reverse"),
        FLOW("Flow");

        companion object {
            fun from(raw: String): TextTransform? = when (raw) {
                "none" -> NONE
                "wrap-reverse" -> WRAP_REVERSE
                "Flow", "flow" -> FLOW
                else -> null
            }
        }
    }

    companion object {
        fun parse(json: Map<String, Any?>): LabelAttributes = LabelAttributes(
            common = CommonAttributes.parse(json),
            bind = AttrCoerce.bindingExprOrName(AttrCoerce.lookup(json, "bind")),
            edgeInset = AttrCoerce.number(AttrCoerce.lookup(json, "edgeInset")),
            highlightColor = AttrCoerce.string(AttrCoerce.lookup(json, "highlightColor", listOf("hilightColor"))),
            partialAttributes = AttrCoerce.array(AttrCoerce.lookup(json, "partialAttributes")),
            shadow = AttrCoerce.obj(AttrCoerce.lookup(json, "shadow")),
            text = AttrCoerce.attrValue(AttrCoerce.lookup(json, "text")) { AttrCoerce.string(it) },
            textTransform = parseTextTransform(AttrCoerce.lookup(json, "textTransform")),
            value = AttrCoerce.lookup(json, "value"),
        )

        private fun parseTextTransform(raw: Any?): TextTransform? {
            val s = raw as? String ?: return null
            val v = TextTransform.from(s)
            if (v == null) {
                AttrWarnings.emit("Label.textTransform: unknown enum value '$s'")
            }
            return v
        }
    }
}
