// @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
// Source of truth: shared/core/attribute_definitions.json
// Regenerate: jui generate attr-bindings --lang kotlin

package com.kotlinjsonui.dynamic.generated

/** Typed attribute extraction for the `Text` component.
 * Component alias of `Label` — full clone of the canonical table (the runtime selects tables by raw spelling).
 * Shared attributes are available via [common].
 * Overrides the common definition of: `shadow` (use the property on this class).
 */
data class TextAttributes(
    /** Attributes shared across all components. */
    val common: CommonAttributes,
    /** Two-way binding @{variable} [binding: two-way] */
    val bind: AttrValue<Any>? = null,
    /** Label internal padding [DEPRECATED: Compose Text has no edgeInset; use padding* instead.] */
    val edgeInset: Double? = null,
    /** Highlight color - hex string or color name from colors.json [aliases: hilightColor] */
    val highlightColor: String? = null,
    /** Partial text styling */
    val partialAttributes: List<Any?>? = null,
    /** Label-specific shadow override (object only) */
    val shadow: Map<String, Any?>? = null,
    /** Text content (supports data binding) */
    val text: AttrValue<String>? = null,
    /** Text transformation (legacy spellings kept for compat) [default: none] */
    val textTransform: AttrEnum<TextTransform>? = null,
    /** Associated value */
    val value: Any? = null,
) {
    enum class TextTransform(val json: String) {
        NONE("none"),
        WRAP_REVERSE("wrap-reverse"),
        FLOW("Flow");

        companion object {
            /** Case-insensitive match against the declared values. */
            fun from(raw: String): TextTransform? = when (raw.lowercase()) {
                "none" -> NONE
                "wrap-reverse" -> WRAP_REVERSE
                "flow" -> FLOW
                else -> null
            }
        }
    }

    companion object {
        /**
         * Canonical attribute names declared for this component, including
         * the shared `common` set (public metadata contract).
         */
        val declaredAttributes: Set<String> = CommonAttributes.declaredAttributes + setOf(
            "bind",
            "edgeInset",
            "highlightColor",
            "partialAttributes",
            "shadow",
            "text",
            "textTransform",
            "value",
        )

        /**
         * Alias spelling → canonical attribute name (merged with common).
         * Alias spellings that are also declared attributes keep
         * their own entry and are not redirected.
         */
        val aliasMap: Map<String, String> = mapOf(
            "alpha" to "opacity",
            "hilightColor" to "highlightColor",
        )

        /** True when `key` is a declared canonical name or alias spelling. */
        fun isDeclared(key: String): Boolean =
            key in declaredAttributes || key in aliasMap

        /**
         * Pass `canonicalOnly = true` for L1-normalized input —
         * alias fallback is then disabled.
         */
        fun parse(json: Map<String, Any?>, canonicalOnly: Boolean = false): TextAttributes = TextAttributes(
            common = CommonAttributes.parse(json, canonicalOnly),
            bind = AttrCoerce.bindingValue(AttrCoerce.lookup(json, "bind")),
            edgeInset = AttrCoerce.number(AttrCoerce.lookup(json, "edgeInset")),
            highlightColor = AttrCoerce.string(AttrCoerce.lookup(json, "highlightColor", listOf("hilightColor"), canonicalOnly)),
            partialAttributes = AttrCoerce.array(AttrCoerce.lookup(json, "partialAttributes")),
            shadow = AttrCoerce.obj(AttrCoerce.lookup(json, "shadow")),
            text = AttrCoerce.attrValue(AttrCoerce.lookup(json, "text")) { AttrCoerce.string(it) },
            textTransform = parseTextTransform(AttrCoerce.lookup(json, "textTransform")),
            value = AttrCoerce.lookup(json, "value"),
        )

        private fun parseTextTransform(raw: Any?): AttrEnum<TextTransform>? {
            if (raw == null) return null
            (raw as? String)?.let { s ->
                TextTransform.from(s)?.let { return AttrEnum.Known(it) }
            }
            AttrWarnings.emit("Text.textTransform: unknown enum value '$raw'")
            return AttrEnum.Unknown(raw)
        }
    }
}
