// @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
// Source of truth: shared/core/attribute_definitions.json
// Regenerate: jui generate attr-bindings --lang swift

import Foundation

/// Static value or `@{binding}` expression for a binding-capable attribute.
public enum AttrValue<T> {
    case value(T)
    /// The expression inside `@{...}` (without the wrapper).
    case binding(String)

    public var value: T? {
        if case .value(let v) = self { return v }
        return nil
    }

    public var bindingExpression: String? {
        if case .binding(let e) = self { return e }
        return nil
    }
}

/// Warning hook — generated parsers never crash on malformed input.
/// Unknown enum values / dimension keywords are reported here and parsed
/// as `nil`.
public enum AttrCodegenWarnings {
    public static var handler: ((String) -> Void)?

    public static func emit(_ message: String) {
        handler?(message)
    }
}

/// Coercion helpers used by the generated `init(json:)` implementations.
public enum AttrCoerce {
    /// Canonical-name lookup with alias fallback (aliases are resolved in
    /// generated code so raw / non-normalized JSON keeps working).
    public static func lookup(
        _ json: [String: Any], _ canonical: String, _ aliases: [String] = []
    ) -> Any? {
        if let v = json[canonical], !(v is NSNull) { return v }
        for alias in aliases {
            if let v = json[alias], !(v is NSNull) { return v }
        }
        return nil
    }

    /// `"@{expr}"` → `"expr"`; anything else → `nil`.
    public static func bindingExpression(_ raw: Any?) -> String? {
        guard let s = raw as? String,
              s.hasPrefix("@{"), s.hasSuffix("}"), s.count > 3 else {
            return nil
        }
        return String(s.dropFirst(2).dropLast(1))
    }

    /// Binding-only attributes accept `@{fn}` (canonical) or a bare name.
    public static func bindingExprOrName(_ raw: Any?) -> String? {
        return bindingExpression(raw) ?? string(raw)
    }

    public static func string(_ raw: Any?) -> String? {
        return raw as? String
    }

    public static func number(_ raw: Any?) -> Double? {
        if let d = raw as? Double { return d }
        if let i = raw as? Int { return Double(i) }
        if let n = raw as? NSNumber { return n.doubleValue }
        return nil
    }

    public static func boolean(_ raw: Any?) -> Bool? {
        return raw as? Bool
    }

    public static func object(_ raw: Any?) -> [String: Any]? {
        return raw as? [String: Any]
    }

    public static func array(_ raw: Any?) -> [Any]? {
        return raw as? [Any]
    }

    public static func any(_ raw: Any?) -> Any? {
        if raw is NSNull { return nil }
        return raw
    }

    /// Binding-capable attribute: `@{expr}` wins, then static coercion.
    public static func attrValue<T>(
        _ raw: Any?, _ coerce: (Any) -> T?
    ) -> AttrValue<T>? {
        guard let raw = raw, !(raw is NSNull) else { return nil }
        if let expr = bindingExpression(raw) { return .binding(expr) }
        if let v = coerce(raw) { return .value(v) }
        return nil
    }
}

/// `number | 'matchParent' | 'wrapContent'` union (used by dimension-style attributes).
public enum DimensionValue: Equatable {
    case number(Double)
    case matchParent
    case wrapContent

    public static func parse(_ raw: Any?, _ context: String) -> DimensionValue? {
        if let n = AttrCoerce.number(raw) { return .number(n) }
        guard let s = raw as? String else { return nil }
        switch s {
        case "matchParent": return .matchParent
        case "wrapContent": return .wrapContent
        default:
            AttrCodegenWarnings.emit("\(context): unknown dimension keyword '\(s)'")
            return nil
        }
    }
}
