// @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
// Source of truth: shared/core/attribute_definitions.json
// Regenerate: jui generate attr-bindings --lang swift

import Foundation

/// `common.bind.primaryValue`: the attributes `bind` stands for, per section —
/// the table SwiftJsonUI Dynamic folds `bind` by, the one jsonui-cli's codegen
/// and validator read (shared/core/bind_fold.rb).
public enum JsonUIBindPrimaryValue {
    /// The attributes `bind` stands for on a node of `type`, the first being where
    /// a lone `bind` goes. `type` is matched as written: a section the table names,
    /// or one whose `_alias_of` names it; a type-synonym is the caller's to resolve
    /// first. An empty list: no entry, and `bind` is not folded.
    public static func attributes(for type: String, node: [String: Any]) -> [String] {
        switch type {
        case "Label", "Text":
            switch node["textTransform"] as? String {
            case "uppercase":
                return ["value"]
            default:
                return ["text", "value"]
            }
        case "Meter":
            return ["level"]
        default:
            return []
        }
    }
}
