// @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
// Source of truth: shared/core/attribute_definitions.json
// Regenerate: jui generate attr-bindings --lang swift

import Foundation

/// Attributes shared across all components (emitted once).
public struct CommonAttributes {
    public enum Visibility: String {
        case visible = "visible"
        case invisible = "invisible"
        case gone = "gone"
    }

    /// Canonical attribute names declared for this component (public metadata contract).
    public static let declaredAttributes: Set<String> = [
        "hidden",
        "id",
        "onClick",
        "opacity",
        "shadow",
        "visibility",
        "width",
    ]

    /// Alias spelling → canonical attribute name. Alias
    /// spellings that are also declared attributes keep their own
    /// entry and are not redirected.
    public static let aliasMap: [String: String] = [
        "alpha": "opacity",
    ]

    /// True when `key` is a declared canonical name or alias spelling.
    public static func isDeclared(_ key: String) -> Bool {
        return declaredAttributes.contains(key) || aliasMap[key] != nil
    }

    /// Hide view
    public let hidden: AttrValue<Bool>?

    /// Unique identifier for the component
    public let id: String?

    /// Click handler (camelCase) - binding only (@{functionName})
    public let onClick: AttrValue<Any>?

    /// Opacity/alpha value (0-1) [aliases: alpha]
    public let opacity: AttrValue<Double>?

    /// Shadow configuration (string or object) [accepts: string | object]
    public let shadow: Any?

    /// View visibility state (can be data binding)
    public let visibility: AttrValue<AttrEnum<Visibility>>?

    /// Width (number, 'matchParent', 'wrapContent') - binding supported [required]
    public let width: AttrValue<DimensionValue>?

    /// Pass `canonicalOnly: true` for L1-normalized input —
    /// alias fallback is then disabled.
    public init(json: [String: Any], canonicalOnly: Bool = false) {
        self.hidden = AttrCoerce.attrValue(AttrCoerce.lookup(json, "hidden"), AttrCoerce.boolean)
        self.id = AttrCoerce.string(AttrCoerce.lookup(json, "id"))
        self.onClick = AttrCoerce.bindingValue(AttrCoerce.lookup(json, "onClick"))
        self.opacity = AttrCoerce.attrValue(AttrCoerce.lookup(json, "opacity", ["alpha"], canonicalOnly: canonicalOnly), AttrCoerce.number)
        self.shadow = AttrCoerce.any(AttrCoerce.lookup(json, "shadow"))
        self.visibility = AttrCoerce.attrValue(AttrCoerce.lookup(json, "visibility"), { Self.parseVisibility($0) })
        self.width = AttrCoerce.attrValue(AttrCoerce.lookup(json, "width"), { DimensionValue.parse($0, "common.width") })
    }

    private static func parseVisibility(_ raw: Any?) -> AttrEnum<Visibility>? {
        guard let raw = raw, !(raw is NSNull) else { return nil }
        if let s = raw as? String {
            switch s.lowercased() {
            case "visible": return .known(Visibility.visible)
            case "invisible": return .known(Visibility.invisible)
            case "gone": return .known(Visibility.gone)
            default: break
            }
        }
        AttrCodegenWarnings.emit("common.visibility: unknown enum value '\(raw)'")
        return .unknown(raw)
    }
}
