// @generated by `jui generate attr-bindings` — DO NOT EDIT BY HAND.
// Source of truth: shared/core/attribute_definitions.json
// Regenerate: jui generate attr-bindings --lang swift

import Foundation

/// Attributes shared across all components (emitted once).
public struct CommonAttributes {
    public enum Visibility: String {
        case visible = "visible"
        case invisible = "invisible"
        case gone = "gone"
    }

    /// Hide view
    public let hidden: AttrValue<Bool>?

    /// Unique identifier for the component
    public let id: String?

    /// Click handler (camelCase) - binding only (@{functionName})
    public let onClick: String?

    /// Opacity/alpha value (0-1) [aliases: alpha]
    public let opacity: AttrValue<Double>?

    /// Shadow configuration (string or object) [accepts: string | object]
    public let shadow: Any?

    /// View visibility state (can be data binding)
    public let visibility: AttrValue<Visibility>?

    /// Width (number, 'matchParent', 'wrapContent') - binding supported [required]
    public let width: AttrValue<DimensionValue>?

    public init(json: [String: Any]) {
        self.hidden = AttrCoerce.attrValue(AttrCoerce.lookup(json, "hidden"), AttrCoerce.boolean)
        self.id = AttrCoerce.string(AttrCoerce.lookup(json, "id"))
        self.onClick = AttrCoerce.bindingExprOrName(AttrCoerce.lookup(json, "onClick"))
        self.opacity = AttrCoerce.attrValue(AttrCoerce.lookup(json, "opacity", ["alpha"]), AttrCoerce.number)
        self.shadow = AttrCoerce.any(AttrCoerce.lookup(json, "shadow"))
        self.visibility = AttrCoerce.attrValue(AttrCoerce.lookup(json, "visibility"), { Self.parseVisibility($0) })
        self.width = AttrCoerce.attrValue(AttrCoerce.lookup(json, "width"), { DimensionValue.parse($0, "common.width") })
    }

    private static func parseVisibility(_ raw: Any?) -> Visibility? {
        guard let s = raw as? String else { return nil }
        switch s {
        case "visible": return Visibility.visible
        case "invisible": return Visibility.invisible
        case "gone": return Visibility.gone
        default:
            AttrCodegenWarnings.emit("common.visibility: unknown enum value '\(s)'")
            return nil
        }
    }
}
